### ISSUE TITLE
Cannot scroll down beyond some point when the console is open

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1003]
1. Write a lengthy code
2. Open the console

Issue
You won't be able to scroll down beyond some point
![scroll](https://cloud.githubusercontent.com/assets/1845370/23107156/f7c8a920-f71d-11e6-8848-313e743ce637.png)

**Comment by hevayo** [comment]
Duplicate of #1664 closing this issue since above is new.
