### ISSUE TITLE
Application stop failed with openjdk1.8 

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/composer#1006]
Application stop failed with openjdk1.8.

Steps
1. Start Service
2. Stop service (Stop Application) (Execution Ending will not happen)
3. Try to start back.

Getting 9091 Address Already in Use error.

![image](https://cloud.githubusercontent.com/assets/7115693/23107231/515b9488-f71f-11e6-8cde-88cd9c3398f1.png)

**Comment by hevayo** [comment]
We currently use jps to identify the process before terminating. This is part of the sdk so try installing openjdk development version. Will keep this issue open until we find a better way to handle this.
