### ISSUE TITLE
Debug pointers are not shown in design view in Firefox

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1017]
Firefox version: 48.0
Please see the attached image, the debug pointers are not shown in firefox.
![composer_bug_firefox_1](https://cloud.githubusercontent.com/assets/15624590/23111831/482aaf7a-f751-11e6-84ff-9b3b9fc417bc.png)

**Comment by dakshika** [comment]
Seems working fine on latest FF 51.0.1

**Comment by pahans** [comment]
tested this on firefox 51 with the latest build. It's working now. fixed delete button alignment issue in above screenshot with https://github.com/ballerinalang/composer/pull/1225

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/1236

**Comment by hevayo** [comment]
Tested in 48 and fix is working.
