### ISSUE TITLE
Space between, variables in the service container and resource container

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#103]
<a href="https://github.com/srsharon"><img src="https://avatars.githubusercontent.com/u/10986966?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Thursday Jan 19, 2017 at 07:35 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/860_

----

The space between the mentioned should be reduced. 
![image](https://cloud.githubusercontent.com/assets/10986966/22138455/bae74310-df06-11e6-9f27-3f5ff9cdd652.png)

**Comment by dakshika** [comment]
@srsharon : Can you verify this on latest build

**Comment by srsharon** [comment]
This issue is fixed by PR https://github.com/ballerinalang/composer/pull/1403, The composer team is refactoring the code to react.js  due to the refactoring the PR is being held up for the moment.

**Comment by hevayo** [comment]
The UI for variable definition has changed but still the spacing needs to be fixed.
