### ISSUE TITLE
Give an error message when a user tries to add a function inside a type mapper without a return value

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1030]
1. Add two structs
2. Add a function without any input or output parameters
3. Add a type mapper 
4. Select the sources
5. Drag the function from the Current Package to the type mapper

Issue
User cannot drag the function as there are no input or output parameters. But doesn't give an indication on what needs to be done to fix the issue

**Comment by sinthuja** [comment]
Fixed with PR - https://github.com/dnwick/composer/pull/3. Once it's merged to the ballerinalang repo, this will be avaiable for testing.

**Comment by nadeeshaan** [comment]
Closing since the fix is merged
