### ISSUE TITLE
UI issues when a function is inserted inside a type mapper

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1032]
Pack - RC1
Browser - Chrome
OS - Mac

1. First add the target and the source of the type mapper.
2. Then drag a function

Issue
Alignment issues. No scroll bar
![screen shot 2017-02-20 at 1 09 24 pm](https://cloud.githubusercontent.com/assets/1845370/23117350/52d8684e-f775-11e6-8f63-f4f40b515e26.png)

Note: scroll bar appeard only after the mapping is done

**Comment by keizer619** [comment]
I have fixed this following commit [1] by enabling scroll bar within type mapper positioning of types and functions
[1] https://github.com/keizer619/composer/commit/6ad55419f2b27006207e5cb392f6f83d7f16c97b

**Comment by nadeeshaan** [comment]
Fix exist in the master. Hence closing the issue
