### ISSUE TITLE
Doc annotations are not supported in the Editor

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1039]
1. Add the doc annotations mentioned in the below link from the source code
https://github.com/ballerinalang/docerina/releases/tag/v0.8.0-RC1#configuring-the-docerina-maven-goal
2. Switch between the design view

Issue
These annotations are not supported in the editor

Expected
These annotations should be supported and available under the annotations drop down of the functions, structs etc.

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2336/files
