### ISSUE TITLE
Service container size

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#104]
<a href="https://github.com/srsharon"><img src="https://avatars.githubusercontent.com/u/10986966?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Thursday Jan 19, 2017 at 07:38 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/861_

----

The size of the service container should reduce from the bottom once a service is dropped into the canvas.

**Comment by dakshika** [comment]
similar issue reported on https://github.com/ballerinalang/composer/issues/103

**Comment by hevayo** [comment]
The above gaps are identical in the new react implementation.
