### ISSUE TITLE
Veriable Type "connection" need to remove from composer drop downs

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/composer#1042]
Since Veriable Type "connection" is no more supported by ballerina  runtime, better to remove it from variable declaration drop downs

![selection_193](https://cloud.githubusercontent.com/assets/3368635/23125432/ad6b9a20-f797-11e6-8e93-a67736ad883b.png)

**Comment by hemikak** [comment]
Fixes with https://github.com/ballerinalang/composer/pull/1081
