### ISSUE TITLE
reply/return statements not editable at first edit click

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1047]
click on statement
<img width="150" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23126733/24d4d5da-f79e-11e6-9fa3-6e424bb46374.png">

statement goes to edit mode
<img width="161" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23126745/2f2b426c-f79e-11e6-867f-7eb2ef13e4f9.png">

However, requires another click on the text to type in the text box
<img width="163" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23126753/3e221188-f79e-11e6-81ab-95103ce175fa.png">

Other statements are editable in the first click

**Comment by kaviththiranga** [comment]
Fixed by @NipunaMarcus in d0f0f9005fbc15c7d83c6d6c56ce6977f7845b2f
