### ISSUE TITLE
[Improvement] Remove expandable icon betweein File Explorer and tool pallet

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/composer#1048]
Since Editor doesn't allow to horizontally drag between File Explorer and tool pallet, its better to remove expandable icon 
![selection_196](https://cloud.githubusercontent.com/assets/3368635/23127541/6cd8684e-f7a1-11e6-9ee1-36e579cbf229.png)
![selection_197](https://cloud.githubusercontent.com/assets/3368635/23127542/6cd88a04-f7a1-11e6-9895-7248121b1f8d.png)

**Comment by dakshika** [comment]
What is the OS and browser that you are testing ?

**Comment by gvasanka** [comment]
On Firefox 51.0.1
