### ISSUE TITLE
Cannot properly stop service in composer when in windows

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1049]
OS: Windows 7 Professional

**Steps**
1. Open composer
2. Create a service
3. Run the service using composer.
4. Stop the service
5. Re run the service 

The service running is blocked due to address already in use. Although the composer.bat is stopped, the process is not clicked.

**Image**
![windows](https://cloud.githubusercontent.com/assets/15624590/23129192/b04e21e4-f7a7-11e6-9a0f-60c2443b2419.png)

**Comment by nadeeshaan** [comment]
Fixed in the latest
