### ISSUE TITLE
Services with package details are not runnable via Composer

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/composer#1056]
Steps:
1. Open a service with package details
2.  Try to run the service via Composer

Issue:
Observing following error.
![selection_199](https://cloud.githubusercontent.com/assets/3368635/23131492/2ca58f9a-f7b0-11e6-8c72-ae54b14b183b.png)

**Comment by dakshika** [comment]
Can you share the sample code

**Comment by gvasanka** [comment]
@dakshika 
I am running the following basic helloworld program, with  package hierarchy as in below pic

```
package org.asanka;
import ballerina.lang.system;
function main(string[] args) {
	system:println("Hello");
	
}
```


![selection_205](https://cloud.githubusercontent.com/assets/3368635/23505826/53032df6-ff6b-11e6-9efa-d1f8322c13f5.png)

**Comment by nadeeshaan** [comment]
@gvasanka can you run the same sample with `./ballerina run service /path/to/bal/file` and check whether it works?

**Comment by hevayo** [comment]
This is a bug we need to fix the launcher to support run ballerina files with package name.

**Comment by hevayo** [comment]
Fixed in latest
