### ISSUE TITLE
Saving a file does not add .bal extension 

### ISSUE THREAD

**Issue by raviu** [ballerinalang/composer#1057]
Saving a file from the composer does not add the .bal extension. This is ok but it seems if you open a file without .bal extension you can't run/debug it on the composer. 

ENV: macOS 10.12.3 JDK 1.8.0 Google Chrome 56

**Comment by dakshika** [comment]
Duplicate issue https://github.com/ballerinalang/composer/issues/132

**Comment by nadeeshaan** [comment]
Closing since the fix #1060 is merged
