### ISSUE TITLE
composer welcome page routing service sample has invalid configuration

### ISSUE THREAD

**Issue by chanakaudaya** [ballerinalang/composer#1059]
In the routing service sample, it has used "jsonutils" package. This needs to be renamed to "jsons".

**Comment by maheeka** [comment]
Fixed with https://github.com/ballerinalang/composer/commit/9a6c7570b1ef2c9930f97b2b43d840767a8d05ed

**Comment by chanakaudaya** [comment]
Even though the import statement is fixed, function calls are not fixed.

**Comment by lahirus** [comment]
Sent a PR. https://github.com/ballerinalang/composer/pull/1127

**Comment by maheeka** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1127/commits/efdf2b1342b4ae28705c1d63f55d5e5faa7c0e68 from @lahirus
