### ISSUE TITLE
Update Copyright and license of every file in Ballerina 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#106]
<a href="https://github.com/sameera-jayasoma"><img src="https://avatars.githubusercontent.com/u/2637328?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sameera-jayasoma](https://github.com/sameera-jayasoma)**
_Friday Jan 20, 2017 at 03:29 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/864_

----

From Sanjiva:

Guys copyright needs to simply say: Copyright (c) 2017, WSO2, Inc. http://wso2.com. All rights reserved.

License being Apachev2 is ok for now - I'll sort that out.

**Comment by maheeka** [comment]
Copyright headers are added for all source files in Composer.
