### ISSUE TITLE
alignment for imported packages in graphical view should be corrected

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#1069]
As shows in below image [1] when imports more packages, the alignment goes incorrectly. It is good to remove the empty space and show like in picture [2]
Checked on 0.8 GA tools pack

[1]
![pack1](https://cloud.githubusercontent.com/assets/15671620/23247490/6fe35f96-f9c0-11e6-860e-46c953945691.jpeg)

[2]
![pack2](https://cloud.githubusercontent.com/assets/15671620/23247495/788b3524-f9c0-11e6-84bc-874605439b8e.jpeg)

**Comment by hemikak** [comment]
Duplicate : https://github.com/ballerinalang/composer/issues/983

**Comment by maheeka** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1055/commits
