### ISSUE TITLE
Cannot drag a function into the type mapper after undo some operation in the type mapper.

### ISSUE THREAD

**Issue by sinthuja** [ballerinalang/composer#1070]
Steps to reproduce:
1) Create 2 structs
2) Drag and drop a type mapper and perform some operation such as select source/target, etc.
3) Delete the type mapper
4) Go to edit -> undo remove type mapper
5) Now drag and drop a function into the type mapper, and the UI rendering with scattered as it's trying to render the functions two times.

**Comment by sinthuja** [comment]
Fixed with PR - https://github.com/dnwick/composer/pull/2/files. Will be available in composer 0.8.1.

**Comment by nadeeshaan** [comment]
Closing since the fix is merged
