### ISSUE TITLE
Graphical veiw doesn't allow to rename a function /service - on firefox

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#1071]
Checked on 0.8 GA tools pack
 Firefox 51.0; Ubuntu 15.10

![funname](https://cloud.githubusercontent.com/assets/15671620/23248568/f85d9b98-f9c5-11e6-9ccb-478f9a2e362c.jpeg)

![sername](https://cloud.githubusercontent.com/assets/15671620/23248570/fa01afac-f9c5-11e6-90c8-f3d8ef17b1e6.jpeg)

**Comment by NipunaMarcus** [comment]
This is happening because of Firefox ASCII system for recognizing characters is bit different as it recognize backspace as a special key. will fix this.

**Comment by nadeeshaan** [comment]
Closing since the fix is merged
