### ISSUE TITLE
Refreshing the file when there is no target struct selected for the type mapper doesn't load the toolpallete and exception in the browser console

### ISSUE THREAD

**Issue by sinthuja** [ballerinalang/composer#1072]
Steps to reproduce.

1) Select the source struct, and don't select the target struct.
2) now refresh the file

The tool pallete will not be loaded, and there is an error -  'Cannot read property 'getAttributesArray' of undefined' logged in the browser console.

**Comment by sinthuja** [comment]
Fixed in the PR - https://github.com/dnwick/composer/pull/7.

**Comment by nadeeshaan** [comment]
Closing Based on the above comment and the Fix is merged
