### ISSUE TITLE
Issue with variable declaration from graphical view

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#1073]
- Drag and drop a variable definition (in function / service)
- Edit to declare a variable (e.g. string index;) : Taken as '= type var' (see attached)
Note that we can correct from source view anyway.
Checked on 0.8 GA tools pack

![declare](https://cloud.githubusercontent.com/assets/15671620/23251418/3a0f23c4-f9d3-11e6-986c-e319295fd054.jpeg)

**Comment by sumuditha-viraj** [comment]
Fixed with https://github.com/sumuditha-viraj/composer/commit/42a03c7a6135979dc03fbcefeb2361dc47baee20
