### ISSUE TITLE
Types do not load in the select2 drop down when refreshed

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1086]
<img width="228" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23300175/6e916cb0-faaa-11e6-8fab-f604fbcf1982.png">
<img width="1192" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23300178/742edbb2-faaa-11e6-8ecb-27de6f27a246.png">
<img width="416" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23300189/799c035e-faaa-11e6-94e3-f212e6e14516.png">

**Comment by NipunaMarcus** [comment]
Is this happening on a specific browser? because this is not getting reproduce on chrome which runs on ubuntu

**Comment by maheeka** [comment]
This should be fixed now with @hemikak's fixes.

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1081
