### ISSUE TITLE
0.8.0-M2 - When you try to save a new .bal file, display the existing .bal files

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#109]
<a href="https://github.com/ushanib"><img src="https://avatars.githubusercontent.com/u/12966170?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ushanib](https://github.com/ushanib)**
_Friday Jan 20, 2017 at 07:23 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/880_

----

 When you try to save a new .bal file, display the existing .bal files. Otherwise existing files will be replaced unknowingly if you give the same name. 
![save_bal_files](https://cloud.githubusercontent.com/assets/12966170/22139929/5e39bb94-df0f-11e6-86ce-2132f6880eff.png)

**Comment by NipunaMarcus** [comment]
In current save dialog if there is a .bal file with the name on the same directory user will be informed with a confirmation alert and ask to confirm whether to cancel saving the file or replace the existing file with the new file hence closing this issue.
