### ISSUE TITLE
Alignment issue of connector declarations 

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1101]
Connector declaration boxes are overlapped with resource borders
<img width="1439" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23313563/3b968ebe-fae4-11e6-96e0-9719bf95205f.png">

**Comment by maheeka** [comment]
The file explorer should be opened or tested in a higher resolution
<img width="1440" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23314333/89ca9adc-fae7-11e6-808f-ad06c117bed6.png">

**Comment by hevayo** [comment]
Fixed with new react implementation
