### ISSUE TITLE
Composer does not show the parser error to the user

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#1114]
Could be something in the TODO list. Just creating as observed.

Writing the program similar to [1] and following parse error is observed in composer log(which is correct). 
**2017-02-28 14:50:59,848 ERROR - Error in BLang parser rest service for composer**

But that is not shown to the user in the composer source view or design view, until he runs the program where he get following error.

**test.bal:9: undefined symbol 'x'**

After fixing it, runtime gave following error(due to 'print'). It wasn't shown in the composer as well.

**test.bal:12: undefined type 'print'**

[1]
import ballerina.net.http;
import ballerina.lang.system;
@http:BasePath("/echo")
service echo {
	@http:POST
	@http:Path("/")
	resource echo(message m) {
		x = 1;
		while (x < 10) {
			system:println(x);
			print x = x + 1;
		}
		http:convertToResponse(m);
		reply m;
	}
}

**Comment by hevayo** [comment]
fixed with 0.9.4
