### ISSUE TITLE
Introduce a menu for opened bal files

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1120]
When too many bal files are open, not all are shown in the tab controller. 

Can we introduce a scroll or a menu listing all open bal files that are not visible. Similar to below : 
<img width="1085" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23454079/0af7b656-fe91-11e6-9cfc-7690928fb9a5.png">

**Comment by dakshika** [comment]
this will automatically get fix by golden layout

**Comment by NipunaMarcus** [comment]
Composer tabs now has a scroller as to the golden layout adaptation which enable user to see previously opened but hidden because of the too many tabs are opened on window hence closing this issue.
