### ISSUE TITLE
When deleting/modifying endpoints worker overlaps with endpoints

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1121]
To reproduce : 
- add endpoint1
- add endpoint2
- add action
- add worker
worker now overlaps endpoint

<img width="720" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23454559/a46671d2-fe92-11e6-813a-3953d6527f71.png">

**Comment by nadeeshaan** [comment]
This is fixed in the latest master
