### ISSUE TITLE
Need to improve File or Folder open UI as current feature is very basic

### ISSUE THREAD

**Issue by dushansachinda** [ballerinalang/composer#1147]
![snip20170302_124](https://cloud.githubusercontent.com/assets/5661226/23540513/7c565720-ff96-11e6-81ad-8c27042abf29.png)

We need to improve the file or folder opening UI, its basic right now I mean, clicking and expanding one folder after another is so frustrating. let's bring what eclipse or any proper IDE has, like browse then open folders (popup) or cmd+shift+G behavior for mac.

**Comment by NatashaWso2** [comment]
This issue is referred in #4306, hence this issue can be closed.
