### ISSUE TITLE
Enhancement: Remove "new" while adding a definition

### ISSUE THREAD

**Issue by srsharon** [ballerinalang/composer#1174]
instead of this :
![image](https://cloud.githubusercontent.com/assets/10986966/23655715/40de3306-035c-11e7-9eea-d57003098be8.png)

Shall we have something like this : 
![image](https://cloud.githubusercontent.com/assets/10986966/23655803/a6588902-035c-11e7-827a-89a0b440069b.png)

**Comment by maheeka** [comment]
This is resolved with https://github.com/ballerinalang/composer/commit/52bcd5d50b06a9a7b5b5ca5ec730698d0db7755d by @hemikak
