### ISSUE TITLE
Cannot Delete the return type of a function after selecting the added return type

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#1197]
Issue:
Cannot delete the return type value from the list after selecting the return type from the list.
![cannot delete after select the return type](https://cloud.githubusercontent.com/assets/9109762/23983510/7db745a8-0a3a-11e7-8ecc-06fedd57868a.png)

Steps: 
1. Add a function
2. Add a return type to the function using return types task bar control
3. Select the added return type on the list

**Comment by nadeeshaan** [comment]
Closing based on the referenced Fix #1201
