### ISSUE TITLE
[Tool][Improvement]BasePath/Resource Path/ Resource Methods are hidden from UI after initializing (ref 3rd pic)

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#120]
<a href="https://github.com/dushansachinda"><img src="https://avatars.githubusercontent.com/u/5661226?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dushansachinda](https://github.com/dushansachinda)**
_Monday Jan 23, 2017 at 02:55 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/919_

----

We need to way to show the BasePath/ Resource Path declarations and the Verbs enabled rather hiding them through as given in below
![snip20170122_50](https://cloud.githubusercontent.com/assets/5661226/22190076/9d4f6d70-e0d5-11e6-979a-3a75ebe63774.png)

![snip20170122_52](https://cloud.githubusercontent.com/assets/5661226/22190073/9ba52078-e0d5-11e6-9f9d-dc1b91fb27e0.png)

Following shows, how it visible after defining the annotations. (We must show what customer has defined rather ask them to click '@' sign and see what they have configured.
![snip20170122_53](https://cloud.githubusercontent.com/assets/5661226/22190080/a3242718-e0d5-11e6-954c-ac9a6f8032b9.png)

**Comment by hevayo** [comment]
Annotation UI was changed in 0.88. With the new implementation user will be able to see the annotation by default and has the option of closing them if needed.
