### ISSUE TITLE
Debug points are not placed correctly

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1202]
![image](https://cloud.githubusercontent.com/assets/1029806/23984705/f40f7eae-0a40-11e7-9d76-5e595f7d0a62.png)

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/commit/864f67e0ac7aa181f125d3985a697ceef483f701

**Comment by nadeeshaan** [comment]
Closing the issue Based on the above comment
