### ISSUE TITLE
An array of arrays support

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#123]
<a href="https://github.com/wggihan"><img src="https://avatars.githubusercontent.com/u/2101222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wggihan](https://github.com/wggihan)**
_Monday Jan 23, 2017 at 06:54 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/928_

----

We need this for batch update in data integration. Basically, we need to define an array of QueryParameter arrays.

E.g: QueryParameter[][] parameters;

**Comment by maheeka** [comment]
supported in the latest versions by runtime
