### ISSUE TITLE
Needs to improve the file save dialog in tool

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#126]
<a href="https://github.com/uthaiyashankar"><img src="https://avatars.githubusercontent.com/u/2410076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [uthaiyashankar](https://github.com/uthaiyashankar)**
_Monday Jan 23, 2017 at 11:44 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/948_

----

(1) Need to have a way to create folder
(2) Need to identify the file system and start from home folder? 
(3) Any folder created after the server started (or parent folder accessed) is not appearing after that.

**Comment by pahans** [comment]
- [ ] Need to have a way to create folder
- [ ] Need to identify the file system and start from home folder?

**Comment by manuranga** [comment]
(1) is addressed by allowing users to type new dir, but should be improved to support nested dirs.

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master. Hence closing
