### ISSUE TITLE
[Editor] Cannot move statements/elements in a function in the Editor view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#127]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Jan 23, 2017 at 12:05 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/951_

----

Steps to reproduce:
1. Add a main function
2. Add an assignment or if condition
3. Try to move the position of the statement in the Editor

Issue
Cannot move the statements/elements

**Comment by maheeka** [comment]
Also reported in https://github.com/ballerinalang/composer/issues/292
