### ISSUE TITLE
firefox Error when renaming a function/service name

### ISSUE THREAD

**Issue by pahans** [ballerinalang/composer#1274]
firefox,

- Add a service or a function
- rename it, press arrow keys while editing
- "Invalid name" error message pops up when I press arrow keys.

**Comment by nadeeshaan** [comment]
I think this is due to the keystroke handling specific to the browsers. However the returned popup is valid since we do not allow such characters to be part of the service name

**Comment by pahans** [comment]
closing this issue because this fixed in latest master.
