### ISSUE TITLE
message vs m vs nothing

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/composer#1281]
Looks like there is no unified approach to message-related constructs in Composer:

- When I create a new service it by default gets parameter "m",
- convertToResponse has the default parameter "message",
- And reply has no parameter by default (and hence fails).

Let's have all message-related constructs have the same default variable name - e.g. m or msg.

**Comment by hemikak** [comment]
"message" type variables does not exists now as there are separate parameters coming in for request and response.

See example: https://github.com/ballerinalang/ballerina/blob/master/samples/getting_started/echoService/echoService.bal
