### ISSUE TITLE
[Editor] Browse option to browse the file location

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#129]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Jan 23, 2017 at 12:19 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/954_

----

![browse](https://cloud.githubusercontent.com/assets/1845370/22203671/349ab1ee-e194-11e6-87b4-87b8c50fc8a8.png)

**Comment by pahans** [comment]
If we use a file browse button here we will not be able to get the file path of the selected file.

**Comment by NipunaMarcus** [comment]
we have improved our file tree view to open the working directory of the user, reflect the typed path available in the File Path field on the tree and focus user to the mentioned path. Also supporting native file browser will need electron like support. For now tree view has been improved functionality and ux wise hence closing this issue.
