### ISSUE TITLE
[Editor] Auto populating defined variables in the editor 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#130]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Jan 23, 2017 at 12:27 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/955_

----

It's better to have the pre-defined variables auto populated when we use them in assigning values (eg: in a assignment statement) in the Editor. Otherwise users can make spelling mistakes when they type the full variable name

**Comment by maheeka** [comment]
This will be implemented with language server support

**Comment by NatashaWso2** [comment]
Suggestions are given for the variables already defined in the editor with the language server support in the latest master, hence this issue can be closed.
