### ISSUE TITLE
Issue when adding an action invocation inside a while

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#1304]
First add an If else and then add an action invocation to if or else statement
Now drag and drop a while to the main worker and add an action invocation to the while.
Bellow issue can be seen in the while re positioning 

![selection_073](https://cloud.githubusercontent.com/assets/1329674/24495414/b1119444-1552-11e7-8243-3d87bf2fcde9.png)

**Comment by maheeka** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1315 by @nadeeshaan
