### ISSUE TITLE
.bal extension is not automatically added when saving a file

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#132]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Jan 23, 2017 at 12:50 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/961_

----

Try to save a file without the extension (eg: test)

Issue
1. No error message is prompted to the user. Once the user tries to open the same file, the file will not be displayed

**Comment by sumuditha-viraj** [comment]
This is fixed.
