### ISSUE TITLE
[Editor] Expression edit selection PopUp load with empty content on Firefox browser

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#133]
<a href="https://github.com/gvasanka"><img src="https://avatars.githubusercontent.com/u/3368635?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gvasanka](https://github.com/gvasanka)**
_Monday Jan 23, 2017 at 13:03 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/964_

----

Steps:
1. Drag and drop main function 
2. Click on system:println
3. check the loading popup
Issue:
On Firefox 50.1.0 Pop-Up loading with empty content. Check screenshots taken on Firefox and Chrome

![selection_135](https://cloud.githubusercontent.com/assets/3368635/22204859/3387e906-e19a-11e6-8c49-d47da531b82c.png)
![selection_136](https://cloud.githubusercontent.com/assets/3368635/22204861/3499f276-e19a-11e6-9506-a56828ea0017.png)

**Comment by pahans** [comment]
related to https://github.com/ballerinalang/composer/pull/1225

**Comment by pahans** [comment]
works on firefox 51 and 52 but not on 50.0.1

**Comment by nadeeshaan** [comment]
closing since the fix is merged
