### ISSUE TITLE
[Enhancement][Tool] Allow Renaming the pallet by doubleclicking on the name

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#134]
<a href="https://github.com/yasassri"><img src="https://avatars.githubusercontent.com/u/7681361?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Tuesday Jan 24, 2017 at 02:13 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/970_

----

When Creating a new Bal project the pallet will be named as untitled. It will be a good option to allow the users to rename the project by double clicking on the pallet name.

![screenshot from 2017-01-24 07-39-26](https://cloud.githubusercontent.com/assets/7681361/22231278/985ae3c4-e208-11e6-8783-81e80b503f57.png)

**Comment by dakshika** [comment]
@hevayo : IMO we can try this with golden layout implementation

**Comment by dakshika** [comment]
This is not a default behavior of any editor.
