### ISSUE TITLE
Save As inactive until changes are made

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/composer#1359]
Looks like Save As is inactive until you make any changes. This is not a correct behavior. Save As should always be active.

Usecase: I open some file (e.g. a sample or previous project) and want to use it as basis of my next project. Before I make any changes, I want to Save it as a new file - to avoid accidentally changing the original file. I click File / Save As and supply the new name and path, and then make my changes.

At the moment, this usecase does not work because Save As is disabled until a change is made.

**Comment by dakshika** [comment]
fixed in latest mater
