### ISSUE TITLE
Commented out lines do not change highlighting

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/composer#1361]
When I comment out a line with // it still keeps its original highlighting. I expect the whole line to change color to the comment style

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1683

**Comment by kaviththiranga** [comment]
![selection_023](https://cloud.githubusercontent.com/assets/1505855/26442646/07ffb1a6-4153-11e7-8cbd-5747f5569449.png)
