### ISSUE TITLE
Browse connectors

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/composer#1362]
Need the ability to browse available connectors within Composer and pick the one to import

**Comment by DSotnikov** [comment]
I wanted to add Google Spreadsheet connector so I added: "import org.ballerinalang.connectors.googlespreadsheet;"

However, the left-hand palette in the design view still does not show the google spreadsheet commands - see attached image.
![no connector in the pallet](https://cloud.githubusercontent.com/assets/6956107/25016048/539233aa-2033-11e7-8270-3536cbe14fcd.png)

**Comment by sumuditha-viraj** [comment]
Fixed with #1762
