### ISSUE TITLE
Connector not added to palette after import

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/composer#1363]
I wanted to add Google Spreadsheet connector so I added: "import org.ballerinalang.connectors.googlespreadsheet;"

However, the left-hand palette in the design view still does not show the google spreadsheet commands - see attached image.
![no connector in the pallet](https://cloud.githubusercontent.com/assets/6956107/25016123/9dbe229a-2033-11e7-9d6f-2161d9066bf2.png)

**Comment by maheeka** [comment]
We currently support only native packages to be imported and added to tool palette. We will work on importing other connectors once they are bundled and available with the Ballerina runtime.

**Comment by sumuditha-viraj** [comment]
This issue is fixed with #1762 
<img width="354" alt="screen shot 2017-06-02 at 2 32 09 pm" src="https://cloud.githubusercontent.com/assets/6814264/26719010/82da6a80-47a0-11e7-97d2-14d21f07bf0c.png">
