### ISSUE TITLE
[Editor][Improvement] No support for "else if" in the editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#137]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Jan 24, 2017 at 05:08 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/978_

----

No support for the following in the editor.

if (){

}else if (){

} else{

}

**Comment by hevayo** [comment]
Fixed in master and will be released with 0.88
