### ISSUE TITLE
Debugger does not show details of array elements

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1375]
<img width="862" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/25116687/ec87b93a-242b-11e7-86b8-db27ebcb4244.png">

When debugging an array element, it only shows the element values and not details of types.

Can we show an expandable view for arrays with details of each element type, etc? Refer to string variable value vs array values in screenshot.

**Comment by pahans** [comment]
fixed in 0.91
