### ISSUE TITLE
Add search functionality for tools palette 

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1379]
There should be a search field to filter tools palette

![image](https://cloud.githubusercontent.com/assets/7569427/25128310/deb957fc-2456-11e7-9361-5daaa110eca5.png)

**Comment by hevayo** [comment]
I assume the search will filter out the elements in toolbar. Few questions 
1. Do we filter constructs.
2. How will the filtered out elements be displayed will they be still attached to groups or shall we display on a flat list with a sub text mentioning the group.

Suggesting to move list/icon switch to the constructs group title section to save some space.

**Comment by hevayo** [comment]
Implement in 0.88
