### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingBox' of undefined

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/composer#1382]
This is what I am now getting in Composer (for my app created in Composer 0.86, now opened in 0.86):

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js:10208

statement-container.js:349 Uncaught TypeError: Cannot read property 'getBoundingBox' of undefined
    at t.value (statement-container.js:349)
    at t.value (statement-container.js:225)
    at t.value (block-statement-view.js:176)
    at node.js:186
    at c (lodash.js:537)
    at Function.gs (lodash.js:9358)
    at t.value (node.js:183)
    at t.value (block-statement-view.js:163)
    at t.value (block-statement-view.js:110)
    at t.value (else-statement-view.js:47)

undefined Failed to load resource: the server responded with a status of 404 (Not Found)

The view is corrupt (half-missing), cannot switch to Source Code view.
![image](https://cloud.githubusercontent.com/assets/6956107/25156745/5cfc5eee-2451-11e7-9329-a4787ac1bf28.png)

**Comment by hevayo** [comment]
Implementation of the diagram has differ from the mention version. Please let us know if you get a similar error in new react based diagram rendering after 0.87 release.
