### ISSUE TITLE
Unnamed return types show with : in function node for datamapper

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1383]
<img width="280" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/25163343/2d0bc74c-24e7-11e7-9ec0-2bff3cdcd274.png">

**Comment by maheeka** [comment]
Happens only with functions defined in same bal file. Reason was the type not persisted correctly. Fixed with https://github.com/ballerinalang/composer/pull/1396. Related to https://github.com/ballerinalang/composer/issues/1395

**Comment by maheeka** [comment]
Reopening for the new implementation

**Comment by keizer619** [comment]
This has been fixed when including jstree for functions

<img width="347" alt="screen shot 2017-07-24 at 3 18 49 pm" src="https://user-images.githubusercontent.com/2918812/28517644-af7b78f8-7082-11e7-80f3-ac9b878e946c.png">
