### ISSUE TITLE
[Editor][Bug][Critical] - Validate against run time when saving the files

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#139]
<a href="https://github.com/erandidesilva"><img src="https://avatars.githubusercontent.com/u/15624590?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Jan 24, 2017 at 05:48 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/982_

----

Validations should happen against run time when saving files. Else problems as indicated in link can occur

[https://github.com/wso2/ballerina/issues/977](url)

**Comment by maheeka** [comment]
We allow opening invalid bal configurations now in the composer. When saving, we show the errors as in #325. Hence closing this issue.
