### ISSUE TITLE
Cannot represent white space strings in variable/const views

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1394]
<img width="228" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/25269323/bac9ceae-2699-11e7-8995-20fe020a86a2.png">
const string delimeter = " ";

In order to indicate the space value, double quotes must be shown.

**Comment by hevayo** [comment]
Implementation has changed and the specific issues is fixed in the new implementation.
