### ISSUE TITLE
[Editor][Improvement] Cannot update the type of the variables once it is added from the Editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#142]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Jan 24, 2017 at 08:14 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/991_

----

1. Add variables, eg: int value.
2. Change the type of the variable to String.

Issue
Editor does not support to update the type

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1189
