### ISSUE TITLE
[tool] Remove long path from breadcrumb 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#148]
<a href="https://github.com/dakshika"><img src="https://avatars.githubusercontent.com/u/6497326?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dakshika](https://github.com/dakshika)**
_Wednesday Jan 25, 2017 at 06:32 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1021_

----

need to hide lengthy path with .../end.bal and show full path on hover. 

![2017-01-24](https://cloud.githubusercontent.com/assets/6497326/22280356/18981f82-e2f6-11e6-9203-d8786b67a0ae.png)

**Comment by NipunaMarcus** [comment]
breadcrumb is no longer available and now file path is shown on a tooltip when hover on the tab hence closing this issue.
