### ISSUE TITLE
Support of REST API Guidelines

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/composer#1483]
According to our "REST API Guidelines", the name of a resource consisting of two words should become these two words separated by a hyphen. For example, "place-order" would be a valid name. When using such a name in the composer, the source view generates "place - order" as name (i.e. it introduces blanks). 

Next, the swagger view ignores this invalid (!) name. And when switching back to the composer, all the resource is gone.

We should fix this to support our own "REST API Guidelines" in Ballerina.

**Comment by hevayo** [comment]
From 0.9.4 "/place-order" should be added to path in resourceConfig annotation. And if the above path given it will generate a valid swagger and source. hence closing the issue.
