### ISSUE TITLE
Add a preloader

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1515]
Need to add a preloader animation to avoid partial loaded screen.

![image](https://cloud.githubusercontent.com/assets/7569427/25909221/18dbe984-35ca-11e7-9af2-de207cea116a.png)

**Comment by jeradrutnam** [comment]
PR: https://github.com/ballerinalang/composer/pull/1516

**Comment by nadeeshaan** [comment]
Closing since the PR has been merged
