### ISSUE TITLE
JMS client connector is not drawn in the composer 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1547]
**Steps**
1. Create a function/main method with one of the functions in [1].
2. Switch to the design view and verify the diagram
3. Interchange the properties variable and the connector initialization. E.g:
```
 jms:ClientConnector jmsEP = create jms:ClientConnector(properties);
 map properties = {"factoryInitial":"org.wso2.andes.jndi.PropertiesFileInitialContextFactory",
                        "providerUrl":"jndi.properties",
                        "connectionFactoryJNDIName": "QueueConnectionFactory",
                        "connectionFactoryType" : "queue"};
```
4. Switch to the design view and verify the diagram

**Issue**
The jms connector and other assignments are not displayed in the design in step 2. But, the connector will be displayed in step 4.

[1] https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-native/src/test/resources/samples/jmsClientConnectorTest.bal

**Comment by nadeeshaan** [comment]
This issue is fixed in the latest
Hence closing
