### ISSUE TITLE
Comments are getting removed when switched between the graphical and source view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#155]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Jan 25, 2017 at 11:37 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1032_

----

1. Add a comment from the source view (eg://this is a comment)
2. Navigate to the graphical view
3. Navigate to the source view

Issue
The comment will be removed

**Comment by nadeeshaan** [comment]
At the moment we are not supporting the comments at the editor. Hence labeling this as an enhancement

**Comment by NatashaWso2** [comment]
Comments added from the source view are not removed when switched between the graphical and source view in the latest master, hence closing this issue.
