### ISSUE TITLE
Editor is not working on IE 8

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#158]
<a href="https://github.com/gvasanka"><img src="https://avatars.githubusercontent.com/u/3368635?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gvasanka](https://github.com/gvasanka)**
_Wednesday Jan 25, 2017 at 13:51 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1038_

----

Steps:
1. Start ballerina editor on Windows 7
2. Open Editor window from IE8 browser window

Issue:
Getting completely black page as in below pics

![selection_138](https://cloud.githubusercontent.com/assets/3368635/22292869/6798e16a-e333-11e6-9c67-2c8153a5f036.png)
![selection_139](https://cloud.githubusercontent.com/assets/3368635/22293018/069df476-e334-11e6-8ac9-1d69ebb13a8b.png)

**Comment by dakshika** [comment]
@hevayo : Do we really need to consider older browsers? Even Microsoft stop the security updates for older ones and continue the IE11. https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

**Comment by dakshika** [comment]
@gvasanka : WDYT?

**Comment by maheeka** [comment]
We do not support IE8. We will support only for Edge onwards.
