### ISSUE TITLE
Statement delete/edit operations not working on IE11

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#159]
<a href="https://github.com/gvasanka"><img src="https://avatars.githubusercontent.com/u/3368635?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gvasanka](https://github.com/gvasanka)**
_Wednesday Jan 25, 2017 at 14:16 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1039_

----

Steps:
1. Start ballerina editor on Windows 7
2. Open the editor on IE11
3. Open the sample helloWorld.bal
4. Click on the "System:Println" statement 
5. Click on Edit or Delete button

Issue:
 Edit or Delete button doesn't work
![selection_140](https://cloud.githubusercontent.com/assets/3368635/22293776/e8af4250-e336-11e6-87a4-a5aeea0960f0.png)

**Comment by dakshika** [comment]
@gvasanka: Can you verify whether this still remains with the latest release?

**Comment by maheeka** [comment]
IE 11 support is not recommended and we will support only Edge going forward.
