### ISSUE TITLE
Auto refresh folders when users open files with 'Open File Explorer' button

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#1663]
Currently, we need to right click and 'refresh' to see the new files.

**Comment by lahirus** [comment]
<img width="275" alt="screen shot 2017-05-18 at 12 13 07 pm" src="https://cloud.githubusercontent.com/assets/3665108/26223914/c6de6054-3be5-11e7-8fcd-998a19e6de41.png">

**Comment by NatashaWso2** [comment]
Newly added files can be seen under the program directory without refreshing in the latest master, hence this issue can be closed
