### ISSUE TITLE
Cannot scroll to see last part of the file when 'Console' is open

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#1664]
We have to close the console to see the full file.

**Comment by sumuditha-viraj** [comment]
I tried with few sample .bal files, Couldn't reproduce the issue. Can you please attach a screenshot of the issue?  And also the .bal file you have tried ?

**Comment by sumuditha-viraj** [comment]
<img width="1415" alt="screen shot 2017-06-01 at 6 14 16 pm" src="https://cloud.githubusercontent.com/assets/6814264/26680237/33a70806-46f6-11e7-8fe7-79ccde3587e1.png">

**Comment by lahirus** [comment]
Sorry, I forgot to mention that it happens to source view,
<img width="1158" alt="screen shot 2017-06-01 at 8 22 11 am" src="https://cloud.githubusercontent.com/assets/3665108/26681666/8494ce72-46a3-11e7-81aa-12bf905c7983.png">

**Comment by hevayo** [comment]
Fix #1902
