### ISSUE TITLE
"Stop Application" does not terminate the service execution properly 

### ISSUE THREAD

**Issue by mefarazath** [ballerinalang/composer#1666]
I started my service via the composer,

`Running oauth_proxy.bal service.
ballerina: deploying service(s) in '/home/farazath/Desktop/IML/oauth_proxy/oauth_proxy.bal'
ballerina: started server connector http-9090`

Then pressing on the "Stop Application" button printed`
Program Terminated.`

When I try to run the same service again via the composer, it gives me the below error
```
Running oauth_proxy.bal service.
ballerina: deploying service(s) in '/home/farazath/Desktop/IML/oauth_proxy/oauth_proxy.bal'
ballerina: error starting server connectors: Cannot bind to http-9090 : Address already in use
Execution Ended.
```

using `lsof -i :9090` I was able to see that a process was still listening on 9090 port.

**Comment by pahans** [comment]
Hi @mefarazath,
what is the operating system you are running?
