### ISSUE TITLE
Composer doesn't allow to switch to source view or swagger view

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#1668]
Following is the code,

`
import ballerina.lang.system;
import ballerina.lang.messages;
import ballerina.net.http;

@http:BasePath{value: "/workersample"}
service workersample {

    @http:POST{}
    resource workersample(message m) {
        
        message response = testSimpleWorker(m);
        reply response;
    }
}

function testSimpleWorker(message msg) (message) {

    message result;

    int x = 100;
    float y;
    msg,x -> sampleWorker;
    system:println("Worker calling function test started");
    y,result <- sampleWorker;
    string s = messages:getStringPayload(result);
    system:println(s);
    system:println("Value received from worker is " + y);

    return result;

    worker sampleWorker {

        message result;
        message m;
        int a;
        float b = 12.34;
        m,a <- default;
        system:println("passed in value is " + a);
        json j;
        j = {"Response message" : "My message"};
        messages:setJsonPayload(m, j);
        b,m -> default;
        
    }
}
`

**Comment by lahirus** [comment]
Following error was shown when tried to switch to Swagger view,
<img width="371" alt="screen shot 2017-05-18 at 4 24 08 pm" src="https://cloud.githubusercontent.com/assets/3665108/26224170/d314bfb6-3be6-11e7-9446-f952b31d4c52.png">

**Comment by hemikak** [comment]
Following error is occurred when trying to switch to swagger view : 
`reference-type-init-expression.js:48 Uncaught TypeError: this.getVariableName is not a function
    at ReferenceTypeInitExpression.generateExpression (reference-type-init-expression.js:48)
    at right-operand-expression.js:35
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9359)
    at RightOperandExpression.generateExpression (right-operand-expression.js:34)
    at AssignmentStatement.generateStatementString (assignment-statement.js:69)
    at AssignmentStatement.initFromJson (assignment-statement.js:46)
    at worker-declaration.js:141
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9359)`
