### ISSUE TITLE
"If/Else, while" statement's UI representations should be improved.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#169]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Jan 26, 2017 at 06:47 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1057_

----

<img width="183" alt="screen shot 2017-01-26 at 12 13 12 pm" src="https://cloud.githubusercontent.com/assets/6814264/22322285/d9676496-e3c0-11e6-8fad-f69e482eb79e.png">

See the above figures. There is no difference between while, if/else statements and Lifeline's vertical line.  Lifeline's vertical line should be discontinued at bottom line of 'while' and the 'if/else' boxes.

**Comment by maheeka** [comment]
If else and while views are updated now and the above is no longer valid. 

<img width="188" alt="image" src="https://user-images.githubusercontent.com/1029806/32714135-59ff91ec-c844-11e7-952b-b8a194a89d71.png">
