### ISSUE TITLE
Implement an Expression editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#170]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Jan 26, 2017 at 07:14 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1059_

----

Substring match for text fields similar to expression editor in google spreadsheets. We will be able to reuse this editor wherever we want in the Ballerina editor.

**Comment by nadeeshaan** [comment]
Expression editor has been integrated into the design view. Hence closing the issue
