### ISSUE TITLE
Implement 'try-it' tool within the editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#171]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Jan 26, 2017 at 07:16 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1060_

----

Once users develop any ballerina configuration they should be able to try it within the editor itself. Need to provide a way to try-it.

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2442
