### ISSUE TITLE
ballerina favicon needs to be updated 

### ISSUE THREAD

**Issue by srsharon** [ballerinalang/composer#1717]
![image](https://cloud.githubusercontent.com/assets/10986966/26616830/166249ca-45ef-11e7-9d38-a2ab47f6ac9e.png)

the favicon should be 48 x 48 favicon.icon file 
![image](https://cloud.githubusercontent.com/assets/10986966/26616842/335062ec-45ef-11e7-9b6e-6cfea9adf261.png)

**Comment by hevayo** [comment]
Fixed with #1730
