### ISSUE TITLE
composer does not support parameterized imports 

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#1737]
`import ballerina.connectors.twitter;
import ballerina.connectors.salesforce as sf;
service HelloService {
    tw:TwitterConnector t = create tw:TwitterConnector(nil,nil,"clientkey","clientsecret",nil);
    @POST{}
    @Path{value: "/tweet"}
    resource tweet(message m) {
        tw:TwitterConnector.tweet(t, messages:getPayload(m));
    }
}`

If we have the salesforce connector import as `import ballerina.connectors.salesforce as sf;` composer will omit the `sf` part. 
Also we cannot include such in the design view imports section

**Comment by hemikak** [comment]
Closed as this issue is fixed.

**Comment by NatashaWso2** [comment]
Fixed in the latest master 9938a9a298383b2f47f32dd7e697217df6841f87
