### ISSUE TITLE
Adding right click menu for delete option etc.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#174]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Jan 26, 2017 at 08:05 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1064_

----

**Comment by dakshika** [comment]
this is fixed in the latest release
