### ISSUE TITLE
Need to click on debug icon twice to start Composer in debug mode in the Cloud

### ISSUE THREAD

**Issue by SabraO** [ballerinalang/composer#1769]
When I debug the application without setting any debug points, the first time I try, the service just gets started (not in debug mode). Then I stop the application (by clicking on "Stop Application" when I click on the "Run" button). After which I again click on the debug icon, and now the application starts in debug mode. So in order to start the application in debug mode, if I don't set a debug point, then I need to click the debug icon two times.

**Comment by pahans** [comment]
Root cause to this issue was UI doesnt give feedback till debugger connects to backend. Added a waiting message.
fixed with https://github.com/ballerinalang/composer/pull/2639
