### ISSUE TITLE
Incorrect URL to access service running in Cloud Composer container

### ISSUE THREAD

**Issue by SabraO** [ballerinalang/composer#1770]
![test](https://cloud.githubusercontent.com/assets/5234592/26726855/3d34558c-47c2-11e7-9033-1247c8dcc25e.png)

When the user runs a ballerina service in Cloud 'http-9090' is displayed. Instead of 'http-9090' we need to display the URL by which the customer can access the service deployed in Composer container. Therefore this value needs to be read by a config file.

**Comment by sumuditha-viraj** [comment]
Fixed with PR #1680
