### ISSUE TITLE
On window resize canvas rendering issue

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1779]
Need to rerender canvas on window resize

![image](https://cloud.githubusercontent.com/assets/7569427/26778241/18339246-49fe-11e7-96b5-af30706180cf.png)

**Comment by hevayo** [comment]
We have implemented diagram resizing with window resizing. it breaks if there is an error. Plese check if you can constantly reproduce.

**Comment by hevayo** [comment]
Fix #1887
