### ISSUE TITLE
Action invocation needs to have different look and feel

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#178]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Jan 26, 2017 at 08:20 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1070_

----

And also the way we connect actions to connector declaration is not intuitive.

**Comment by maheeka** [comment]
The round icon indicating that the arrow must be drawn appears only when we move the mouse to the right corner. Even then it is not clear that an arrow must be drawn.

Automatically connecting to the connector declaration or indicating with an arrow must be done.

**Comment by hevayo** [comment]
Icon to connect with connectors are shown on hover from 0.94
