### ISSUE TITLE
Unable to run the package via composer

### ISSUE THREAD

**Issue by sashikamw** [ballerinalang/composer#1789]
When a ballerina file includes the package name (ex: package org.wso2 defined in sample.bal file) composer do not provide any option to execute the package. It only supports to run a selected ballerina file.

Following error observed
ballerina: incorrect package in 'passthroughPredefined.bal': expected '', found 'org.wso2'

**Comment by pahans** [comment]
related to https://github.com/ballerinalang/composer/issues/1056

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/1821
