### ISSUE TITLE
Right align the connectors and we should use a different symbol to signify the connectors. 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#179]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Jan 26, 2017 at 08:26 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1072_

----

**Comment by maheeka** [comment]
This was opened to differentiate between default workers and connector declarations. Anyhow, at the moment, we do this with colours. Going forward, we will add an icon to differentiate.

**Comment by hevayo** [comment]
fixed in 0.93
