### ISSUE TITLE
Make given file open when the composer UI loads

### ISSUE THREAD

**Issue by amalkasubasinghe** [ballerinalang/composer#1798]
For cloud deployment, we need a mechanism to open a given bal file when the user loads the Ballerina Composer.

**Comment by hevayo** [comment]
With 0.88 you can open a specific  file by passing the file path as command argument.

**Comment by sumuditha-viraj** [comment]
Fixed with #1875 

Users can specify the file path of the .bal file, using --file directive. See the attached image.

<img width="698" alt="screen shot 2017-06-10 at 2 27 57 pm" src="https://user-images.githubusercontent.com/6814264/27008697-c145d410-4e96-11e7-8ac7-61b07e106d85.png">
