### ISSUE TITLE
[Editor] [UX] Compatibility issue with Windows Edge browser

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#180]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Thursday Jan 26, 2017 at 09:35 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1075_

----

Tested on Windows 10 -Edge browser and Graphical view issues are attached herewith
1. Edit panel goes bottom of the page
![ui_edit](https://cloud.githubusercontent.com/assets/15671620/22326323/2c5c63ba-e3d8-11e6-8c0a-2055857c8e81.jpeg)

2. In home page of editor, buttons are misplaced if window is minimized
![editor2](https://cloud.githubusercontent.com/assets/15671620/22361502/66a8fce2-e480-11e6-97c7-9538e3600209.jpeg)

**Comment by dakshika** [comment]
@kavithasub : Is this still valid with latest versions?

**Comment by hevayo** [comment]
Implementation has differed closing this issue due to we have an updated issue here https://github.com/ballerinalang/composer/issues/2460
