### ISSUE TITLE
0.88 composer fails to render some concatenated strings

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#1807]
If there is an assignment statement in the following format the composer fails to render.

`string s = "test"+astringvariable+"test"`

The following bal file fails to open in the composer due to lines 17 and 26.

...

import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.lang.jsons;
import ballerina.lang.strings;

@http:BasePath {value:"/geochain"}
service GeoChain {

    @http:GET{}
    resource geochainResource (message m) {
        //retrieving request paramters.
        json request = messages:getJsonPayload(m);
        string country = jsons:getString(request,"$.country");
        string username = jsons:getString(request,"$.username");

        string countryInfoQueryParams = "/countryInfoJSON?lang=en&country=" + country + "&username=" + username;
        http:ClientConnector geoserviceEP = create http:ClientConnector("http://api.geonames.org");
        message msg = {};

        //calling the country info endpoint
        message countryInfoResponse = http:ClientConnector.get (geoserviceEP, countryInfoQueryParams, msg);
        json capitalJ = jsons:getJson(messages:getJsonPayload(countryInfoResponse), "$.geonames[:1].capital");
        string capitalS = strings:valueOf(capitalJ);
        string capitalParsed = strings:toLowerCase(strings:subString(capitalS, strings:indexOf(capitalS, "\"") + 1, strings:lastIndexOf(capitalS, "\"")));
        string wikiSearchQueryParams = "/wikipediaSearch?q="+ capitalParsed + "&maxRows=10&username=" + username;

        //calling the wiki search endpoint
        message wikiSearchResponse = http:ClientConnector.get (geoserviceEP,wikiSearchQueryParams,msg);
        xml response = messages:getXmlPayload(wikiSearchResponse);
        messages:setXmlPayload(m,response);
        reply m;
    }

}

**Comment by hevayo** [comment]
Checked with a latest build and this seems to be working. Will keep this open to test with final pack.

**Comment by hevayo** [comment]
This is fix in latest
