### ISSUE TITLE
File explore h.scroll on right on load

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1827]
![image](https://user-images.githubusercontent.com/7569427/26964380-c93c96ba-4d0e-11e7-8167-f11696ece55d.png)

If there are longer file names, first part of the text is getting cut of. Need to move scrollbar to left on load.

![image](https://user-images.githubusercontent.com/7569427/26964725-813ff620-4d10-11e7-8e22-39339747191a.png)

Shall we do something like above, so that it will show the most closest path, if there are duplicate names

**Comment by hemikak** [comment]
To be addressed with Golden Layout

**Comment by hevayo** [comment]
fixed in 0.9.4
