### ISSUE TITLE
[Editor] Graphical view displays unnecessary symbol when drag & drop a resource multiple time 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#183]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Thursday Jan 26, 2017 at 10:17 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1080_

----

Please check the attachment.
- Do delete and drag & drop a 'Resource' into service multiple time, unnecessary symbol appears in Graphical view.
- navigation is not helped to remove those.
- Still the same symbol appears when open a new file in Graphical view (image 2) until browser refreshed
![drag_drop](https://cloud.githubusercontent.com/assets/15671620/22327550/c933c05c-e3dd-11e6-8253-b50a3d635274.jpeg)
![newfile](https://cloud.githubusercontent.com/assets/15671620/22327670/64f9928c-e3de-11e6-8eb2-e893ecaf05b8.jpeg)

**Comment by nadeeshaan** [comment]
This issue is due to an error which happened. Could not reproduce the issue in the latest master. If the issue still reproduce please reopen with the steps to reproduce
