### ISSUE TITLE
Imports/Global toggle buttons should persist on toggle

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1830]
![image](https://user-images.githubusercontent.com/7569427/26966705-daa17b1e-4d18-11e7-95e4-78d6817b5cb8.png)

![image](https://user-images.githubusercontent.com/7569427/26966757-14ff8c6a-4d19-11e7-976d-d27a0f32c986.png)

Currently button hides if the field is expanded. Instead we can keep the button on the same location and add a pressed state to them

**Comment by maheeka** [comment]
Duplicated in https://github.com/ballerinalang/composer/issues/2067
