### ISSUE TITLE
Support named package imports

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#184]
<a href="https://github.com/maheeka"><img src="https://avatars.githubusercontent.com/u/1029806?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Jan 26, 2017 at 11:39 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1081_

----

Support syntax
[import PackageName [version ImportVersionNumber] [as Identifier];]*

Connector declarations and action invocations should use the identifier instead of package name

**Comment by maheeka** [comment]
Duplicated in #1737
