### ISSUE TITLE
Statements has a connection arrow

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1845]
![image](https://user-images.githubusercontent.com/7569427/26973097-59c0eb64-4d32-11e7-87a1-1a1c3e6d1d7f.png)

Need to remove connection arrow on none connector statements. And UI breaks on user draws an arrow

**Comment by nadeeshaan** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1859.
Hence closing the issue
