### ISSUE TITLE
Support native action in composer

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#1874]
Currently you cannot have native action in composer, which will throw error while switching from source to design

**Comment by NipunaMarcus** [comment]
now adding a custom client connector and adding a action to connect to it will result in adding another client connector of same type.

![clientconnector issue](https://user-images.githubusercontent.com/9109762/32267242-9b27e256-bf10-11e7-914f-d763e3d5159c.png)

**Comment by nadeeshaan** [comment]
Fixed from v0.95 onwards.
Hence closing the issue
