### ISSUE TITLE
Remove multiple outputs removes the whole statement

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1896]
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1029806/27009918-2e471554-4eb7-11e7-9715-01cca5d438e8.png">

    transform {
        p.first_name,p.last_name = e.name;
        p.age = e.age;
        p.city = e.name;
    }

removing first connection, removes the whole 1st statement.

**Comment by keizer619** [comment]
This has been fixed when fixing following issue
https://github.com/ballerinalang/composer/issues/2437
