### ISSUE TITLE
[Editor] Cannot declare long, float, double, json, xml, message array type variables from the graphical view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#190]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Jan 27, 2017 at 06:03 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1095_

----

Cannot declare long, float, double, json, xml, message array type variables from the graphical view. Currently it supports only int and string types.

**Comment by sumuditha-viraj** [comment]
As shown in the following image users can add arbitrary type name. Likewise users can add float[], long[] etc.
<img width="675" alt="screen shot 2017-03-24 at 6 02 14 pm" src="https://cloud.githubusercontent.com/assets/6814264/24294345/0b780aee-10bc-11e7-8c23-5eeb9535e446.png">
