### ISSUE TITLE
Border issue in Expression Editor in edit mode

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1921]
<img width="168" alt="image" src="https://user-images.githubusercontent.com/1029806/27021392-9bbe6656-4f65-11e7-9390-bb1d463df067.png">
<img width="150" alt="image" src="https://user-images.githubusercontent.com/1029806/27021432-e3927c56-4f65-11e7-8a62-5732344b1220.png">

In edit mode of expression editor, the border gets overlapped with the textbox, making the border on left and right hidden at some places.

**Comment by maheeka** [comment]
This is reproduced in 90% resolution :)

**Comment by keizer619** [comment]
Closing as recent UX improvements has fixed this and shows like below screenshot

<img width="292" alt="screen shot 2017-07-24 at 2 33 45 pm" src="https://user-images.githubusercontent.com/2918812/28515897-e6544752-707c-11e7-8fd5-6b8c4347cbd7.png">
