### ISSUE TITLE
File Browser Tree Navigator Improvements

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1924]
Issue 1 :
<img width="222" alt="image" src="https://user-images.githubusercontent.com/1029806/27021553-ddd249da-4f66-11e7-9b76-717ecef6a8b5.png">
Clicking on 'restfulService' text and arrow both will expand the folder. However, to expand the next level folders, clicking on the text doesn't work. Only clicking on the arrow works.

Issue 2:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/1029806/27021560-e60cba40-4f66-11e7-8760-4608ed176a6e.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/1029806/27021604-3a16ad58-4f67-11e7-87a9-f4b8d5362ed0.png">
Arrows in first level and second level is different. first level has ^ and > and second level has a filled arrow. Second level collapse icon is barely visible

**Comment by dakshika** [comment]
First issue fixed in latest master

**Comment by hevayo** [comment]
Fixed with 0.9.4
