### ISSUE TITLE
Transform throwing an error when clicking on the expand button 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#1929]
Issue:
Transform statement cannot expand if it put in a if

Steps:
1. Add a service.
2. Add a IF statement 
3. Put a transform statement onto IF statement 

Image:
![error-transform](https://user-images.githubusercontent.com/9109762/27022147-3d67569e-4f6a-11e7-95fa-7c03bbb995a7.png)

**Comment by maheeka** [comment]
This needs to be solved by using the language server to get the inscope variables

**Comment by keizer619** [comment]
This issue has been fixed in following commit
https://github.com/ballerinalang/composer/pull/2000/commits/a365eb62d7fe0b6909d962219ba830d39c2f45b3
