### ISSUE TITLE
When debuging a sample .bal file, on the tab it is shown as dirty file

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#1934]
Issue: 

When open a sample .bal file in composer and debug it using composer, on the tab it is shown as file is dirty. 

Steps:

1. Open HelloWorld.bal sample from welcome page of the composer.
2. Go to the debug from the left navigation.
3. click application

Image:

![debug issue](https://user-images.githubusercontent.com/9109762/27023013-55a4fee2-4f6e-11e7-9113-2fa28657bfdb.png)

**Comment by hevayo** [comment]
Closed as per pahan's comment
