### ISSUE TITLE
Cannot add returns with no identifier with enter

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1938]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/1029806/27023538-95e21b6e-4f70-11e7-803c-11dc937d9158.png">

When adding return types with no identifiers, enter key press does not work. Validations only work for returns with identifiers. However, returns with no identifiers can still be added with focus out.

**Comment by nadeeshaan** [comment]
Closing the issue since the fix is merged
