### ISSUE TITLE
Reply arrow should be a dashed line 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#194]
<a href="https://github.com/srsharon"><img src="https://avatars.githubusercontent.com/u/10986966?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Friday Jan 27, 2017 at 09:12 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1106_

----

![image](https://cloud.githubusercontent.com/assets/10986966/22365666/c82c23fe-e49e-11e6-9ca5-9785c7b183be.png)

**Comment by nadeeshaan** [comment]
Closing the issue, after the design decision was to use the solid line
