### ISSUE TITLE
The struct definition window in 0.88 is not intelligent 

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#1942]
The struct definition window is not intelligent, the default value text box generates code that does not conform to the data type selected and this leads to other issues down the line, 

For example if a struct is initiated at declaration time using code view, the composer fails to switch back to compose view.

function functionOne () {
    
    newStruct1 s = {name:"hello"};
}

struct newStruct1 {
    string name = kdsjksdjf;
}

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2149
