### ISSUE TITLE
Transform Statement - UX improvements

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1944]
- [x] back button should be more intuitive
- [x] center align expand button
- [ ] hover opacity should increase on action buttons of the statement
- [x] hide selected variables from drop down
- [x] title of the variables/structs should be highlighted to be clearly visible
- [x] add source and target titles
- [ ] improve overlaps on verticle lines of arrows
- [x] source and target drop downs should be fixed (should not be a part of scrolling div)
- [x] add colors as required to emphasize
- [x] make the arrow thin/add colours
- [x] evaluate curved arrows or similar different approaches
- [x] transform view is cut off when file explorer is open

**Comment by maheeka** [comment]
<img width="137" alt="image" src="https://user-images.githubusercontent.com/1029806/27069994-bbdd3d2a-5034-11e7-9284-1673d7cde90c.png">

**Comment by keizer619** [comment]
As these improvements have been done i am closing this issue
