### ISSUE TITLE
Syntax errors are not propagated to the design view

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#1956]
Syntax errors that are returned after calling the validate endpoint are not propagated to the **design view**. Since these calls are occurring in the background it would be better if they can be displayed for the design view users similar to the way they are displayed for the **code view** users.

Few examples of errors that are not displayed in design view,

'{"errors":[{"row":3,"column":7,"text":"<unknown>:3:7: missing Identifier before ';'","type":"error"}]}'

'{"errors":[{"row":1,"column":11,"text":"<unknown>:1:11: unwanted token '.'","type":"error"},{"row":1,"column":17,"text":"<unknown>:1:17: unwanted token 'import'","type":"error"},{"row":1,"column":33,"text":"<unknown>:1:33: unwanted token '.'","type":"error"},{"row":1,"column":37,"text":"<unknown>:1:37: mismatched input '.'. Expecting one of ';'","type":"error"},{"row":1,"column":42,"text":"<unknown>:1:42: mismatched input ';'. Expecting one of {'[', Identifier}","type":"error"},{"row":3,"column":0,"text":"<unknown>:3:0: unwanted token '@'","type":"error"},{"row":3,"column":5,"text":"<unknown>:3:5: mismatched input ':'. Expecting one of ';'","type":"error"},{"row":3,"column":15,"text":"<unknown>:3:15: unwanted token '{'","type":"error"},{"row":3,"column":21,"text":"<unknown>:3:21: mismatched input ':'. Expecting one of ';'","type":"error"}]}'

**Comment by NipunaMarcus** [comment]
Showing syntax error on design view has been implemented and working in current master hence closing this issue.
