### ISSUE TITLE
The save as and save drop down options are disabled for a file just created.

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1959]
_Build: ballerinalang/tools-distribution/org.ballerinalang.tools:ballerina-tools: 378_

**Steps**
1. Create a new file 
2. Go to drop down "File" 

**Acutal Behaviour**: As shown in the attached image both the Save and Save As options are disabled. But when the keyboard shortcut is used, the save dialog box opens

![composer_1](https://user-images.githubusercontent.com/15624590/27115851-249bbb46-50eb-11e7-97bc-134d1c2e5fbd.png)

**Expected behaviour**: Both the save and the save as options should be enabled when the file is just created. It should only be disabled when there is no change to save in an already saved file

**Comment by dakshika** [comment]
Similar issue https://github.com/ballerinalang/composer/issues/2045

**Comment by dilinisg** [comment]
**Issue 2**
Star mark(*) which indicates the file needs to be saved should appear on the tab of the newly created file
