### ISSUE TITLE
[Critical] Sort the directory structure in save or open file options

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1960]
_Build: ballerinalang/tools-distribution/org.ballerinalang.tools:ballerina-tools: 378_

As shown in the attached image currently the directory structure is not sorted. It has to be sorted so that it will enhance the user experience as well as to provide better illustration 

![composer_2](https://user-images.githubusercontent.com/15624590/27115989-eb9ae186-50eb-11e7-9c77-b550dc257574.png)

**Comment by maheeka** [comment]
Duplicated in https://github.com/ballerinalang/composer/issues/731
