### ISSUE TITLE
Provide argument type in library functions

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1963]
_Build: ballerinalang/tools-distribution/org.ballerinalang.tools:ballerina-tools: 378_

**Actual behaviour:** As shown in the attached image, the library functions does not show the argument type. Since method overloading is not supported, it is very crucial to mention the type of the argument, else the user will have to cross reference with some other material to know what is the required argument type for that particualr function. 

![composer_5](https://user-images.githubusercontent.com/15624590/27116461-011e8046-50ef-11e7-86f2-f2169b80463f.png)

**Comment by nadeeshaan** [comment]
This is the same function invocation statement represented in the ballerina source view as well. This is being addressed with the language server and prompt on hover and when editing (Same as done in the text editors' content suggestion). Hence closing the issue
