### ISSUE TITLE
Tool Palette "More" button placement fix

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1975]
![image](https://user-images.githubusercontent.com/7569427/27166261-2101169e-51b7-11e7-94de-ecc2b512c57b.png)

Tool Palette "More" buttons should place inside the relevant group container.

**Comment by hevayo** [comment]
Will it be possible to provide more details. The ( + More ) should signify more libraries or more connectors. Will it work if we place this next to the title.

**Comment by keizer619** [comment]
@jeradrutnam 
With recent UX fixes this has been renamed and improved as following screenshit.
Hence i am closing this issue, if you see any fur
<img width="305" alt="screen shot 2017-07-24 at 2 55 49 pm" src="https://user-images.githubusercontent.com/2918812/28516664-9dd51b5c-707f-11e7-84b6-b2c1d848fe7a.png">
ther improvement can be done please feel free to reopen
