### ISSUE TITLE
[JMS] Cannot add multiple Connection Properties from the composer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1992]
If we click on key and value from the drop down list 
![prop2](https://user-images.githubusercontent.com/1845370/27179506-9102b404-51ec-11e7-9d67-e66b671a69d0.png)

**Issues**
1. Cannot add multiple Connection Properties from the composer
2. Usability issue when it is prompted to type something (as the identifier) and also give a drop down list to select. Cannot figure out which method to use

**Comment by hemikak** [comment]
Cannot add multiple Connection Properties from the composer - Fixed
