### ISSUE TITLE
[JMS] Give suggestions of the available connection properties

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1993]
![prop2](https://user-images.githubusercontent.com/1845370/27179990-cb99865e-51ee-11e7-871c-c590e75fd2a0.png)

In the JMSSource annotation, suggestions are given for example; providerUrl, factoryInitial which is easy and users know what to add.

But, in the ConnectioProperty annotation, the suggestions available are key and value which is incorrect and inconsistent with the above behaviour.

**Comment by hemikak** [comment]
This needs to be fixed from the ballerina core - https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-native/src/main/ballerina/ballerina/net/jms/annotations.bal

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/ballerina/pull/2775/
