### ISSUE TITLE
Search tool palette related improvements

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1998]
1. Searching through connector names, does not filter the connector. -> packages must be added to the search indexing
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1029806/27212640-0634d2f6-527f-11e7-8537-c596cfb67c80.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1029806/27212695-6c72a62e-527f-11e7-81e4-c9e0be0f34d5.png">

2. clear the search text box when clicking on + libraries/connectors or have the filtered content when clicked on +

<img width="286" alt="image" src="https://user-images.githubusercontent.com/1029806/27212656-253eed8a-527f-11e7-83a2-4757c167e15e.png">

3. Allow the option of adding imports from the tool palette it self. When searching for a function, it will be useful to have them added from the tool palette directly, than having to do it manually or with function drag drop.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/1029806/27212671-43befbba-527f-11e7-9b8a-0175f6b959d7.png">

**Comment by hevayo** [comment]
implementation has differed tool palette was removed from 0.95.6
