### ISSUE TITLE
drag and drop searched function from tool palette clears the palette

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#1999]
1. click on + and search for "println"
<img width="635" alt="image" src="https://user-images.githubusercontent.com/1029806/27212720-922cf874-527f-11e7-8646-c86bae285a68.png">

2. now drag and drop println function to main function. The tool palette is cleared of all content.
<img width="697" alt="image" src="https://user-images.githubusercontent.com/1029806/27212743-c3f05c7a-527f-11e7-999c-52f935da3508.png">

**Comment by hevayo** [comment]
What happen is when you drag and drop a function from this particular package it will add the package to imports. Packages which are imported will be not listed in library thus it will be removed automatically. 

Need to find a proper solution for this though.

**Comment by maheeka** [comment]
Can we always show all packages in explore? The once that are imported maybe in a grayed out colour?

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master. Hence closing
