### ISSUE TITLE
[Regression Issue] Composer freezes when editing swagger definition

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#2016]
The composer freezes when a swagger definition is edited using the swagger editor in ballerina .89 build no 412[1]. to reproduce, open a sample ballerina service, go to swagger view, cut the swagger definition and wait a second or two for the editor to process the change, copy back the definition and try to switch back without modifying the definition.

**Note that this issue is not observed in .88 release distribution.**

[1] - https://wso2.org/jenkins/job/ballerinalang/job/tools-distribution/org.ballerinalang.tools$ballerina-tools/412/

**Comment by handakumbura** [comment]
Resolved in build # 430. shall we close this ticket?

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2442, https://github.com/ballerinalang/composer/pull/2575
