### ISSUE TITLE
Dialog titles must be capitalised and content must be truncated

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2046]
Create new directory, folder and delete file dialogs have titles in simple case.

e.g. : 
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1029806/27432089-687675ae-576c-11e7-8a88-00b7e9f4c19e.png">

When content is too long, it goes beyond the dialog.

**Comment by dakshika** [comment]
This is fixed on latest master
