### ISSUE TITLE
Empty canvas opened for errorneous bal files with no parser errors

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2048]
Consider the following example : 

```
package wso2.hospital.sample;

import ballerina.net.http;

@http:BasePath { value: "/sample"}
service Service1 {

   @http:GET {}
   @http:Path { value:  }
   resource Resource1 (message m) {
   }
}
```

Save this to a .bal and open from composer. The diagram page is shown with an empty canvas. 
`@http:Path { value:  }` is an errorneous statment which does not show as a parser error in composer. Hence it is considered as a valid source and tries to render the graphical view which fails. 

However, if we try to navigate to design view from source view, same happens.

But, if you copy the above same source and try to navigate to design view, this fails with a parser error :null

**Comment by manuranga** [comment]
Fixed with #2101
