### ISSUE TITLE
No const validation in service level variables

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2051]
When adding a const in service level variables a variable will be added ignoring const keyword.

Validation must be provided to indicate that constants are not allowed in service level, without removing them without a warning.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/1029806/27432959-1e646030-5770-11e7-9f89-90364f287d23.png">
hit enter
<img width="355" alt="image" src="https://user-images.githubusercontent.com/1029806/27432963-232efa3a-5770-11e7-9dc8-295dd2980ff3.png">

**Comment by NatashaWso2** [comment]
When a variable with "const" keyword is provided, it is not added to the variables list but is ignored without a warning.
