### ISSUE TITLE
Global variable constant statement type validation

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2052]
- [x] `const int Y = "";`

The above code if typed in source view and try to switch, 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/1029806/27433138-f768436a-5770-11e7-873e-8d88b830971e.png">

- [x] `const int Y = "test";`
if typed and switched to source view, it is changed to : 
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1029806/27433152-0c64ba00-5771-11e7-93a9-e71725af11b4.png">

- [ ] if we try to type the same in design view, there is no validation with type.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1029806/27433177-2bf29efa-5771-11e7-8847-d8e91548c322.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1029806/27433188-329ebec8-5771-11e7-9379-fba9810ddbdb.png">

renders correctly in source view as well
<img width="256" alt="image" src="https://user-images.githubusercontent.com/1029806/27433203-47d69f04-5771-11e7-9d42-0355107fa319.png">

- [ ] some variable types are not supported. Please check following is working (json)
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1029806/27473886-54c42ad0-581e-11e7-9735-815a9d04a377.png">

**Comment by NipunaMarcus** [comment]
This is fixed in the current master and design view error view will validate syntax and inform the user hence closing this issue.
