### ISSUE TITLE
Welcome page is not responsive

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2058]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1029806/27433747-99b0ad04-5773-11e7-99c3-194725130eae.png">

**Comment by hevayo** [comment]
![screenshot from 2017-06-22 17-56-32](https://user-images.githubusercontent.com/323846/27433992-9680076e-5774-11e7-9a3a-e492de0ecea8.png)

**Comment by hevayo** [comment]
Fixed with #2135
