### ISSUE TITLE
Cannot find arguments to be passed for HTTP:get() from composer itself 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#2059]
User cannot figure out what type of parameters or how many parameters can be or should be passed in to a function, in this case it is client connector action get().

**Comment by maheeka** [comment]
Connector declarations have the same issue of not being able to figure out the parameters. 

﻿
<img width="579" alt="image" src="https://user-images.githubusercontent.com/1029806/27434025-ba122e5a-5774-11e7-8b34-6d052e4a560b.png">


﻿

**Comment by maheeka** [comment]
Same applies for function invocations as well. Instead of adding parameters to the statement, let's provide a documentation.

**Comment by maheeka** [comment]
Also related : https://github.com/ballerinalang/composer/issues/959

**Comment by NipunaMarcus** [comment]
Documentation for a particular package or function or connector is now showing in a tab with the PR #2140 hence closing this issue.
