### ISSUE TITLE
Run button tool tip is added for click and hover both

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2066]
Click on Run button
<img width="270" alt="image" src="https://user-images.githubusercontent.com/1029806/27436709-b9738d5a-577d-11e7-9411-d4e5484e25f7.png">

The tool tip doesn't dissapear when cursor is moved. Should click elsewhere for the tool tip to disappear.

**Comment by nadeeshaan** [comment]
Fixed. Hence closing
