### ISSUE TITLE
UX Improvements to Global/Import components

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2067]
(1) Placement should not change when expanding either of above components
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1029806/27436835-134e9612-577e-11e7-8ac1-83c04e413ea1.png">
vs
<img width="505" alt="image" src="https://user-images.githubusercontent.com/1029806/27436845-18e312f6-577e-11e7-9195-9e83638e702b.png">
vs
<img width="352" alt="image" src="https://user-images.githubusercontent.com/1029806/27436851-1d91c662-577e-11e7-92a4-4d1481a9e57b.png">

(2) To expand can click anywhere on the component, but collapsing works only by clicking on the eye icon

(3) Import placeholder is not clear. 'Add Import' text does not give that much of an idea (open to discuss)

(4) Showing a number with the count of imports or variables does not add value. Users only need to know whether there are imports or not, not the count.

**Comment by dakshika** [comment]
+1 for this

**Comment by hevayo** [comment]
We removed the global and import from design view.
