### ISSUE TITLE
When a service is running, show an indication

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2068]
If user closes console by mistake, there is no way to bring it back and to shut down the service as well (run view is not available too)

**Comment by dakshika** [comment]
IMHO we need to add panel show/hide option on the menu.

![Window menu](https://media.gcflearnfree.org/ctassets/topics/247/start_panel_on.png "Window menu")

**Comment by NipunaMarcus** [comment]
This has been fixed by adding a view menu which allow user to open console if it is closed hence closing this issue.
