### ISSUE TITLE
Adding Else If without Else is not possible

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2069]
- [ ] If user needs to add a else if without an else block, there is no straightforward way to add it. Add Else, and then Else If and delete Else. An option must be available to select between Else If and Else

- [ ] Also natural flow of programming is to add Else Ifs and finally add Else. Above flow disrupts this.

- [ ] If Else block is deleted it cannot be added back.

- [ ] Always the [+] icon appears in the end of If block. Should we make it available on the top as well (for ease) ?

**Comment by NatashaWso2** [comment]
Fixed in the latest master c3dbf84fb021c68495071330b7cd26fb753fc690, so closing this issue
