### ISSUE TITLE
Add left operand of the function invocation and action invocations when drag and drop.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#2071]
When drag and drop package level function invocations left operand is set empty.

![empty left operand](https://user-images.githubusercontent.com/9109762/27437687-a91dfcda-5780-11e7-8cac-52a7f9c61d5d.png)

This can confused the user as there is not clue what type of variable need to be added to capture the return value from the function.

**Comment by maheeka** [comment]
Should also address action invocations. Duplicated in https://github.com/ballerinalang/composer/issues/2060

message m = ... should appear. it is not clear that a 'message m' should be created.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1029806/27434232-a487e380-5775-11e7-89c1-f55f364b6079.png">

Instead we should give as
message m = http:ClientConnector.get()

**Comment by NipunaMarcus** [comment]
Fix the issue with the https://github.com/ballerinalang/composer/pull/2103. Hence closing.
