### ISSUE TITLE
Save dialog placeholder does not disappear on focus

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2072]
When typing file location in save dialog, "e.g. : ... " placeholder should disappear.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1029806/27437319-80a7f1bc-577f-11e7-8ee0-abfe6d5d4d8c.png">

**Comment by NipunaMarcus** [comment]
Placeholders are normally disappear when start typing .. @srsharon is having a placeholder such as this ideal?

**Comment by NipunaMarcus** [comment]
This is normally the way of showing example of what to input using placeholder. Hence closing the issue.
