### ISSUE TITLE
[Feature] Add API documentation to composer

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2074]
Add a new component on the right menu pane to render the API documentation from [1].

We can render the navigation from [1] in right pane and the canvas pane can render the package details as in [2]

[1] http://ballerinalang.org/docs/api/0.8/
[2] http://ballerinalang.org/docs/api/0.8/ballerina.lang.system.html

**Comment by NipunaMarcus** [comment]
This feature has been implemented hence closing the issue.
