### ISSUE TITLE
Improvements to tool palette constructs view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2079]
(1) Add a padding to the label view
<img width="179" alt="image" src="https://user-images.githubusercontent.com/1029806/27439333-57ac667a-5785-11e7-909b-2b84eeef8063.png">
vs
<img width="184" alt="image" src="https://user-images.githubusercontent.com/1029806/27439372-72987c8a-5785-11e7-9b88-55d567946780.png">
with left-padding : 3px, it looks better.

(2) Align text labels
<img width="111" alt="image" src="https://user-images.githubusercontent.com/1029806/27439499-b3ec9c5c-5785-11e7-9f81-8d8a68816f10.png">

**Comment by hevayo** [comment]
Fixed with #2135
