### ISSUE TITLE
Snippet completion in source editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#208]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Jan 30, 2017 at 05:47 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1146_

----

implement snippet auto-completion in source editor

**Comment by maheeka** [comment]
Language server implementation will address this issue.

**Comment by nadeeshaan** [comment]
Since this feature has been included in the latest master, closing the issue
