### ISSUE TITLE
Dialogs have close (x) and button option both

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2080]
Should we have both options or remove one? Both perform the same action, hence one can be removed. IMO, close is not needed.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/1029806/27439798-6faafefc-5786-11e7-9443-ed7b62b01f8e.png">

**Comment by erangatl** [comment]
IMHO we need to keep the close (x) for consistency and standards (Usability heuristics). Users will always look for a close on top right corner. We should not confuse them.

We should have a secondary action as well and it's text will depend on the action.

For this scenario, close button text should be 'Cancel'

**Comment by NipunaMarcus** [comment]
This has been fixed hence closing the issue.
