### ISSUE TITLE
Package component has no placeholder

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2082]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/1029806/27440246-bf1af9fa-5787-11e7-9846-f8c9dfd8d5cc.png">
Add a placeholder explaining what to type here.

**Comment by maheeka** [comment]
Also, the enter should add the package. Currently this is only working for focus out

**Comment by manuranga** [comment]
@maheeka fixed the name to ballerinalang.
