### ISSUE TITLE
Improvements to source view Find

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2085]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/1029806/27440738-49d2739c-5789-11e7-9f73-9c480d2c40a7.png">

(1) The highlight is not clearly visible
(2) The find dialog does not match with the rest of composer UI theme

**Comment by dakshika** [comment]
IMO we need to move this as a menu option. Otherwise, there is no way to identify such a feature.
