### ISSUE TITLE
Canvas background is not visible for large horizontal content

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2086]
Canvas (square background) is not available throughout.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1029806/27440848-88700fa6-5789-11e7-9dec-8a5f2da14687.png">

**Comment by dilinisg** [comment]
Similar to the above issue. Observed in the 19/07 pack
![canvas](https://user-images.githubusercontent.com/1845370/28371141-c550dd7a-6cb9-11e7-9c92-b69c1994916a.png)

**Comment by hevayo** [comment]
Issue mention by @dilinisg is fixed.

**Comment by NipunaMarcus** [comment]
Both issues have been fixed in composer. First issue has been closed by adding a property modal to connectors and second issue is fixed by setting the height of the canvas dynamically hence closing this issue.
