### ISSUE TITLE
Revisit connector declaration statement representation

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2089]
Follow https://groups.google.com/forum/#!topic/ballerina-dev/CpxUP3nIv18 to figure out and implement a better visual representation

Problems are that the current representation does not show where the declaration was done. The errors only uncovered when running the service/application. 

E.g. : action invocation if appears before the connector is declared (consider the situation where action invocation was added inside an if-else block)

**Comment by nadeeshaan** [comment]
Fixed with #2407 and hence closing the issue
