### ISSUE TITLE
If construct, condition box is not intuitive

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2091]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/1029806/27470686-c59f3e68-5812-11e7-8ea0-ed145d717948.png">

If true does not give an idea that the 'true' part should be edited to include the condition. Think of a better solution

**Comment by dakshika** [comment]
similar one https://github.com/ballerinalang/composer/issues/169

**Comment by maheeka** [comment]
Revisit this design.
Also, clicking on condition removes the 'if'

<img width="166" alt="image" src="https://user-images.githubusercontent.com/1029806/32714199-a634c85c-c844-11e7-97f8-e492cf354ad9.png">

**Comment by hevayo** [comment]
Issue is no longer relevant with new design shipped with 0.95.6
