### ISSUE TITLE
Whitespace related issues

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2095]
- [x] Whitespace not preserved for while statement

- [x] Error in If-Else default whitespaces. This is when added from design. If reformat it formats correctly. 

<img width="204" alt="image" src="https://user-images.githubusercontent.com/1029806/27473694-a1b8fd76-581d-11e7-9c53-3d2eb5eb4625.png">

- [x] Default assignment statement spacing is incorrect
<img width="135" alt="image" src="https://user-images.githubusercontent.com/1029806/27473725-be9a0462-581d-11e7-995c-5d61812f403d.png">
should be 'a = b' not 'a  = b'

**Comment by kaviththiranga** [comment]
Mentioned three issues are already fixed with 32f63ed319a8bcc7ef30a96a33b48fb2de759692, 25a5c7f89f6082125f2dcf238f53c3c4876821b7 and 0064709f0fb483d66dc790f78b936a303d929607 .
