### ISSUE TITLE
It is hard to add a pathParam annotation directly on to a resource.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#2102]
Issue: 

When trying to add a path param annotation to a resource first it only shows POST and Path [1] as the select-able options. And even after selecting a Path we cannot see the option to add the  PathParam unless we click on the already added Path annotation and then it will list down option to add PathParam but selecting PathParam will replace the already added Path.

Scenarios: 

[1] only shows POST and Path

![pathparam issue](https://user-images.githubusercontent.com/9109762/27475676-b92339ee-5823-11e7-99b9-b584d6eeb203.png)

[2] after selecting a Path we cannot see the option to add the  PathParam 

![pathparam2](https://user-images.githubusercontent.com/9109762/27475725-d8f22a78-5823-11e7-880f-59f6daa8f508.png)

[3] click on the already added Path annotation and then it will list down option to add PathParam but selecting PathParam will replace the already added Path.

![pathparam3](https://user-images.githubusercontent.com/9109762/27475757-01a21a64-5824-11e7-9a06-9b420fffa020.png)

![pathparam4](https://user-images.githubusercontent.com/9109762/27475778-1161c3fa-5824-11e7-8953-4f98780d6c49.png)

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2336
