### ISSUE TITLE
Cannot type keywords in package name

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2113]
Shouldn't validate keywords when appear with in combination with other names for the package.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1029806/27484410-bf129ac0-5846-11e7-8984-185169e7db56.png">

**Comment by maheeka** [comment]
Related https://github.com/ballerinalang/composer/issues/2113

Should allow keywords by parser, but must not be provided as suggestions.

**Comment by hevayo** [comment]
You cannot have keywords in a package name similar to java see [1]

[1] https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
