### ISSUE TITLE
Make the tool palette search global

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2115]
When a user performs a search for a function, we can perform a global search rather than asking them to click on more and then do the search. This is too much work for a straightforward task. 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1029806/27486576-ac3c209e-584e-11e7-8d27-be04be4be931.png">

**Comment by hevayo** [comment]
implementation has differed tool palette was removed from 0.95.6
