### ISSUE TITLE
Committed Statement is broken.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#2154]
Issue: Committed block of transaction aborted statement is not working properly. 

![committed error](https://user-images.githubusercontent.com/9109762/27635940-ce943aba-5c26-11e7-821b-3fb931f5fa97.png)

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2167

**Comment by NipunaMarcus** [comment]
Fixed in the current branch hence closing this issue.
