### ISSUE TITLE
[tool] Missing DTD in index page

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#221]
<a href="https://github.com/dakshika"><img src="https://avatars.githubusercontent.com/u/6497326?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dakshika](https://github.com/dakshika)**
_Tuesday Jan 31, 2017 at 10:01 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1190_

----

DTD missing in app main page. need to fix and validate with correct markup

**Comment by hevayo** [comment]
This was fixed in 0.87
