### ISSUE TITLE
[Blocker] Debugging services is not working

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2225]
Release - 0.89

The frames are not displayed
![debug2](https://user-images.githubusercontent.com/1845370/27735822-126b028e-5dbf-11e7-8b8b-b385e8d7e924.png)

**Comment by hevayo** [comment]
Should be because of the first frame gets dropped.

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2226
