### ISSUE TITLE
"Address already in use" when debugging a service and need to restart the composer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2229]
OS - Ubuntu 15
Intermittent
1. Debug a service 
2. Stop the service
3. Debug again

**Issue**
"Address already in use" error is prompted and need to restart the composer to work again

**Comment by dilinisg** [comment]
Observed this again in the 21/07 pack

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2639
