### ISSUE TITLE
Removing parent function invocation does not remove nested function invocations in view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2230]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1029806/27737133-a856eeac-5dc4-11e7-99a8-4cc72d95ad71.png">

Removing toLowerFunction should remove the whole statement, since it is the top expression of the assignment statement. But it is only removed from source view.

```
    transform {
        e.last_name = strings:toLowerCase(strings:toUpperCase(p.name));
    }
```

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/1029806/27737191-e0bb2ab0-5dc4-11e7-885f-9d317b3b2ded.png">

**Comment by roonyh** [comment]
Now the source view reflects the resulting design view state.

```
    transform {
        var temp = strings:toUpperCase(p.name);
    }
```
This is a better solution because now `toUpperCase` return params can be connected to another target.
