### ISSUE TITLE
Cannot add a else if statement clicking on the plus button 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2234]
When you hover over the if-condition, the plus button appears. But soon you try to click on it, it disappears
![ifcond](https://user-images.githubusercontent.com/1845370/27738245-714ada00-5dc8-11e7-8f6c-6da9d0bea656.png)

**Comment by NipunaMarcus** [comment]
tried on Firefox v53.0 and Chrome. Couldn't reproduce. Might be a intermittent issue. We'll try testing again and again.

**Comment by nadeeshaan** [comment]
Tested in the latest master branch, could not reproduce the issue. Please reopen if the issue exists further
