### ISSUE TITLE
Unwanted characters added when typing in Firefox- source and design view

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#2235]
<img width="760" alt="screen shot 2017-06-30 at 3 33 37 pm" src="https://user-images.githubusercontent.com/3665108/27753323-ce8be4b6-5daa-11e7-8c80-0b7dfae7fb60.png">

**Comment by dakshika** [comment]
@lahirus  what is the browser version that you are using?

**Comment by lahirus** [comment]
Firefox.

**Comment by nadeeshaan** [comment]
Closing the issue since the related issue #2262 is fixed.
