### ISSUE TITLE
Continue keyword is missing

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2246]
Need to support continue keyword.

**Comment by maheeka** [comment]
Please follow up on : https://github.com/ballerinalang/ballerina/issues/2858

**Comment by dilinisg** [comment]
No icon for continue keyword
It can be added anywhere in a lifeline

**Comment by manuranga** [comment]
Icon issue is reported here https://github.com/wso2-dev-ux/font-wso2/issues/76

**Comment by dilinisg** [comment]
Will report a separate issue for the lifeline issue

**Comment by hevayo** [comment]
Icon is added.
