### ISSUE TITLE
File not found gets printed when accessing the native API docs from the composer

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#2248]
Following file not found error gets printed every time native API docs are accessed from the composer. Looks ugly.

`2017-07-03 10:32:00,980 ERROR -  File not found [/home/dumiduh/WORK/BALLERINA/QAMonth/nightly/0207/ballerina-tools-0.89-SNAPSHOT/docs/api/docerina-theme/fonts/fontawesome-webfont.woff2?v=4.6.3], Requesting path [/home/dumiduh/WORK/BALLERINA/QAMonth/nightly/0207/ballerina-tools-0.89-SNAPSHOT/docs/api/docerina-theme/fonts/fontawesome-webfont.woff2?v=4.6.3] `

observed in ballerina tools build #473 MD5: bc7474a684978ecf59224a6bf12f64e3

**Comment by NatashaWso2** [comment]
This issue is fixed with ballerina tools 0.9 distribution

**Comment by hemikak** [comment]
Fixed as per comment.
