### ISSUE TITLE
load packages asynchronously on initial page loading

### ISSUE THREAD

**Issue by pahans** [ballerinalang/composer#2256]
![selection_041](https://user-images.githubusercontent.com/1552869/27791862-b453c19c-6014-11e7-9227-1b104a23565c.png)

package loading takes about ~3000ms on initial page rendering. During this time UI freezes. Lets load packages asynchronously and display a loading indicator. Doing this might fix the edge browser compatibility as well.

**Comment by NatashaWso2** [comment]
This issue is fixed in the latest master as follows : all the packages are asynchronously loaded and a loading indicator is shown till this happens. 
Since this issue is resolved, this can be closed
