### ISSUE TITLE
Path params and query params auto complete inside the resource params block

### ISSUE THREAD

**Issue by nuwanbando** [ballerinalang/composer#2257]
https://www.dropbox.com/s/nx8d6pqmbevskqn/Screenshot%202017-07-03%2013.56.53.png?dl=0

the http: params has to be auto completed

**Comment by NatashaWso2** [comment]
This issue is fixed in the ballerina tools 0.9 distribution.

**Comment by hemikak** [comment]
Content assist is provided while writing  annotations for params.
