### ISSUE TITLE
We should build a catalogue of pre-built scenarios as one of the pains in the composer

### ISSUE THREAD

**Issue by nuwanbando** [ballerinalang/composer#2258]
Basically this means we will have pre-built scenarios

1. String to json conversion
2. Do a get / post to a known EP
3. A transform scenario
4. DB select / insert
5. A sample case for each connector (SF/GMAIL etc)

I know that ballerina by samples is this. But What I mean is bake that into the composer itself. 

we can also expand this to have all EIPs.

**Comment by NatashaWso2** [comment]
Now we have samples in the 'Welcome page' of the composer which covers all the pre-built scenarios mentioned , hence closing this issue
