### ISSUE TITLE
The quality of the exported diagrams are low

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#2261]
The export diagram function of the .89 composer produces SVG files which are below acceptable quality. Please take a look,

![diagramexport](https://user-images.githubusercontent.com/6889802/27815157-ab4cd332-609f-11e7-94e2-961572506443.jpg)

**Comment by NipunaMarcus** [comment]
For now exporting SVG can be viewed correctly on a web browser. This is due to all the style classes are applied in a SVG style tag which is not supported many image viewers. We are currently working on enhancing Diagram export functionality to be rendered even in image viewers.

**Comment by handakumbura** [comment]
Ack. yeah, most users would expect the exported diagram to behave like an image.

**Comment by NipunaMarcus** [comment]
This issue has been fixed as user can export diagram as a png hence closing the issue.
