### ISSUE TITLE
Errors when working with lengthy source codes

### ISSUE THREAD

**Issue by omindu** [ballerinalang/composer#2275]
Noticed the following while working with lengthy source codes. (v0.89)

- Cannot run the service for that particular ballerina source from the composer, but the same service can be run from the command line.
- The following error gets printed in the browser console.
```
Uncaught TypeError: Cannot read property 'getTop' of undefined
    at ConnectorDeclarationPositionCalcVisitor.value (connector-declaration-position-calc.js:66)
    at PositionCalculatorVisitor.value (position-calculator-visitor.js:46)
    at ConnectorDeclaration.value (node.js:221)
    at node.js:229
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9358)
    at IfStatement.value (node.js:223)
    at node.js:229
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9358)
```
- A lot of white spaces in the design view. See [\[1\]].

You can test this with the following source - https://github.com/omindu/ballerina-pep/blob/master/xacml-pep.bal

[\[1\]]: <https://camo.githubusercontent.com/fd8a53aa67e2b07508afb6d5cde5c8f5d7c88676/68747470733a2f2f7261776769742e636f6d2f6f6d696e64752f62616c6c6572696e612d7065702f6d61737465722f7265736f75726365732f696d616765732f7861636d6c2d7065702e737667>

**Comment by NipunaMarcus** [comment]
This issue occur when we wrote the whole code in source view (without switching to design view) or copy paste the code and try to render the diagram. if we implement this using design view (and source view) issue is not there. Tool palette also not working in this scenario. issue is body component for the Ballerina AST root is not available.

**Comment by NipunaMarcus** [comment]
@omindu  - can you try copy & pasting this code and see whether issue is still coming? 
[myerrorBal.txt](https://github.com/ballerinalang/composer/files/1123678/myerrorBal.txt)

**Comment by omindu** [comment]
@NipunaMarcus I don't see the errors when opening the attach file.

**Comment by NatashaWso2** [comment]
The issue cannot be reproduced using ballerina tools 0.9 distribution

**Comment by nadeeshaan** [comment]
Closing the issue based on the previous comment. Please reopen if the issue exist further
