### ISSUE TITLE
struct type fields are restricted - imports and cannot edit

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2283]
only field name is editable.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1029806/27899480-0026e3bc-6248-11e7-809f-44fd707f08c9.png">

cannot add struct fields imported from other packages as struct fields
struct field types does not show type even when added from source view
```
struct Employee {
    string name;
    int age;
    complexstructdefs:Address address;
}
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1029806/27899623-9b2e3b58-6248-11e7-97dd-7df7df6f11e1.png">

**Comment by NipunaMarcus** [comment]
Issue is fixed hence closing.
