### ISSUE TITLE
Order of the connectors change when undo deleting a connector

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#229]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Feb 01, 2017 at 11:30 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1229_

----

1. Add a service and 3 HTTP connectors.
2. Name the 3 endpoints as endpoint 1, 2 and 3 respectively.
3. Connect all the 3 endpoints to HTTP methods
4. Delete the 2nd endpoint. The connection will automatically set to a different endpoint (3rd)
5. Undo deleting the endpoint. The order of the endpoints will change

![4](https://cloud.githubusercontent.com/assets/1845370/22505115/c8af83b6-e89f-11e6-95fc-2df47200a21d.png)

![5](https://cloud.githubusercontent.com/assets/1845370/22505118/ce615096-e89f-11e6-8c26-8a4330f12dea.png)

**Comment by nadeeshaan** [comment]
This issue of deleting has been fixed in the latest branch and a related issue has been fixed with #1266. 
We are opening a new Issue for undo issue #1267
