### ISSUE TITLE
Error when adding the timeout block in fork-join

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2291]
**Steps**
1. Add a fork-join statement
2. Add the timeout block
3. Switch to source view

**Issues**
Errors will be displayed. Extra curly brace is added to the front

`}timeout(60)(map m){}`

When switched to the design view again, the tool pallet will be missing

![composer](https://user-images.githubusercontent.com/1845370/27944795-d06b79ac-6306-11e7-8f53-611a335e9c0b.png)

**Comment by dilinisg** [comment]
@nadeeshaan - Can we get this fixed ASAP. It is so annoying to work with fork-join with this error.

**Comment by nadeeshaan** [comment]
Closing the issue, since the fix has been merged
