### ISSUE TITLE
Support JSON mappings

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2292]
based on a JSON schema or the new struct binding to JSON[1].

[1] https://groups.google.com/forum/#!msg/ballerina-dev/EwzHM4IkUoE/X4pZoiBQBQAJ

**Comment by keizer619** [comment]
With following fix [1] we are supporting Struct generation with samples JSONs. Therefore user can generate Structs from sample JSONS and continue mapping and using constraint JSON Struct. Hence i am closing this issue.

[1] https://github.com/ballerinalang/composer/pull/4210
