### ISSUE TITLE
Connector definition added at the bottom leading to errors

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2297]
**Steps**
1. Add a service
2. Add a connector at the bottom of the service definition from the design view
3. Switch to the source view

**Issue**
1. The connector definition added at the bottom of the other codes
2. Undefined symbol 'endpoint1' error when running the service

![undefinedconn](https://user-images.githubusercontent.com/1845370/27945447-b5a9b116-630a-11e7-87f0-cb278cda2316.png)

**Comment by nadeeshaan** [comment]
@dilinisg this is invalid configuration. You need to declare the connector instance before executing the action upon it (line no:19). Also, composer design view now avoids creating such mistakes with the latest master. Hence closing the issue
