### ISSUE TITLE
Identifying a standalone program as a service when redeploy a program

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2314]
**Steps**
1. Open the helloWorld sample
2. Run the application and click on redeploy application as soon as you run the program (before it terminates)

**Issue**
Following error is logged in the console. It identifies the program as a service
```
Program Terminated.
Execution Ended.
Running helloWorld.bal service.
ballerina: deploying service(s) in '/../ballerina-tools-0.90-SNAPSHOT/samples/helloWorld/helloWorld.bal'
ballerina: no service found in '../ballerina-tools-0.90-SNAPSHOT/samples/helloWorld/helloWorld.bal'
Execution Ended.
```

**Comment by dilinisg** [comment]
Note: If there is no requirement to redeploy a standalone program, this feature can be removed for standalone programs

**Comment by NatashaWso2** [comment]
Since there is no requirement to redeploy a standalone program, this feature is  removed for standalone programs in the latest master.
Hence this issue can be closed.
