### ISSUE TITLE
Service name should be displayed instead of "Sample service" in the swagger view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2318]
Following fields can be populated as follows for the swagger view
 **title**: service name
 **version**: version defined in the http:config

![servicename](https://user-images.githubusercontent.com/1845370/28016508-41ffdbc0-6592-11e7-9c26-98a3287075b6.png)

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2406/
