### ISSUE TITLE
remove already used variables in input/output drop downs in transform view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2323]
When a variable is used in a transform statement either as input or output once it cannot be used again. However, now we are showing all the variables in both input and output irrespective of whether they have been used before or not. Selecting such a variable does not show an error as well.

Hence we need to remove once used variables from the drop downs.

**Comment by keizer619** [comment]
This has been fixed in following commit
https://github.com/ballerinalang/composer/commit/ac3ca90be958709c3a2e688a6c9131674d74a536
