### ISSUE TITLE
Debugger variable values cannot be viewed when too long => copy option?

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2331]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/1029806/28070688-6e78c8fe-666b-11e7-80b4-a02b39b20ef0.png">

Shall we provide a copy to clipboard and tool tip to show content on hover?

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2818
