### ISSUE TITLE
Debugger - inner details of structs and arrays

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2332]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1029806/28071327-3abdedbc-666d-11e7-88e6-2e791d6b9e26.png">

Currently only the type is shown and the inner details cannot be viewed (books and book).

**Comment by pahans** [comment]
related to https://github.com/ballerinalang/ballerina/issues/2667

**Comment by pahans** [comment]
closing according to this https://github.com/ballerinalang/ballerina/issues/2667
