### ISSUE TITLE
Implement the XML support in JSON model builder

### ISSUE THREAD

**Issue by hevayo** [ballerinalang/composer#2377]
We need to implement the following methods in BLangJSONModelBuilder. 
visit(XMLAttributesRefExpr xmlAttributesRefExpr)
visit(XMLQNameExpr xmlQNameRefExpr)
visit(NamespaceDeclaration namespaceDclr)
visit(NamespaceDeclarationStmt namespaceDeclarationStmt)

Above methods should also be implemented for BLangExpressionModelBuilder, CompletionItemAccumulator

**Comment by NipunaMarcus** [comment]
Implemented the xml support hence closing the issue.
