### ISSUE TITLE
[Editor] [Improvement] Scroll/navigate option to navigate among files when user opens too many bal files

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#238]
<a href="https://github.com/gvasanka"><img src="https://avatars.githubusercontent.com/u/3368635?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gvasanka](https://github.com/gvasanka)**
_Thursday Feb 02, 2017 at 06:40 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1253_

----

Its better to provide scroll/navigate option to navigate, when user opens lot of files on the editor

![selection_154](https://cloud.githubusercontent.com/assets/3368635/22539409/ed314ae4-e93f-11e6-9f35-457198dcb2d0.png)

![selection_155](https://cloud.githubusercontent.com/assets/3368635/22539513/8600c1fa-e940-11e6-95a4-06ab8a5f8f3f.png)

**Comment by nadeeshaan** [comment]
Duplicated issue with #1120. hence closing
