### ISSUE TITLE
Two config properties in the list view in annotations

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2387]
![2configs](https://user-images.githubusercontent.com/1845370/28256395-b4b6e2ec-6adf-11e7-8243-0dfc20d24cb3.png)

**Comment by hemikak** [comment]
Was not able to reproduce. But added a fix on a place which this could have happened. : https://github.com/ballerinalang/composer/pull/2503

**Comment by hemikak** [comment]
Please reopen if issue exists.
