### ISSUE TITLE
Layout issue when loading a new page in Firefox

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2396]
Firefox version: 54.0.1
Pack - tools (14/7)

Steps: Get a new page (File -> New)

![loading](https://user-images.githubusercontent.com/1845370/28266297-a5bd927c-6b11-11e7-97c1-70991c6eb3c0.png)

**Comment by kaviththiranga** [comment]
Fixed in HEAD 1bccc2e9f37bfee49473f1795f6c23cb35391b69
