### ISSUE TITLE
[ContentAssistance] No suggestions for global variables and variables in the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2398]
Pack - tools (14/7)

If we add a variable assignment from the tool pallet, the data types are suggested.

But no such suggestions for global variables and service level variables

**Comment by dilinisg** [comment]
Also. no suggestions for the parameters passed in the functions

**Comment by NatashaWso2** [comment]
Suggestions are provided for the parameters passed in the functions.

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
