### ISSUE TITLE
[Editor] Compatibility issues with Safari browser - Cannot work on editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#242]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Thursday Feb 02, 2017 at 07:56 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1261_

----

Safari version: 5.1.7
OS : Windows 10

Buttons and menu options are overlapping; not fixed to the browser windows size; 
please check attached.

![safari](https://cloud.githubusercontent.com/assets/15671620/22541147/a424aeee-e94a-11e6-828f-9e266a97ecf8.jpeg)

**Comment by sumuditha-viraj** [comment]
Safari is not a common browser in windows. Since we have prioritised the supporting browsers on certain platforms, I'll close this issue.
