### ISSUE TITLE
Cannot map values using Transform

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2422]
Pack - 18/07

**Issues**
1. The suggestions of the structs are not appeared
2. When the name of the struct is manually entered, an error is displayed which is not meaningful to the user

Therefore, cannot map values using Transform

![-1](https://user-images.githubusercontent.com/1845370/28309869-546f8742-6bc8-11e7-80ec-09686ac180cb.png)

**Comment by maheeka** [comment]
@dilinisg  Can you share the bal config for this error?

**Comment by dilinisg** [comment]
@maheeka  I don't have the code now. But it is easily reproducible. Just add two structs with 1 property each and add a transform to a function. That's all.

**Comment by dilinisg** [comment]
Tried with variables and working. Hence, closing the issue
