### ISSUE TITLE
Transform related UI issues

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2423]
Pack - 18/7

**Issues**
1. The back button of the transform window is not visible to the user much and the user might get confused how to return back to the main design
2. Tool tips are required for all the buttons (Add, Back, Close, Tick icons)
3. The tick icon used when adding values to struct is not consistent with other Add buttons (Tick vs Plus icons)

![back](https://user-images.githubusercontent.com/1845370/28310501-4b9cfecc-6bca-11e7-9d80-815c947e3716.png)
![tooltip](https://user-images.githubusercontent.com/1845370/28310509-5188935a-6bca-11e7-801a-398dbc6bd077.png)

**Comment by dilinisg** [comment]
Overlapping issue
![transformui](https://user-images.githubusercontent.com/1845370/28353816-fd270538-6c7a-11e7-9bc1-11672d4ae48d.png)

**Comment by dilinisg** [comment]
Functions are drown way below the canvas

![lower case](https://user-images.githubusercontent.com/1845370/28357358-c67d93c2-6c88-11e7-8eb6-4e52d8047614.png)

**Comment by dilinisg** [comment]
Release 0.91
Transform expandable button issue:
![transformui2](https://user-images.githubusercontent.com/1845370/28513454-decb61ea-7073-11e7-9aeb-fb7cf13159ed.png)

**Comment by keizer619** [comment]
We have conducted major refactoring for transform for 0.94 release, so most of issues specify here are fixed. Hence i am closing this issue, for new improvements/issues we can open issues for.
