### ISSUE TITLE
Transform related suggestions

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2433]
Pack - 19/7
Suggest the following to improve the usability aspect of transform.

**Need error/confirmation messages for the following scenarios**
1. When trying to add another struct when one is already added
2. When trying to add the same struct to both sides
3. Confirmation message when a user tries to delete one struct when all the mappings are already done

**Other**
1. Cannot identify how to delete a mapping between two variables. Need to improve the design

**Comment by keizer619** [comment]
- This has been improved by removing already added Structs/Variables from the drop down menu. 
- Delete popup will appear on mousehover of the Connection with following fix . https://github.com/ballerinalang/composer/pull/2779/commits/11c35eb93066addfb1e54be4484e5d2e12af7bf8

**Comment by keizer619** [comment]
As editor has editor undo capability no need to include a confirmation box, hence closing this issue
