### ISSUE TITLE
[Transform] If one mapping is deleted all the other mappings below that will be deleted

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2436]
Pack - 19/07
Firefox

**Steps**
1. Open the below code in composer. You will see the mapping correctly
```
import ballerina.lang.strings;
struct Employee {
    string name;
    int age;
    string address;
    int marks;
}

struct Person {
    string first_name;
    string last_name;
    string city;
    int marks;
    int age;
}

function main (string[] args) {
    Person p = {first_name: "John",last_name: "Doe",age: 30,city: "London"};
    Employee e = {};
    
    transform {
        e.name = strings:toLowerCase(p.first_name);
        e.age = p.age;
        e.address = p.city;
        e.address = p.city;
        e.marks = p.marks;
        e.address = p.city;
        e.marks = p.marks;
    }
}
```
2. Delete one field (marks/age) from the Person struct from the design view
3. Verify the transform design again

**Issue**
All the mapping under that field will be removed

**Comment by NipunaMarcus** [comment]
Above mention issue is now not there. But There's a unnecessary error alert giving every time on opening the transform design view after deleting a property. 

![error transform](https://user-images.githubusercontent.com/9109762/28522099-532ec412-7094-11e7-8d38-e41c4278ba2d.png)

also this error is printed on the browser console.
![transform error](https://user-images.githubusercontent.com/9109762/28521961-aa7f468e-7093-11e7-8f02-5443f25ac076.png)

**Comment by keizer619** [comment]
We have done major improvements in the transform, now remaining connections are rendered even we remove a struct field.
![screen shot 2017-10-20 at 2 10 28 pm](https://user-images.githubusercontent.com/2918812/31812008-3b09f7a8-b59f-11e7-9575-889cc790faaa.png)
