### ISSUE TITLE
[Content Assist] related issues/improvements - types and variables

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2441]
(1) primitive types are not provided in global variable level
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1029806/28365881-f48d8514-6ca7-11e7-97d8-f3b7f144b72c.png">
(2) const keyword is not supported
<img width="176" alt="image" src="https://user-images.githubusercontent.com/1029806/28365898-09f639d2-6ca8-11e7-86cd-5321423122f1.png">
(3) incorrect content assist after "const"
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1029806/28365922-203f16dc-6ca8-11e7-8776-4bd78bfd3f96.png">
(4) content assist does not work when constants are available
<img width="280" alt="image" src="https://user-images.githubusercontent.com/1029806/28366000-6f0efaca-6ca8-11e7-9137-4ea0be7c5217.png">
(5) incorrect content assist for server connector
<img width="373" alt="image" src="https://user-images.githubusercontent.com/1029806/28366038-94c67702-6ca8-11e7-8cdb-0bb8438f4f31.png">
(6) no content assist for variables in server level
<img width="338" alt="image" src="https://user-images.githubusercontent.com/1029806/28366108-e35b449c-6ca8-11e7-8868-364ebfb6abf1.png">
(7) incorrect content assist in identifier placeholder
<img width="365" alt="image" src="https://user-images.githubusercontent.com/1029806/28366138-02256a56-6ca9-11e7-8bd9-4bd397e4e66f.png">
(8) previously added and removed variables are not removed from suggestions (in source view global scope)
<img width="479" alt="image" src="https://user-images.githubusercontent.com/1029806/28366173-2de60ae2-6ca9-11e7-8151-2cfcc96de18f.png">
(9) when defining a global variable, the suggestions have different variations of the global variable - GLOBAL, GLOB etc
<img width="982" alt="image" src="https://user-images.githubusercontent.com/1029806/28370380-c8107824-6cb7-11e7-9e6f-69c2c34d1580.png">

**Comment by nadeeshaan** [comment]
This is a;ready fixed in the latest master. Hence closing
