### ISSUE TITLE
Change settings button for run application settings

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2443]
Current icon doesn't give the feeling of a settings button. 
<img width="247" alt="screen shot 2017-07-19 at 5 52 01 pm" src="https://user-images.githubusercontent.com/6814264/28366637-402d0334-6cab-11e7-9d22-3bc281e04c66.png">

Can we add a meaningful icon - Eg: "cog-wheel"

**Comment by pahans** [comment]
IMO this is a configuration that's why I added a configurations icon. @srsharon WDYT?

**Comment by srsharon** [comment]
Well the icons there looks like its apart of application, 
IMO I think we need to redesign this, reason being if you click on application, it doesn't give the feeling of run application. 

The configuration icon is fine just that the representation doesn't give a user the feeling, that he/she has the ability to click on this.

**Comment by pahans** [comment]
closing this because implementation and UI changed.
