### ISSUE TITLE
[Content Assist] Auto import function invocations in source view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2445]
In design view import is auto added when we drag a function invocation. Same experience must be provided in source view, when a user does a function invocation using content assist.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/1029806/28367139-4f144d4c-6cad-11e7-9391-4e095d853a37.png">

**Comment by NipunaMarcus** [comment]
This will be tracked in the task created for new language server implementation hence closing this issue.
