### ISSUE TITLE
[Content Assist] issues/improvements related to packages

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2446]
(1) packages are populated in global scope, but when selected, only adds identifier. Ideally should not be shown without import keyword (related to (3))
<img width="533" alt="image" src="https://user-images.githubusercontent.com/1029806/28366693-74fbb632-6cab-11e7-94ed-e7c157474726.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1029806/28366697-7aa002b4-6cab-11e7-9855-98bf765bd57a.png">

(2) packages are not shown in suggestions with import keyword
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1029806/28366721-946846f2-6cab-11e7-8dda-afe3c193e4d6.png">

(3) packages  are not showing in an empty bal file but showing in a file with global variable
<img width="591" alt="image" src="https://user-images.githubusercontent.com/1029806/28366946-670c7a88-6cac-11e7-86c0-1926e45873b8.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1029806/28366919-4b51067e-6cac-11e7-952c-75c9201cda64.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1029806/28366932-5a0e9e88-6cac-11e7-8389-294fec81c014.png">

When do we show connector packages and when do we not show? Not clear as per above 3 cases.
(4) cant we show imports similar to connector packages similar to (3) without asking users to type ballerina > org> .. etc
<img width="386" alt="image" src="https://user-images.githubusercontent.com/1029806/28367011-b4d948fe-6cac-11e7-9577-fc375d908ebb.png">

(5) should we bring strings and org.ballerina.strings to one?? 
<img width="398" alt="image" src="https://user-images.githubusercontent.com/1029806/28367298-fe83cc26-6cad-11e7-89af-08fceae0e407.png">

(6) since there is no meaning of using just "strings" shall we add "strings:" by default?
<img width="193" alt="image" src="https://user-images.githubusercontent.com/1029806/28367345-2d132640-6cae-11e7-92fb-b7b1c256b789.png">

(7) package names are shown in identifier suggestions
<img width="927" alt="image" src="https://user-images.githubusercontent.com/1029806/28370142-2a70e5b8-6cb7-11e7-8087-1afcddfdb9a7.png">

(8) function invocations are not visible in service level variables
<img width="973" alt="image" src="https://user-images.githubusercontent.com/1029806/28372367-21c73006-6cbd-11e7-9c7e-9ae10f19792b.png">

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
