### ISSUE TITLE
[Content Assist] Snippet support

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2448]
(1) snippet behavior for statements is different from constructs
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1029806/28367609-3213149c-6caf-11e7-8a51-1c67a0b5e8fd.png">
 having the service still listed, will allow the snippet to be added.

But if it is a statement, suggestion dissapears when typing complete keyword, hence snippet cannot be added with enter after typing.
<img width="195" alt="image" src="https://user-images.githubusercontent.com/1029806/28367658-66de7608-6caf-11e7-8a3f-2570cfd032a9.png">

<img width="140" alt="image" src="https://user-images.githubusercontent.com/1029806/28367636-5427729e-6caf-11e7-8f9e-36e2924c0c1f.png">

(2) try catch block snippet currently is errorneous in the catch block.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1029806/28367707-8f577670-6caf-11e7-8801-ddef91d0416b.png">
we should change it to below with the errors import.
<img width="259" alt="image" src="https://user-images.githubusercontent.com/1029806/28367741-a67285f2-6caf-11e7-9ee3-1c491168b306.png">
If the snippet is wrong, content assist breaks from here in whole of the file.

**Comment by nadeeshaan** [comment]
2 has been fixed.

**Comment by NatashaWso2** [comment]
For both constructs and statements, suggestions disappear when typing the complete keyword, hence snippet cannot be added with enter after typing the complete keyword. The behavior of constructs and statements when adding suggestions are consistent.
