### ISSUE TITLE
Content Assist does not work in block statements

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2449]
(1) content assist completely breaks after adding try catch block
```
import ballerina.lang.errors;

service<http> serviceName{
    @http:GET { }
    resource resourceName (message m) {
        try {
 
        } catch (errors:Error e) {
            
        }
    }
}
```
(2) Content assist does not work inside transform statement
<img width="231" alt="image" src="https://user-images.githubusercontent.com/1029806/28368745-18fc3854-6cb3-11e7-8d11-29149096d344.png">

**Comment by NipunaMarcus** [comment]
This error occur when trying to type something after adding try block
![language server isse](https://user-images.githubusercontent.com/9109762/28517574-6d0e227c-7082-11e7-89ee-e585243cec72.png)
