### ISSUE TITLE
[Content Assist] Transaction statement not supported

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2450]
(1) No suggestions and snippet completion
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1029806/28368356-af52cc3e-6cb1-11e7-8de0-c9da33ebcaf9.png">

(2) content assist breaks with transaction statement
<img width="365" alt="image" src="https://user-images.githubusercontent.com/1029806/28368428-edddf5f0-6cb1-11e7-80c0-a59e6124c49f.png">

**Comment by NipunaMarcus** [comment]
Issue has been fixed hence closing this ticket.
