### ISSUE TITLE
Content assist suggestions issue with ordering/filtering

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2453]
When searching for str (strings), "ballerina.lang.strings" should appear before connector packages since it is a better match. However, the ordering gives precedence to wrong packages.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1029806/28368973-c6fc8dfa-6cb3-11e7-81c7-8a375fb8afd3.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/1029806/28369047-01c47e20-6cb4-11e7-8dfc-d1b71bbb13fb.png">

`import ballerina.lang.errors;

function name () {
    
    fork {
        worker worker1{
            int x = strings:length("hello");
        }
    }
    
}`

**Comment by NatashaWso2** [comment]
This is fixed in the latest master. Suggestions given by content assist is in the proper order as below: 
![string](https://user-images.githubusercontent.com/13446645/32757308-e8fd42e8-c904-11e7-9757-1b7e69876461.png)

So this issue can be closed
