### ISSUE TITLE
[Content Assist] Fork Join snippet completion not working

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2456]
(1) No suggestion/snippet for join
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1029806/28369396-10c86a02-6cb5-11e7-8a10-f4d49b7a6310.png">
(2) no suggestions/content assist inside join block

**Comment by dilinisg** [comment]
Duplicates https://github.com/ballerinalang/composer/issues/2363
