### ISSUE TITLE
Composer is not working on Windows Edge

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2460]
Pack - 19/07
The samples won't be opened
Nothing displays on the canvas when drag and drop elements.

![edge](https://user-images.githubusercontent.com/1845370/28370415-e16a7d2e-6cb7-11e7-9a62-e794fd77e825.png)

**Comment by dilinisg** [comment]
Same issue observed in the second pack given to QA on 16/10/2017.

**Comment by NatashaWso2** [comment]
Duplicate of #4307 
Hence closing this issue
