### ISSUE TITLE
Step over behaves like Step in 

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2463]
Debug the program and stop at the debug pointer as shown below.

<img width="708" alt="screen shot 2017-07-19 at 7 31 41 pm" src="https://user-images.githubusercontent.com/6814264/28370854-05d60146-6cb9-11e7-8f97-64cc8bc7a95a.png">

Then click on Step over button. Correct behavior is to go to line number 11. But it will go to line number 19 which is the step in behaviour.

<img width="605" alt="screen shot 2017-07-19 at 7 32 23 pm" src="https://user-images.githubusercontent.com/6814264/28371538-ea07ee1e-6cba-11e7-936b-4d5d08efd8a0.png">

**Comment by pahans** [comment]
Fixed this in latest debug implementation in ballerina(0.91) core.
sample code
```js
import ballerina.net.http;
import ballerina.lang.system;

@http:configuration {basePath:"/echo"}
service<http> echo {

    @http:GET{}
    @http:Path {value:"/"}
    resource echo (message m) {
        http:convertToResponse(m);
        echoFunc();
        reply m;
    }
}

function echoFunc() {
    system:println("Done 1!");
    system:println("Done 21");
    system:println("Done 3!");
} 
```
