### ISSUE TITLE
[Content Assist] variables defined inside while is visible outside

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2466]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/1029806/28371626-1d73fc52-6cbb-11e7-97f5-b8b7d130d5b7.png">

the suggested variables were added and some were removed in other bal files

**Comment by nadeeshaan** [comment]
@maheeka can you please check with the latest master build? Seems like this is a caching issue. Please try clearing the cache and check whether the issue exist. Also the expected suggestions list should contain the packages as well. seems like it doesn't at this senario.

**Comment by maheeka** [comment]
I think this was because I declared x as a global variable earlier and removed. Related to https://github.com/ballerinalang/composer/issues/2441 issue (8). Please close this if it is handled in #2441

**Comment by nadeeshaan** [comment]
This issue is not due to a bug in the scoping. This is due to the issue of having global variables and breaking the suggestion mode. Hence closing this. Will be addressed with #2441.
