### ISSUE TITLE
 Connector rendering issue

### ISSUE THREAD

**Issue by manuranga** [ballerinalang/composer#2470]
Try the source form https://github.com/ballerinalang/ballerina/blob/18ab63d/samples/getting_started/twitterConnector/twitterConnector.bal

![conn1](https://user-images.githubusercontent.com/1686124/28372569-b2aab5e8-6cbd-11e7-9718-f2de2f2bf355.png)
![conn2](https://user-images.githubusercontent.com/1686124/28372571-b2b77a08-6cbd-11e7-8bf0-a01f3e01a35d.png)

**Comment by nadeeshaan** [comment]
Closing since the fix is merged
