### ISSUE TITLE
Variable Value Inspection in the Debugger is not supported for Arrays and Structs

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2480]
As shown in the below image Variable values inspection is not working for Structs and Arrays.

<img width="245" alt="screen shot 2017-07-20 at 11 46 59 am" src="https://user-images.githubusercontent.com/6814264/28403258-a0f6f3c8-6d41-11e7-997e-37bf16545e07.png">

**Comment by pahans** [comment]
closing according to this https://github.com/ballerinalang/ballerina/issues/2667
