### ISSUE TITLE
Design a way to declare XML Namespace in import level in ballerina program.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#2491]
XML Namespace Declaration can be added in the import level of the ballerina program. We need to decide a way to enable user to do this using composer.

**Comment by NipunaMarcus** [comment]
Related issue :https://github.com/ballerinalang/composer/issues/2898

**Comment by nadeeshaan** [comment]
Closing the issue since this is already addressed as mentioned in the previous comment
