### ISSUE TITLE
Annotations cannot be attached to any service, action etc. from the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2492]
Pack - 20/07
Firefox 54

Cannot select values from the drop down list

![attach](https://user-images.githubusercontent.com/1845370/28410530-99cb05ca-6d5b-11e7-83a2-f43ebc4fc767.png)

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2483
