### ISSUE TITLE
Incorrect behaviour while debugging if/else statement

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2501]
<img width="1117" alt="screen shot 2017-07-20 at 5 08 07 pm" src="https://user-images.githubusercontent.com/6814264/28415742-a5370702-6d6e-11e7-8fb1-16059263cc9f.png">

According to the program in the above image it shouldn't go to the line number 8.(reason is b1 = false) But it is going to line number 8.

<img width="1115" alt="screen shot 2017-07-20 at 5 08 20 pm" src="https://user-images.githubusercontent.com/6814264/28415978-b30a004a-6d6f-11e7-9aea-855b298bcbe4.png">

**Comment by sumuditha-viraj** [comment]
Please find the attached sample testcase.
[httpConnector.bal.zip](https://github.com/ballerinalang/composer/files/1162154/httpConnector.bal.zip)

**Comment by pahans** [comment]
Fixed this in latest debug implementation in ballerina(0.91) core.
