### ISSUE TITLE
Debugging in between few files is not working

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2502]
Please try to debug two files in the attached program directory. Debugging is not working. See the images with few debug pointers.

<img width="1075" alt="screen shot 2017-07-20 at 5 27 49 pm" src="https://user-images.githubusercontent.com/6814264/28416233-d05b065c-6d70-11e7-9bda-bf8aeaf6b46d.png">

<img width="1049" alt="screen shot 2017-07-20 at 5 28 01 pm" src="https://user-images.githubusercontent.com/6814264/28416246-e69f91ee-6d70-11e7-901b-0374b25eb2da.png">

**Comment by pahans** [comment]
this is fixed in master
