### ISSUE TITLE
Avoid snippet suggestions in design view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2516]
![image](https://user-images.githubusercontent.com/1029806/28436179-9d567640-6db3-11e7-9871-7424450fb7c9.png)

I wanted to type "s" but ended up adding the complete snippet.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1029806/28436254-e1472002-6db3-11e7-8aa1-431340475cc3.png">

**Comment by NipunaMarcus** [comment]
added a completer filter to fix this scenario. But this appear intermittent as ace editor has cached the completers somehow.
