### ISSUE TITLE
Title tag in wso2 logo

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#252]
<a href="https://github.com/erangatl"><img src="https://avatars.githubusercontent.com/u/20179540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erangatl](https://github.com/erangatl)**
_Thursday Feb 02, 2017 at 11:31 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1281_

----

It's better to remove title tag from wso2 logo

**Comment by nadeeshaan** [comment]
Fixed in the latest hence closing
