### ISSUE TITLE
[Editor] Compatibility issues with IE11

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#255]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Thursday Feb 02, 2017 at 12:00 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1286_

----

used IE 11 on Windows 10
- Menu options (save, open, etc ) are not working 
- Drag and drop not working properly

![ie11](https://cloud.githubusercontent.com/assets/15671620/22548585/29a8054e-e96d-11e6-8b6a-416363b86ef6.jpeg)

**Comment by hevayo** [comment]
The diagram implementation has changed we will check if the new UI cause similar behavior with IE 11.

**Comment by dakshika** [comment]
@handakumbura : can you verify this with the latest version?

**Comment by dakshika** [comment]
related issue https://github.com/ballerinalang/composer/issues/159

**Comment by maheeka** [comment]
We do not recommend IE11 and we will be supporting Edge going forward.
