### ISSUE TITLE
 Source Editor Color or Size cannot be changed from Settings

### ISSUE THREAD

**Issue by keizer619** [ballerinalang/composer#2571]
- Go to  File->Settings
- Change Source Editor Color or Size
- Following error will be printed 

` Uncaught TypeError: e.tabController.getActiveTab(...).getBallerinaFileEditor is not a function`

**Comment by NatashaWso2** [comment]
This feature is currently not available. So the composer preferences cannot be changed by the user. This will be supported by future versions of composer hence closing this issue.
