### ISSUE TITLE
Bug when calling connector action in println method

### ISSUE THREAD

**Issue by upeksha1996** [ballerinalang/composer#2601]
When entered following code in the main method, the design view went blank
    system:println(DatabaseConnector.insertTweet(567567,"just tweeting <3 <3 <3"));

When inserted in two lines it worked
  any dbContent = DatabaseConnector.insertTweet(567567,"just tweeting <3 <3 <3");
  system:println(dbContent);

**Comment by nadeeshaan** [comment]
This is not supported in Ballerina. According to the Grammar specifications, action invocation should either be as a variable definition statement or as a assignment statement. This is mainly due to the visual first concept of Ballerina. Closing the issue since this is not support in the language
