### ISSUE TITLE
Worker Invocation move down will not increase the lifeline height

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#2608]
Issue is reproduced when we have a worker invocation and statements after the invocation statement.

![selection_093](https://user-images.githubusercontent.com/1329674/28510613-05b597ba-7067-11e7-8a3d-ee8afa495f9c.png)

**Comment by dilinisg** [comment]
Another scenario:
![default22](https://user-images.githubusercontent.com/1845370/29964193-e94e768a-8f26-11e7-869a-5cb478e20b9b.png)

**Comment by nadeeshaan** [comment]
The issue has been fixed in the latest master build. Hence closing
