### ISSUE TITLE
[Annotations] Typemapper should be removed from the list annotation attachment list

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2609]
Release 0.91

![attach](https://user-images.githubusercontent.com/1845370/28513396-aa3511f6-7073-11e7-9b76-43c31d2c004c.png)

**Comment by hemikak** [comment]
See packaged-scope-environment.js

**Comment by NipunaMarcus** [comment]
We cannot remove typemapper keyword from the list and make it transform as it is still defined as typemapper in the ballerina lang and it is a attachment point for the annotation defintion. 

Annotation Def -
https://github.com/ballerinalang/ballerina/blob/master/docs/grammar/BallerinaParser.g4#L93
Attachment Points -https://github.com/ballerinalang/ballerina/blob/master/docs/grammar/BallerinaParser.g4#L106

**Comment by dilinisg** [comment]
@NipunaMarcus : We don't need to make it transform right? Transform does not need annotations.

**Comment by NipunaMarcus** [comment]
@dilinisg : I don't think we can remove it either as parser grammar has the typemapper as a attachment point for annotation definition. Let me check with the runtime team.

**Comment by NipunaMarcus** [comment]
There is a ongoing discussion about typemapper as transformer related changes going. After that this will be removed from the list. Until that moving this ticket to onhold.

**Comment by NipunaMarcus** [comment]
as to latest decisions annotations definitions are not be able to added to composer diagram or not be rendered within. Because there is no point of adding annotations as we cannot use them in the scope.hence closing this issue.
