### ISSUE TITLE
reformat code option seems to break the working code 0.90

### ISSUE THREAD

**Issue by shavantha** [ballerinalang/composer#2613]
reformat code option seems to break the working code 0.90

steps
1.load the attached code within code_reformat.zip on a ballerina composer fro, 0.90
2.start the service and invoke
3.click on reformat code and note that errors are introduced

Note: the original code was written over 0.89 version and I changed below line to meet the new syntax and started using the service.
![reformat](https://user-images.githubusercontent.com/6552100/28517710-daad4a3e-7054-11e7-8a48-3c07c85f5858.png)

FROM
======
@http:config {basePath:"/coverage"}

TO
====
@http:configuration {
    basePath: "/coverage"
}
[code_reformat.zip](https://github.com/ballerinalang/composer/files/1169408/code_reformat.zip)

**Comment by hevayo** [comment]
Hi This is due to a known issue in 0.90 where connector identifier gets duplicated with formatting. This is fixed in the latest 0.91 release.
