### ISSUE TITLE
[Swagger] Multiple HTTP methods for a resource are not supported in swagger

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2619]
Release 0.91

If we implement a resource like below, only one HTTP method will be displayed in the swagger view
```
@http:POST {}
@http:GET {}
@http:Path {value:"/book/{country}"}
    
resource passthrough (){
}
```

**Comment by hemikak** [comment]
Waiting till https://github.com/ballerinalang/ballerina/issues/3073 is resolved.

**Comment by hemikak** [comment]
Ballerina does support multiple http method verbs. See "Support for multiple HTTP verbs in generated Swagger definitions." @ballerina-dev@googlegroups.com on how this is supported in the swagger editor.
