### ISSUE TITLE
Cannot run a service when there are issues in the annotation attachment 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2623]
Release - 0.91

**Steps**
1. In the passthrough service sample, configure the HTTP configurations as below. (without a value for the port)
2. Try to run the service

**Issue**
Cannot run the service. The button is blocked hence no error message to the user
![nomsg](https://user-images.githubusercontent.com/1845370/28557925-f5e8d448-712c-11e7-9430-8f5a31067ba3.png)

**Comment by NipunaMarcus** [comment]
As to the current implementation in this scenario user will be switched to source view as typing a empty annotation is syntactically wrong and in the source view error will be shown and user won't be able to run the program. 

![errordone](https://user-images.githubusercontent.com/9109762/29169554-2c53fe1e-7df2-11e7-909a-14df4d1a00b9.png)

Hence closing this issue.
