### ISSUE TITLE
Can we "beautify" delete file confirmation? 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#263]
<a href="https://github.com/uthaiyashankar"><img src="https://avatars.githubusercontent.com/u/2410076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [uthaiyashankar](https://github.com/uthaiyashankar)**
_Friday Feb 03, 2017 at 06:46 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1322_

----

We need to adjust the style a bit. 
<img width="765" alt="screen shot 2017-02-03 at 12 14 59 pm" src="https://cloud.githubusercontent.com/assets/2410076/22582071/7d427606-ea0a-11e6-9227-7855ed3eb788.png">

**Comment by hevayo** [comment]
I guess it is a must to have red color in this dialog.

**Comment by dakshika** [comment]
![ballerina composer](https://user-images.githubusercontent.com/6497326/27864226-4f2d76c6-61ab-11e7-9d25-613b3cc197cc.png)

This is the current status of this

**Comment by nadeeshaan** [comment]
This has been revamped as following.

![selection_128](https://user-images.githubusercontent.com/1329674/32154151-bdf11a18-bd54-11e7-9f9a-1c0f10271c46.png)

Hence closing the issue
