### ISSUE TITLE
[Debugger] Global variables are not shown in frame

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2634]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/1029806/28658522-5aee83f4-72c9-11e7-91d0-ca162e5662ee.png">

Global variable people is not visible in the frame.

**Comment by pahans** [comment]
This is a run time issue. closing this in favor of https://github.com/ballerinalang/ballerina/issues/2669
