### ISSUE TITLE
Function invoke, assignment and variable constructs accept any value

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2646]
Release - 0.91

**Steps**
1. Add a function invoke construct
2. Write the function invocation as "int i = 1"

**Issue**
It will save the value without reverting it back

**Comment by NipunaMarcus** [comment]
Design of this for now is to use a statement box as a general statement box. So it will change to the respective statement when the statement type changed. This will be further discuss in Design review. Until that moving this ticket from bug to enhancement.

**Comment by hevayo** [comment]
Implementation has differed we will no longer have statement boxes from 0.95.6
