### ISSUE TITLE
Make the add button visible all the time to add different code blocks

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2655]
Release - 0.91

The add button is currently visible only when you hover over the code block (eg: transaction block). So you might not notice that. Therefore, make it visible all the time so that people know code blocks can be added from there

![plusbutton](https://user-images.githubusercontent.com/1845370/28872859-9756f6e4-77a8-11e7-93ec-17f787e856d6.png)

**Comment by NipunaMarcus** [comment]
This has been fixed with the current master hence closing this issue.
