### ISSUE TITLE
Jump to source should highlight the source code selected

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2661]
Release 0.91

**Steps**
1. Click on jump to source in a particular statement in the design view
2. The source view will be loaded

**Enhancement**
The source view should highlight the particular statement that triggered this action. Otherwise it will be as same as moving to the source view from the source view tab

**Comment by kaviththiranga** [comment]
Instead of highlighting we now move source editor cursor to starting position for that particular element.
Fixed with
https://github.com/ballerinalang/composer/pull/2683/files
