### ISSUE TITLE
[Lang Server] out of scope variables are suggested for completers

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2663]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/1029806/28955779-71b19584-7906-11e7-8a89-fa523e0b98e4.png">
<img width="878" alt="image" src="https://user-images.githubusercontent.com/1029806/28955803-9beeba84-7906-11e7-95df-e80d3eb7f3b6.png">

var3 should not be shown in completers

**Comment by nadeeshaan** [comment]
Closing the issue since this is resolved
