### ISSUE TITLE
Wrong version and question mark in the footer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2669]
![footer](https://user-images.githubusercontent.com/1845370/29108032-bf98da8a-7cfa-11e7-8b75-df8ccb8038c8.png)

**Comment by NatashaWso2** [comment]
Correct version is included in the footer in the latest pack (both in Chrome and Firefox)
![firefox](https://user-images.githubusercontent.com/13446645/29122618-9ddab798-7d30-11e7-932e-e284b4483a93.png)
![chrome](https://user-images.githubusercontent.com/13446645/29122619-9ddaf67c-7d30-11e7-959f-dad9b51d5bde.png)

**Comment by nadeeshaan** [comment]
Closing the issue based on the previous comment

**Comment by dilinisg** [comment]
Reopening as I can still observe the above issue. Checked in the following browsers.
Chrome - 56
Firefox - 54

**Comment by pahans** [comment]
Might be a font loading issue. What's your operating system?

**Comment by dilinisg** [comment]
Checked in Windows 7 and Ubuntu 15.10. Same issue in the About us page as well.
![about](https://user-images.githubusercontent.com/1845370/29519057-860c1950-8699-11e7-8b8c-d55acb782411.png)

**Comment by NatashaWso2** [comment]
This issue is fixed in the latest master, hence this issue can be closed.
