### ISSUE TITLE
Break statement shouldn't be allowed in constructs other than loops

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2687]
Release - 0.91

**Steps**
1. Add a break statement inside fork-join, try-catch etc. from the design view
2. Run the program

**Issues**
Errors when running the program

**Comment by nadeeshaan** [comment]
Currently we use only the syntactic validation at the composer level. Since this issue is syntactically valid according to the grammar it won't capture as an error. Composer will be combined with syntactical validation in later releases. This enhancement will be onhold until then

**Comment by kaviththiranga** [comment]
Fixed with 
https://github.com/ballerinalang/composer/pull/2710
