### ISSUE TITLE
Double click on the service name, function name, structure name does not select the name

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#271]
<a href="https://github.com/uthaiyashankar"><img src="https://avatars.githubusercontent.com/u/2410076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [uthaiyashankar](https://github.com/uthaiyashankar)**
_Friday Feb 03, 2017 at 11:03 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1343_

----

$subject. You have to click 3 times to select the name. Also, once selected like this, the name cannot be editable. 

This behaviour is different for resources. You can double click to select the name, and then you can change the name.

**Comment by hevayo** [comment]
Fixed with react implementation available from 0.87
