### ISSUE TITLE
[Content Assist] No suggestions for function parameters

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2722]
Release - 0.91.1
![ca2](https://user-images.githubusercontent.com/1845370/29209630-29e57534-7ead-11e7-90d9-b8a27c650b14.png)

![ca1](https://user-images.githubusercontent.com/1845370/29209631-29e6faee-7ead-11e7-960b-3442a9d347d4.png)

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
