### ISSUE TITLE
[Editor] Observed an inconsistency behavior in remove buttons

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#274]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Friday Feb 03, 2017 at 12:32 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1357_

----

- In variable / constant variable declaration, click on the 'remove' button collapse the editable text field
- In struct, it clears the characters 
Usability: Better if we keep the consistency.

![remove_button](https://cloud.githubusercontent.com/assets/15671620/22591462/b582723e-ea3a-11e6-9a84-23a640b41b97.jpeg)

**Comment by dakshika** [comment]
Seems this is fixed on latest master 19956702379f9413a48be47f734dd6862be5c4c2
