### ISSUE TITLE
[Debugger] UI issues when removing arguments

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2789]
Release 0.92

**Issues**
1. No remove button for the first argument
2. A close button above the first arguments which is not working and also inconsistent

![args2](https://user-images.githubusercontent.com/1845370/29453841-b52af562-8428-11e7-851d-d133d49cb30a.png)

**Comment by NipunaMarcus** [comment]
Issue is fixed hence closing the issue.
