### ISSUE TITLE
[Debugger] Line by line execution does not happen when multiple lines of code are written in a single line

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2790]
Release 0.92

**Sample**
```
import ballerina.lang.system;
function main (string[] args) {
    system:println("Hello, World1!"); system:println("Hello, World2!"); system:println("Hello, World3!"); system:println("Hello, World4!"); if(true){ system:println("Hello, World5!");}
}

```
**Issue**
When debugging the above sample first the following output will be printed all at once.
```
Hello, World1!
Hello, World2!
Hello, World3!
Hello, World4!
```
Step over once -> Hello, World5! will be printed 
Step over again to stop the execution

**Comment by pahans** [comment]
Related to https://github.com/ballerinalang/ballerina/issues/3276

**Comment by pahans** [comment]
closing this in favour of https://github.com/ballerinalang/ballerina/issues/3276
