### ISSUE TITLE
Implement undo manager's state change upon design-source-swagger view switch

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#280]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Saturday Feb 04, 2017 at 04:22 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1389_

----

We need to come up with a proper state management policy when switching between different views and doing modifications to file via each one of them.  We need to make undomanager aware of view switching. Bascially, when a user switch to each one of different views, it should clear out the undo stack from previous view - only if user user do some modification in new view. Otherwise it should keep the stack as it is.  For example, if user just want to see whats in generated source he should be able to goto source view and come back without getting his undo stack cleared.

**Comment by kaviththiranga** [comment]
This is not needed with the new unified undo/redo based on the generated source diff for each user action.
