### ISSUE TITLE
[Debugger] The debugger tool pallet will be removed when debugging a service

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2807]
Release - 0.92

**Steps**
1. Debug a service

**Issue**
When one full execution is over (when the message is sent to the client), debugging will end from the left pane, meaning the tool pallet will be removed, but in background debugging is active. Since the tool pallet is no more there, we can start debugging again causing "Address already in use"

![debug23](https://user-images.githubusercontent.com/1845370/29514729-2fa9ad1e-8687-11e7-9a39-59ed12d0622a.png)

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2902
