### ISSUE TITLE
[Windows][Debugger] Another tab with the same service is opened when debugging a service

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2808]
Release 0.92
Windows
Firefox

**Steps**
1. Add several debug points to a service
2. Start debugging

**Issues**
1. When the first debug point is hit, a new tab will be opened with the same service
2. When other debug points are hit, the user will be shifted to the new tab opened in 1

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2859
