### ISSUE TITLE
Issues in reformat code

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2814]
Release 0.92

**Issues**
1. Indentation issues
2. Spaces that are kept intentionally are also removed

Before:
![rc1](https://user-images.githubusercontent.com/1845370/29518479-24f13c6a-8697-11e7-936f-22b0beb03f96.png)

After Reformat:
![rc2](https://user-images.githubusercontent.com/1845370/29518482-2a8a47f2-8697-11e7-9c3c-4ac63a1a310c.png)

**Comment by hevayo** [comment]
Fixed in 0.95
