### ISSUE TITLE
Typeof keyword is not supported in the composer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2827]
Release 0.92

`type x = typeof i;`

**Issues**
1. No suggestions in both source view and design view
2. This is re-formatted as "typeofi" in the design view

**Comment by dilinisg** [comment]
Release 0.93

**Actual**
```
type typeOfVariable = (typeof variable);
type typeOfIntVariable = (typeof intVariable);
```

**Source view**
```
type typeOfVariable = typeofvariable;
type typeOfIntVariable = typeofintVariable;
```
**Same in design view**

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed.
See line 6 and 7 in the attached image
![typeof and lengthof](https://user-images.githubusercontent.com/13446645/32602734-3ccf55f0-c56d-11e7-8f16-44ac7a6b7cc1.png)
