### ISSUE TITLE
Lengthof keyword is not supported in the composer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2828]
Release 0.92

`int length = lengthof dataset.persons;`

**Issues**
1. No suggestions in both source view and design view
2. This is written as "lengthofdataset.persons"

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed.

See line 8 in the attached image
![typeof and lengthof](https://user-images.githubusercontent.com/13446645/32602662-f636699e-c56c-11e7-8105-efbf077ad8d0.png)
