### ISSUE TITLE
[ContentAssist] Suggestions are not given when there are errors in the code

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2829]
Release 0.91

Suggestions are not given when there are errors in the code. This should work even when there are errors

**Comment by NatashaWso2** [comment]
Suggestions are given even when there are errors in the code in the latest master.
![suggestions-with-errrors](https://user-images.githubusercontent.com/13446645/32934680-9fc05ae4-cb92-11e7-86d7-93f4179bd20b.png)

Since this is fixed, this issue can be closed.
