### ISSUE TITLE
Invalid import: "Current Package" should be removed

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2834]
Release 0.91

Invalid import statement: "Current Package" should be removed

**Comment by dilinisg** [comment]
![cp3](https://user-images.githubusercontent.com/1845370/30369041-c625983c-9890-11e7-9554-808cc07db09c.png)

**Comment by NatashaWso2** [comment]
Current Package is removed from both annotation packages and import suggestions as below:

**_annotations_**
![annotations](https://user-images.githubusercontent.com/13446645/32946199-98a8aa98-cbbc-11e7-83ce-241558cfbb97.png)

**_import suggestions_**
![imports](https://user-images.githubusercontent.com/13446645/32946214-a282e182-cbbc-11e7-8247-5a847b0ea0a3.png)
