### ISSUE TITLE
[ContentAssist] Wrong suggestions for json arrays and function parameters

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2838]
Release 0.92

For the commented line In the below code, no suggestions were given to 
1. dataset parameter 
2. for persons[i], wrong suggestions for i

```
function insertPerRecordToDB (json dataset) (string[], int, errors:Error){
...
   while (i < length) {
     //  var lastname, _ = (string)dataset.persons[i].lastname;
   }
}
```

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
