### ISSUE TITLE
[Editor] Improvements for 'Import packages' 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#287]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Monday Feb 06, 2017 at 06:46 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1424_

----

1. There is no indicator (red-line) marked for wrong package name (e.g. import ballerina.lang.ssystem) in both graphical and source view; Could save the bal file.

![import1](https://cloud.githubusercontent.com/assets/15671620/22636988/2a34283a-ec65-11e6-96d8-3e85876d4b6b.jpeg)
![import3](https://cloud.githubusercontent.com/assets/15671620/22637009/596ab876-ec65-11e6-976a-1ade49fca07c.jpeg)

2. No option to edit the package name(if wrong characters added) in graphical view, rather needs to be removed and re-type or change from source view.

![import4](https://cloud.githubusercontent.com/assets/15671620/22637020/708b87d8-ec65-11e6-8290-538dfb2e36fa.jpeg)

**Comment by hevayo** [comment]
Issue [2] is fixed in 0.87 with added option to change the package name.

**Comment by dakshika** [comment]
Currently, we are showing the error on source view. we can map that to UI as well.

**Comment by maheeka** [comment]
Imports can now be edited.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1029806/32717142-7f52a8ec-c850-11e7-8dd4-ff370a4059cc.png">

Erroneous imports are indicated.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1029806/32717177-98a81656-c850-11e7-8506-02063bf14244.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/1029806/32717187-9fcaa944-c850-11e7-95bd-e02bdd360fd9.png">
