### ISSUE TITLE
Too many options for the same functionality when debugging which is complicated

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2870]
Pack - 23/08/2017

The same debugging functions can be seen at two places which confuses a first time user as to which one to use. Also, one option is with colors and the other without colors.

![debug111](https://user-images.githubusercontent.com/1845370/29599631-bf77b93c-87ee-11e7-9a38-446711749270.png)

**Comment by pahans** [comment]
fixed in latest master
