### ISSUE TITLE
[xmlLiterals] xml written cannot be preserved

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2897]
Pack - 23/08/2017

xml x4 = xml `<?foo  <aaa{{v1}}bbb{{v2}}ccc??d?e>?f<<{>>>?>`

This above written in design view is saved as below giving errors in the source view

xml x4 = xml `<?foo ?>`;

**Comment by NipunaMarcus** [comment]
This is fixed in the current release.
