### ISSUE TITLE
Worker interaction link cannot be manually drawn

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2926]
Pack - 23/08/2017

**Steps**
1. Add two workers
2. Add send and receive. Don't change the names first
3. Try to draw the connectivity link between send and receive

**Issue**
Cannot draw as link as those two are in different levels. Hence, the option to draw should be deleted.
![connectorwrks2](https://user-images.githubusercontent.com/1845370/29618767-ceb94440-8836-11e7-8c11-877658f4471d.png)

Note: When the send and receive is renamed with correct names, the connection will be automatically drawn

**Comment by NatashaWso2** [comment]
With the current version of the composer we do not allow the worker interaction link to be manually drawn. Renaming the send and receive with correct worker names would automatically draw the interaction link. The design is not yet finalized and is under discussion.

**Comment by hevayo** [comment]
As of 0.95.6 we have removed the drawing of lifelines, instead user has to enter the proper worker names.
