### ISSUE TITLE
[Editor] Welcome page should not have a close button unless there is simple way to retrieve it back

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#293]
<a href="https://github.com/ushanib"><img src="https://avatars.githubusercontent.com/u/12966170?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ushanib](https://github.com/ushanib)**
_Monday Feb 06, 2017 at 09:08 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1440_

----

Welcome page should not have a close button unless there is simple way to retrieve it back.

If a user accidentally closes the welcome page, to retrieve it back, user should figure out how to do it. (At the moment you have to open a new file and close it to retrieve welcome page back.)

When you close it editor goes blank, which does not look nice.

Therefore better to have the Welcome page as default.

![screenshot from 2017-02-06 14-38-07](https://cloud.githubusercontent.com/assets/12966170/22640734/eb774720-ec79-11e6-9281-ed00b5b34727.png)

**Comment by maheeka** [comment]
Now the welcome page can be opened from the Help menu.
