### ISSUE TITLE
Indicate which view the user has selected out of the 3 views

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2938]
Release 0.93

The user should know in which view they are by looking at the tool box. For example just like highlighted in the image below.

![3views](https://user-images.githubusercontent.com/1845370/29771939-dad3a050-8c13-11e7-8914-8bffda488ab4.png)

**Comment by hevayo** [comment]
Implementation has differed we no longer has the above buttons in composer from 0.95.6
