### ISSUE TITLE
Tool bar item menus do not close when click outside

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#2944]
At the moment we need to click on the tool bar item itself to close the menu. Should allow the same behaviour when clicking
![selection_104](https://user-images.githubusercontent.com/1329674/29776588-aed19ff8-8c26-11e7-9751-1b07a9cdd668.png)
 outside

**Comment by dilinisg** [comment]
Duplicates https://github.com/ballerinalang/composer/issues/2876

**Comment by nadeeshaan** [comment]
Closing since issue is duplicated
