### ISSUE TITLE
Path is highlighted when a user hover over the breadcrumb which gives the feeling that it can be clicked

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2946]
Release 0.93

Path is highlighted when a user hover over the breadcrumb which gives the feeling that it can be clicked

![breadcrumb2](https://user-images.githubusercontent.com/1845370/29804537-d8b52950-8ca0-11e7-97df-de900fe3c142.png)

**Comment by NatashaWso2** [comment]
Breadcrumb was removed from the composer by design in the latest master, hence this is no longer valid.
So this issue can be closed.
