### ISSUE TITLE
No effect if a user wants to navigate to the 3 views from the source and swagger views

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2950]
Release 0.93

**Steps**
1. Go the source of swagger view
2. Click on any of the 3 views (default/compact..)

**Issue**
No effect. Either these buttons should be disabled when the user is in the source/swagger views or facilitate the user to navigate between the 3 views

**Comment by hevayo** [comment]
Toolbar was removed in 0.95.6 and the view selector is Incorporated to design view itself.
