### ISSUE TITLE
Doc support for functions in the current package

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2952]
Release 0.93

Doc support is available for functions under the current package and gives a 404 when loaded

![doc1](https://user-images.githubusercontent.com/1845370/29808227-d45f464c-8cb4-11e7-9413-d95f36d3ea56.png)

![404](https://user-images.githubusercontent.com/1845370/29808006-0f8cbd72-8cb4-11e7-8f68-5245855dd859.png)

**Comment by NatashaWso2** [comment]
Current package cannot have a doc as for now only native packages has documents so the document icon is not shown to current package items in the latest master. Since this issue is resolved, this can be closed.
