### ISSUE TITLE
Disable features that are not applicable for the welcome page

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2968]
Release 0.93

In the welcome page, run, debug, 3 views, redo, undo, save in the tool pallet and left pane should be disabled as those features are not relevant. Clicking on some of the features gives invalid error messages

![disable](https://user-images.githubusercontent.com/1845370/29909217-75dd0296-8e42-11e7-9bbf-0bc632b5d248.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 83f36e6e96fe5537d07b8428ad606dbbe4cfd998
