### ISSUE TITLE
[Firefox] Transform sample layout issues

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2969]
Release 0.93
Firefox browser

Transform sample : Initial view 
![initialviewtf](https://user-images.githubusercontent.com/1845370/29909806-3185015e-8e45-11e7-88fc-f14c3770ab83.png)

After scroll down
![scrolltf](https://user-images.githubusercontent.com/1845370/29909820-3aaf6684-8e45-11e7-9c86-58ef34565d07.png)

**Comment by keizer619** [comment]
This issue has been fixed for 0.94 release
