### ISSUE TITLE
Composer freezers when a sql action statement is added

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2973]
Release 0.93
 
`TypeError: c is undefined` error in the console when the update action statement is added to the source view and the composer freezers when you switch between design and source view

```
transaction {
        testDB.update("Insert into Customers (firstName,lastName,registrationID,creditLimit,country) values ('James', 'Clerk', 200, 5000.75, 'USA')", parameters);
    } aborted {
        returnVal = -1;
    }
```

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing the issue. Please reopen if the issue exists in the latest build as well
