### ISSUE TITLE
Debugger doesn't connect intermittently on cloud environment

### ISSUE THREAD

**Issue by pahans** [ballerinalang/composer#2987]
Debugger doesn't connect intermittently on cloud. Have to click reconnect button when it fails to connect. 
Debugger backend [opens port 5006](https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/util/debugger/VMDebugServer.java#L87) in the server and [outputs](https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/util/debugger/VMDebugServer.java#L90)  
"Ballerina remote debugger is activated on port 5006".  After listening to this message debugger client  opens a websocket channel to debugger backend. This fails intermittently on cloud environment.
This flow works fine when working locally and in a [simulated internet connection.](https://ngrok.com/)
![selection_061](https://user-images.githubusercontent.com/1552869/29937393-fbcd8fe6-8ea2-11e7-91ac-21031b74dec3.png)

**Comment by hevayo** [comment]
Closing since composer on cloud is deprecated.
