### ISSUE TITLE
[Editor] Error when renaming a function/service name

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#299]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Feb 06, 2017 at 10:37 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1458_

----

Browser - Firefox 51.0.1
1. Add a service or a function
2. Try deleting the characters of the existing name

Issue
"Invalid name" error message pops up for each character deleted in the name

![name](https://cloud.githubusercontent.com/assets/1845370/22643823/27cd5a14-ec86-11e6-9a17-7dba7f2b6ee6.png)

**Comment by pahans** [comment]
tested this on firefox 51.0.1 and chrome. It is working now.

**Comment by nadeeshaan** [comment]
Closing based on the last comment
