### ISSUE TITLE
Errors when debugging a program with fork-join

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2991]
Release 0.93

The attached ballerina program which uses a fork-join runs successfully. But when you try to debug, getting the following errors.

```
Debugging started...
error in worker 'subWorker2': ballerina.lang.errors:Error, message: 5
	at .:main(fork-join-test2.bal:23)
error in worker 'addWorker1': ballerina.lang.errors:Error, message: 5
	at .:main(fork-join-test2.bal:8)

```
[fork-join-test.txt](https://github.com/ballerinalang/composer/files/1270126/fork-join-test.txt)

**Comment by pahans** [comment]
closing in favour of https://github.com/ballerinalang/ballerina/issues/4134
