### ISSUE TITLE
Variables are shown in the same frame when debugging two resources

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2992]
Release 0.93

**Steps**
1. Debug a bal file with 2 services in the same bal file

**Issue**
When displaying variables, the variables in the first resource is replaced with the second resource variables. But, when debugging a main function and a function, the variables in the main function are shown even at the time the function is debugged. So, it is not consistent

**Comment by pahans** [comment]
this is fixed in latest master
