### ISSUE TITLE
Variables added after debugging has started can be debugged, but values are not shown in the value inspector

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2998]
Release 0.93
Variables added after debugging has started can be debugged, but values are not shown in the value inspector.

**Steps**
1. Start debugging a program
2. Add a new variable declaration while debugging (int i = 3)
3. Add a debug point to the new variable
4. Continue debugging

**Issue**
The new variable can be debugged, but the value will not in the value inspector. 
Same behavior in the idea plugin.

**Comment by NipunaMarcus** [comment]
@pahans  - does this support in our debugger? i don't think we do hot deployment while debugging..

**Comment by pahans** [comment]
no we dont support hot deployment while debugging
