### ISSUE TITLE
[TransformStmt] Removing connection does not unmark the circle

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2999]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1029806/30014765-a2657fce-916b-11e7-9b65-757ee4d3b29b.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1029806/30014768-a699dae0-916b-11e7-9feb-f40014b46886.png">

**Comment by roonyh** [comment]
Fixed in d2dc46bb427ef56
