### ISSUE TITLE
[Editor] Delete icon of each statements in graphical view is not visible

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#300]
<a href="https://github.com/ushanib"><img src="https://avatars.githubusercontent.com/u/12966170?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ushanib](https://github.com/ushanib)**
_Monday Feb 06, 2017 at 11:34 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1465_

----

Delete icon of each statements in graphical view is not visible.

Please see the attachment.

![screenshot from 2017-02-06 17-02-10](https://cloud.githubusercontent.com/assets/12966170/22645701/52ffbd50-ec8e-11e6-8cc3-b81c8cbc8c59.png)

**Comment by nadeeshaan** [comment]
Fixing since the fix is merged
