### ISSUE TITLE
[TransformStmt] Expand icon not working in firefox

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#3000]
<img width="152" alt="image" src="https://user-images.githubusercontent.com/1029806/30014796-d5e7c03c-916b-11e7-96b2-b503c8fb1f6d.png">

**Comment by dilinisg** [comment]
Already reported in https://github.com/ballerinalang/composer/issues/2423

**Comment by NipunaMarcus** [comment]
This happens because of the some elements in SVG doesn't support css width adjustment. They need their width and height to be passed as a element attribute.

**Comment by nadeeshaan** [comment]
Closing, since this has been addressed already in #2423
