### ISSUE TITLE
Error logged when adding Service Level Variables

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#3026]
Steps to reproduce

- Add a service definition
- Try adding a global variable definition
- Bellow error will be logged in the browser console
![selection_109](https://user-images.githubusercontent.com/1329674/30165385-8622e36c-93fd-11e7-9123-c7dac1114966.png)

**Comment by NatashaWso2** [comment]
This issue is fixed in the latest master, so this can be closed.
