### ISSUE TITLE
Alignment issues in the annotations

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3037]
Release 0.93

![alignment2](https://user-images.githubusercontent.com/1845370/30267786-46f56bfe-9701-11e7-9129-07185047bb9b.png)

**Comment by roonyh** [comment]
Not seen in 0.95
![image](https://user-images.githubusercontent.com/3872221/32882110-43c66a80-cad9-11e7-9a35-2a5d7775cfb3.png)
