### ISSUE TITLE
Block adding the same annotation more than once

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3043]
Adding the same annotation twice is not a valid scenario.

Eg:
![anno4](https://user-images.githubusercontent.com/1845370/30279270-66ff6f2a-972a-11e7-9a0b-064a4caeaefd.png)

Therefore, adding the same annotation more than once should be blocked

Note: With the current implementation for doc annotations, the same doc annotation should be able to add more than once

**Comment by NatashaWso2** [comment]
This is a duplicate of #2100, hence closing this issue.
