### ISSUE TITLE
Change the config tool tip name to a meaningful name

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3050]
Change the config tool tip name to a meaningful name. Eg: "Add arguments" 

![configtooltip](https://user-images.githubusercontent.com/1845370/30320353-fe234c8c-97cf-11e7-866c-e707c2f5f206.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master
![config-ttoltip](https://user-images.githubusercontent.com/13446645/32540174-d9feec14-c491-11e7-8624-ce35fe16f143.png)
