### ISSUE TITLE
Changes done in the transform view affect the debug points in the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3052]
Pack - Tools 0.93 11/09

**Steps**
1. Open the transform statement sample 
2. Add a debug point to a statement below the transform block (design and source views are consistent)
3. Go to the transform design view and add/remove a connection
4. Check the debug points in both design and source views

**Issue**
The debug point in the source view will be changed due to the modification, but the debug point in the design view will remain the same. So, there is an inconsistency between the two debug points in both views

**Comment by pahans** [comment]
fixed in 0.94
