### ISSUE TITLE
The height of the lifeline is not adjusted in the compact view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3053]
Pack - 0.93 13/09

The height of the lifeline is not adjusted sometimes in the compact view

Default view
![ws2](https://user-images.githubusercontent.com/1845370/30363068-71ad73ba-987c-11e7-8713-5eff1bc9ad67.png)
Compact view
![ws1](https://user-images.githubusercontent.com/1845370/30363080-7b4c978e-987c-11e7-8c98-e564e2984c77.png)

**Comment by roonyh** [comment]
@dilinisg Do you mean the minimum height of the lifeline should be decreased in the compact view? Could you clarify what the expected way the life line should be displayed?

**Comment by hevayo** [comment]
Compact view is removed from 0.95.6
