### ISSUE TITLE
Height of the transform statement is not adjusted in the compact view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3054]
Pack 0.93 13/09

Default view
![t1](https://user-images.githubusercontent.com/1845370/30363624-8c5e8c2e-987e-11e7-9082-b10df001ba6c.png)

Compact view
![t2](https://user-images.githubusercontent.com/1845370/30363628-9253fa24-987e-11e7-90f9-f7d60b0b0278.png)

**Comment by maheeka** [comment]
Transform must be expandable and hence will not make sense to compact it. 

Anyhow, it is a new top level construct and this issues is no longer valid.
