### ISSUE TITLE
Structs view is not compact in the compact view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3055]
Pack 0.93 13/09

Structs view is not compact in the compact view. Spacious above and below the table

![c1](https://user-images.githubusercontent.com/1845370/30364016-0ab75212-9880-11e7-900b-ab5b8b1bf459.png)

**Comment by dilinisg** [comment]
Can be seen in 0.95 release as well

**Comment by hevayo** [comment]
compact view has been removed from 0.95.6
