### ISSUE TITLE
Adding statements to the action view should be blocked

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3066]
Pack 0.93 13/09

Currently, the composer indicates (marking the area green) that statements can be added to the action view. But, it does not show the added statements according to the design which is correct. But, you let the user adding statements here is wrong. Also, if you switch to the default or compact view, those statements will be available. But, the user might think those statements are not added. 

Therefore, adding statements to the action view should be blocked

**Comment by hevayo** [comment]
Implementation has differed, composer no longer has the tool palette.
