### ISSUE TITLE
Add buttons should be visible to the user without making them appear only when hover

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3072]
In fork-join and try-catch additional catch blocks, finally block and timeout block can be added from the add button which is only visible when you hover over the construct. Till then users won't be aware of such feature. Therefore, this feature should be prominent to users.
![addb](https://user-images.githubusercontent.com/1845370/30416039-3a1af176-9948-11e7-94b7-ec40bafd99aa.png)

**Comment by dakshika** [comment]
This is fixed on latest master
