### ISSUE TITLE
Need tool tips for add buttons in try-catch, fork-join

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3073]
Need tool tips for add buttons in try-catch, fork-join. It confuses the user whether a catch block or a finally block is added when you click the add button in try-catch statement.

![addb](https://user-images.githubusercontent.com/1845370/30416302-44d98072-9949-11e7-9446-9c129970f8a6.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master
