### ISSUE TITLE
Finally keyword is not shown as a keyword in try-catch

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3074]
Pack 0.93 13/09

Finally keyword is not shown as a keyword as it is not colored
![try1](https://user-images.githubusercontent.com/1845370/30416433-c949bce6-9949-11e7-9d2b-28effef3396f.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master, so closing this issue.

![finally-keyword](https://user-images.githubusercontent.com/13446645/32541511-e4a90128-c495-11e7-9dff-d86787a6e183.png)
