### ISSUE TITLE
Try-catch cannot be properly formatted

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3078]
Pack 0.93 13/09

**Steps**
1. Add a main function
2. Add a try-catch
3. Add a finally block
4. Switch to the source view and reformat the code

**Issue**
Try-catch will not be properly formatted
![try1](https://user-images.githubusercontent.com/1845370/30430531-25789c92-9979-11e7-95fe-55b927bd1d19.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed.
![try-catch-format](https://user-images.githubusercontent.com/13446645/32583436-97c01386-c519-11e7-91ff-af30007e18dc.png)
