### ISSUE TITLE
Indicate syntax errors in the design and source view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3079]
Syntax errors should be marked in the design and source view to indicate there is an error without waiting till the user compiles the code

![syntx2](https://user-images.githubusercontent.com/1845370/30467423-04da4d44-9a02-11e7-934d-f446294b9539.png)

![syntx3](https://user-images.githubusercontent.com/1845370/30467427-0a5fd252-9a02-11e7-9707-e7fc44e60375.png)

**Comment by NatashaWso2** [comment]
This issue is fixed in the latest master with #4225 and #4237 

![semanticerrors](https://user-images.githubusercontent.com/13446645/32598665-5321a5ea-c560-11e7-95d4-5c9730c7c4c3.png)

So this issue can be closed
