### ISSUE TITLE
[Editor] Need to add correct syntax when initializing values to an array

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#309]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Feb 07, 2017 at 02:39 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1499_

----

1. Add a string array constant from the graphical view. Give an identifier and add the values.

Issue
First what I did was just adding values comma separated like apple,mango,grapes thinking that syntax {},`,"" will be added automatically.

For strings, we just need to add the value and the editor will automatically add "" for it. But its not the same for arrays. Need consistency with this regard and its easy for the user because they don't need to worry about the correct syntax

**Comment by nadeeshaan** [comment]
Currently we do not have different variable type representations at the design view level. This enhancement will be provided with the implementation of the expression editor

**Comment by nadeeshaan** [comment]
This issue has been addressed by embedding the expression editor to the statements. Hence closing the issue.
