### ISSUE TITLE
Switching does not happen when the icon on the tabs is clicked

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3093]
Pack - 0.93 (19/09)

Switching between design and source views does not happen when the icon on the tabs is clicked

![design](https://user-images.githubusercontent.com/1845370/30631343-850939b4-9e01-11e7-9722-234c1f927857.png)
![source](https://user-images.githubusercontent.com/1845370/30631355-8f8ecb10-9e01-11e7-8045-1eea861a61cb.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master so this issue can be closed.
