### ISSUE TITLE
Xml namespaces and comments cannot be preserved

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3106]
Pack 0.93 (19/09)

**Add the below code segment in the composer**
```
    xmlns "http://ballerina.com/";
    xmlns "http://ballerina.com/aa" as ns0;

    xml x2 = xml `<book ns0:status="available">
                    <ns0:name>Sherlock Holmes</ns0:name>
                    <author>Sir Arthur Conan Doyle</author>
                    <!--Price: $10-->
                  </book>`;
    system:println(x2);
```

**This will be shown like below in the design view**

![xml3](https://user-images.githubusercontent.com/1845370/30695263-323166cc-9ef5-11e7-8022-31d86e669ebe.png)

**Issues**
1. The comment is missing
2. The xml namespace in the element (book ns0:status="available") is missing

**Comment by NatashaWso2** [comment]
The xml namespace and comments given in the source view are preserved and is shown in the design view as follows:
![xml](https://user-images.githubusercontent.com/13446645/33058127-1cf0494c-ceb4-11e7-9fe5-85f33a2c402a.png)

Since this is fixed in the latest master, this issue can be closed.
