### ISSUE TITLE
[Editor] Implement mScroller for all panes

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#311]
<a href="https://github.com/dakshika"><img src="https://avatars.githubusercontent.com/u/6497326?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dakshika](https://github.com/dakshika)**
_Tuesday Feb 07, 2017 at 04:36 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1502_

----

**Comment by nadeeshaan** [comment]
Closing based on the last comment
