### ISSUE TITLE
[Firefox] Split view is occupying more than half of the canvas by default

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3118]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7
Firefox

Split view is occupying more than half of the canvas by default 
![splitview1](https://user-images.githubusercontent.com/1845370/30736817-e25027b2-9fa1-11e7-8f2a-57b787f0df55.png)

**Comment by hemikak** [comment]
Fixed
