### ISSUE TITLE
[Firefox] No close button for tabs

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3119]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7
Firefox

No close button for tabs, so cannot close tabs
![close](https://user-images.githubusercontent.com/1845370/30736999-98241ea4-9fa2-11e7-9727-c59cd05aaa65.png)

**Comment by keizer619** [comment]
This is visible in  0.94-pre-release pack hence closing this issue
