### ISSUE TITLE
Issues in the project explorer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3121]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

- [x] Issue 1 - Missing tool tips
![tooltip1](https://user-images.githubusercontent.com/1845370/30737896-cd0ee318-9f77-11e7-87fb-0f582264e6bd.png)

- [x] Issue 2 - The delete and refresh icons of the folder will be removed when one of the directory is selected
![icon2](https://user-images.githubusercontent.com/1845370/30738104-9a6def1a-9fa6-11e7-80cf-5efb3cbda58a.png)

- [x] Issue  3 - Cannot delete a folder

- [x] Issue 4 - Cannot open a directory by copy pasting the path directly without selecting it from the tree structure

- [x] Issue 5 - Cannot add a new file to a newly created sub directory

- [x] Issue 6 - Cannot add a new folder to a newly created sub directory

- [x] Issue 7 - Cannot rename and deleted a newly created sub directory

- [x] Issue 8 - Cannot delete a newly added file

- [x] Issue 9 - Cannot open a file in the editor

- [x] Improvement 10 - The previous name should be visible to the user when renaming a file/folder

- [x] Issue 11 - Refresh after adding a file and folder does not show the newly added files

- [x] Issue 12 - Disable the option to open a file in the editor if it is not a bal file

**Comment by kaviththiranga** [comment]
Added tool tips to explorer root actions with 2d68ba20af94cf74f73596bc1f46822b5a803263.

Other issues were found on a head with unfinished work on explorer and no longer reproducible.
