### ISSUE TITLE
No option to go to the source view or completely move to design view when the split view is opened

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3124]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

No option to go to the source view or completely move to design view when the split view is opened. The user has to close the tab and then move to either design or source view

**Comment by hemikak** [comment]
This behavior was followed similar to VSCode.

**Comment by hevayo** [comment]
We have provide a button to close split view with 0.94
