### ISSUE TITLE
The scroll bar is separating from the split view 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3126]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

The scroll bar is separating from the view when it is moved quickly
![split3](https://user-images.githubusercontent.com/1845370/30741943-99892a66-9fb4-11e7-8973-e48871866a1f.png)

**Comment by hevayo** [comment]
Fixed in 0.94.0-M1
