### ISSUE TITLE
Issues in the Menus

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3127]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

Issue 1 - The Preferences are not working

Issue 2  - Undo and Redo are not working

Issue 3 - When the Welcome page is selected from the Help menu the page will be opened, but the user is not directed to the page

**Comment by hevayo** [comment]
Issue 1 is captured in https://github.com/ballerinalang/composer/issues/3679

issue 2 & issue 3 are fixed in 0.94
