### ISSUE TITLE
The console should be minimized when the collapse button is clicked

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3129]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

The console should be minimized when the collapse button is clicked. Currently, the height is adjusted to 2 levels which is not required since we can adjust the height by drag and drop.
![con3](https://user-images.githubusercontent.com/1845370/30743973-9686c1b2-9fbd-11e7-84fe-4548c0068d40.png)

![coll1](https://user-images.githubusercontent.com/1845370/30743942-6ba94d70-9fbd-11e7-8e2e-230f919b15df.png)

**Comment by hevayo** [comment]
This is the expected behavior where close is used to hide the console and "^" is used to maximize the console.
