### ISSUE TITLE
[Firefox] Console and Try-it is covered by the project explorer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3130]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

**Steps**
1. Close the console if open
2. Expand the project explorer
3. Toggle button panel to open the console

**Issue**
The Console and Try-it is covered by the project explorer. When you collapse the project explorer, you will see the console

**Comment by hevayo** [comment]
No longer reproducible.
