### ISSUE TITLE
Issues when closing and adjusting the height of the console

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3131]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

Issue 1: The tool pallet will be limited up to the area where the console was when the console is removed.
![con5](https://user-images.githubusercontent.com/1845370/30744625-9101ab1e-9fc0-11e7-9804-c2928c72ced5.png)

Issue 2: The height is adjusted it takes time to render the elements and code
![console1](https://user-images.githubusercontent.com/1845370/30744702-f2f7231c-9fc0-11e7-81dd-5540be544493.png)

**Comment by hevayo** [comment]
Fixed in HEAD
