### ISSUE TITLE
Issues with the debug menu

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3136]
Pack  - 809e1059ea629ab06d43ef1442a7a05bc5b272d7

Issue 1 - The debug menu should be renamed as Run and have both run and debug options just like in IDEA. So, Stop debug option is also not required.
![debug2](https://user-images.githubusercontent.com/1845370/30746534-a9c67a06-9fc7-11e7-8aac-8799447916a9.png)

Issue 2 - In the left pane, "Run with debugging" should be changed to only "Debug"
![debug1](https://user-images.githubusercontent.com/1845370/30746531-a564b2f2-9fc7-11e7-80f8-3b5b2ffa0863.png)

**Comment by hevayo** [comment]
Fixed in 0.94
