### ISSUE TITLE
[Editor][Improvement] Suggesting data types when user adds variable definitions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#315]
<a href="https://github.com/chaminda"><img src="https://avatars.githubusercontent.com/u/7115693?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chaminda](https://github.com/chaminda)**
_Tuesday Feb 07, 2017 at 05:44 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1510_

----

Better if we can at least listing available data types when we add variable definitions from the editor. Maybe like the way of defining arguments in the editor.
if we can easily handle this, for the time being, It's bit user-friendly than the current implementation of it,

**Comment by maheeka** [comment]
At the moment we provide following support : 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/1029806/27429009-64e2c740-5761-11e7-8887-062124589675.png">

Need to enhance with language server implementation.

**Comment by NipunaMarcus** [comment]
This will be tracked from the language server new implementation progress.
