### ISSUE TITLE
Enable search option

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#316]
<a href="https://github.com/srsharon"><img src="https://avatars.githubusercontent.com/u/10986966?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Tuesday Feb 07, 2017 at 06:27 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1511_

----

![image](https://cloud.githubusercontent.com/assets/10986966/22680126/7e4bbb32-ed2c-11e6-8e66-470c9e26f204.png)

**Comment by hevayo** [comment]
will be implement in 0.88
