### ISSUE TITLE
The breadcrumb does not change when you save an already saved file in a different location

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3168]
**Steps**
1. Open a already saved file
2. Save the file in a new location 

**Issue**
The breadcrumb will show the previous/old location even though the new file is opened. It will update the breadcrumb only when the user shift to another tab and return again

**Comment by NatashaWso2** [comment]
Breadcrumb was removed from the composer by design in the latest master, hence this is no longer valid.
So this issue can be closed.
