### ISSUE TITLE
[Intermittent] Network error when trying to save a service

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3194]
Release 0.93

This error is observed when a change is made to the service and try to save the file

![networkerrorcloud](https://user-images.githubusercontent.com/1845370/30919621-9408a166-a3bf-11e7-8ffc-8b0ccfd5944a.png)

**Comment by NatashaWso2** [comment]
This cannot be reproduced in the latest master, hence closing this issue.
