### ISSUE TITLE
Write a parser for Editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#325]
<a href="https://github.com/uthaiyashankar"><img src="https://avatars.githubusercontent.com/u/2410076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [uthaiyashankar](https://github.com/uthaiyashankar)**
_Tuesday Feb 07, 2017 at 11:14 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1538_

----

We are depending on backend parser for the editor at the moment. The syntax restrictions are high due to that. For example, having an empty function is not allowed by the language restriction, but the editor should be able to render it and let user to edit. 

#893 is related.

**Comment by kaviththiranga** [comment]
We are no longer on this path. We are using custom error handling strategies with the same parser  bypass runtime restrictions.
