### ISSUE TITLE
[Editor] Cannot change the source of the struct once it is selected in the type mapper

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#327]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Feb 07, 2017 at 11:34 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1541_

----

1. Add two structs. Enter values
2. Add a type mapper
3. Select the structs for the source and target
4. Once you select the source and target, try to interchange the two

Issue
cannot change the sources once it is selected

**Comment by sumuditha-viraj** [comment]
This is fixed.
