### ISSUE TITLE
Use of the two cancel buttons in the swagger view is not clear

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3286]
Two cancel buttons which confuses the user. Does not indicate which cancel button cancels what.

![cancel](https://user-images.githubusercontent.com/1845370/31176108-4b2f4678-a92f-11e7-9a07-5c8ce6aaeb11.png)

**Comment by hemikak** [comment]
This is the behaviour of the swagger-ui(http://petstore.swagger.io/).

The above state is reached when clicking the try-it of the swagger-ui. Swagger try-it will be removed and the composer's try-it should be used.
