### ISSUE TITLE
[Editor] Updating the struct will not update the type mapper

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#329]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Feb 07, 2017 at 11:48 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1544_

----

1. Add two structs. Enter values
2. Add a type mapper
3. Select the source and target in the type mapper
4. Change the identifier name in one of the elements in a struct
5. Add a new element to one of the structs

Issue
Changes made in step 4 and 5 will not be reflected in the type mapper.

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing
