### ISSUE TITLE
Type conversions are not working in the type mapper

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#330]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Feb 07, 2017 at 12:06 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1549_

----

1. Add a structs and add values of below types
int, float, long, boolean
2. Add another struct and add values of below types
long, double
3. Add a type mapper and select first struct to the source and the other as the target
4. Try to map the following
boolean -> int/long/float/double
int -> long/float/double
long -> double
float -> double

Issue
All above conversions cannot be done from the type mapper

**Comment by maheeka** [comment]
Also reported at https://github.com/ballerinalang/composer/issues/2290 with implementation details. Hence closing.
