### ISSUE TITLE
Close icon size and text sizes are mismatching

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3345]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, the close icon size and the text size for "Console" is mismatching. This results in a visual ambiguity for the person who is using composer. 

![composer_console](https://user-images.githubusercontent.com/15624590/31325780-85489ca8-acde-11e7-9faa-35f87e0cb36b.png)

**Comment by hevayo** [comment]
implementation differed
