### ISSUE TITLE
Disable save button till a file name is entered

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3349]
Version: 0.93
Browser: Version 61.0.3163.100

Currently the save button is enabled at all times and a validation occurs at end if the save is pressed without the file name, it's better to disable the save button until a file name is entered which will indicate that it is mandatory

![composer_saveas](https://user-images.githubusercontent.com/15624590/31326059-7d8afbac-ace1-11e7-8c2d-e18bdf62ccb3.png)

**Comment by dakshika** [comment]
fixed in latest master
