### ISSUE TITLE
[Editor] Cannot create an object from the editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#335]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Feb 07, 2017 at 13:21 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1557_

----

1. Add the below code from the source view or draw it in the graphical view

import ballerina.lang.system;
type person {
	string name;
	int age;
	
}
function main(string [] args) {
	person p1 = new person();
	p1.name = "Dilini";
	
}

2. Switch between the source and graphical view

Issue
The code will be adjusted as below.

function main(string [] args) {
	person();
	 = "Dilini";
	
}

**Comment by nadeeshaan** [comment]
This syntax for type has been changed and now the struct is the syntax and syntax person _p1 = new person();_ has also been changed. Hence closing
