### ISSUE TITLE
No tool tips for if/while condtions which do not show the full content

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3357]
No tool tips for if/while condtions which do not show the full content. Only statements have tool-tips for such scenarios

![tooltip3](https://user-images.githubusercontent.com/1845370/31326953-52e390b4-ace9-11e7-9077-61350e1de406.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master so this issue can be closed
![if condition](https://user-images.githubusercontent.com/13446645/32542454-b104a572-c498-11e7-81db-1f6746a7a15f.png)
