### ISSUE TITLE
Add variable placeholder

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3366]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, currently the place holder is shown as "Add variable" rather than having this string, from the user's perspective its better to provide an indication of the syntax of adding a new variable. 
Hence a placeholder similar to "<type><variable name> = <value>" will have more value than the current "Add variable" placeholder

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
