### ISSUE TITLE
Add placeholders for all the properties in the annotations

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3371]
Add placeholders for all the properties in the annotations so that the user knows what to enter and the format to enter.

eg: for path property - add the path with a slash in front
![path2](https://user-images.githubusercontent.com/1845370/31331058-8a6f58d2-acfe-11e7-956c-b1f906f7443a.png)
![cons](https://user-images.githubusercontent.com/1845370/31331049-83c19cb6-acfe-11e7-80c6-3d8d564da128.png)

**Comment by NatashaWso2** [comment]
Referred this issue in #2100, hence closing this issue.
