### ISSUE TITLE
Leave a definite space for characters before a ux component to ensure proper alignment

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3373]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, due to spacing problems in the ux component, the particular section looks disorted as there is broken alignment of "X" icon. This should be corrected as this will effect the neatness in the UI which will leave an impression in a user's mind

![composer_resource_1](https://user-images.githubusercontent.com/15624590/31333066-58fe8aea-ad06-11e7-868d-2110061d8d05.png)

**Comment by dakshika** [comment]
This has been improved in latest master. Now we are showing close and add an option on hover. Closing the issue due to latest changes please verify and reopen if we need to do further improvements
