### ISSUE TITLE
Errors are dissapearing before the user can read them

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3374]
If a long error occurs it disappears before we can completely read it. Can we let the user close the error or maybe if the user is hovering over the error keep the error till the pointer is moved away. 

![screenshot from 2017-10-09 15-23-56](https://user-images.githubusercontent.com/7681361/31333243-eba21344-ad06-11e7-81a1-79b5669814ba.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
