### ISSUE TITLE
[UX] Rename 'Open File Explorer' to 'Show File Explorer'

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/composer#3375]
IMO, the existing 'Open File Explorer' button is quite misleading. I expected it to open a file explorer as a new window (similar to 'Open Program Directory' window). IMO better to reword it as 'Show File Explorer', 'Toggle File Explorer' or just 'File Explorer'.

**Comment by NatashaWso2** [comment]
The button is renamed as 'Explorer' in the latest master, hence this issue can be closed.
