### ISSUE TITLE
No suggestions or autocomplete for resource level annotations

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3376]
Can we add autocomplete and suggestions for resource level annotations? Maybe we can have a static list for this since we already know what are parameters that can be passed to a resource. 

` resource statusCodeResource (message m, @http:PathParam {value:"code"} string codeValue, @http:QueryParam {value:"withbody"}string withbody)`

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
