### ISSUE TITLE
Tool tip for variable

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3377]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

Currently the tool tip for variable contains an explanation as given in the attached image. This is confusing. It's better to have a simple wording and it's very important to keep a general pattern when giving tool tips. 

E.g. `Statement that can be added and interspersed in any order. Can be used anywhere in code`

![composer_variable_tooltip](https://user-images.githubusercontent.com/15624590/31333478-dc0457e8-ad07-11e7-93f8-765a754c16ce.png)

**Comment by samgnaniah** [comment]
Suggested text: "Variables are statements that can be added and positioned in any order."
