### ISSUE TITLE
Suggestions are not correctly given

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3380]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

Please see the attached image. When the string "js" is typed, ideally it should suggest wordings that go with the pattern "js" but as shown in the image, the suggested list contains "jms" as well. The suggestions should not be just a character match but a pattern match. The current design degrades user experience.

![composer_suggestion_variable](https://user-images.githubusercontent.com/15624590/31334356-9ffa7062-ad0b-11e7-9be1-595ab3422407.png)

**Comment by hevayo** [comment]
Implementation has differed we will no longer has statement boxes from 0.95.6
