### ISSUE TITLE
Delete button of the action invocations are not prominent to the user

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3381]
It is visible only when you hover over the exact location of the delete button and it is not prominent to the user
![delete](https://user-images.githubusercontent.com/1845370/31334644-bc8dfaa4-ad0c-11e7-8196-8213e6ad2bde.png)

**Comment by NatashaWso2** [comment]
With the new design we don't allow the user to manually draw the action invocation arrow. Instead the user can select the endpoint which the action invocation needs to be drawn by selecting from the drop down given after clicking on the arrow head. 
![action-invocation-endpoints](https://user-images.githubusercontent.com/13446645/33198539-a8855b00-d111-11e7-8aa7-96fc7e75fe8a.png)

It is mandatory for the user to draw the action invocation arrow from the action invocation to the endpoint by selecting an endpoint from the list given, hence the delete button for the action invocation arrow is not given in the latest master.
