### ISSUE TITLE
No suggestions/autocomplete for function parameters

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3383]
Affected version: 0.93

Please refer the screenshot.

![screenshot from 2017-10-09 16-25-45](https://user-images.githubusercontent.com/7681361/31335073-9682efde-ad0e-11e7-89b6-a23abbc57280.png)

**Comment by NatashaWso2** [comment]
Suggestions are given for function parameters in the latest master.
![function-arguments](https://user-images.githubusercontent.com/13446645/32934310-a0d4eb58-cb91-11e7-8df0-a071dcc62631.png)

So this issue can be closed.
