### ISSUE TITLE
JMS sample file is not rendered properly

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/composer#3385]
Steps to reproduce: 
- Go to composer welcome page and select 'JMS' sample.
- On the File Explorer, double click on 'jmsSender.bal' file. 
- It is not rendered properly. See screenshot below:

![jmssender_bal](https://user-images.githubusercontent.com/7592890/31335389-00371436-ad10-11e7-9554-489be559e2d8.png)

Furthermore, although I can see the design view (with empty canvas), It shows 'Design View' button to toggle into the design view.

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
