### ISSUE TITLE
File is created without .bal when created through directory structure component

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3393]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

**Steps**
1. Open an existing directory structure
2. Right click on the directory name and choose "New file"
3. In the dialog enter a file name to be created
4. Click create

**Actual behaviour**
As shown in the below images, the file is created without the .bal extension. 

![composer_directory_1](https://user-images.githubusercontent.com/15624590/31338083-a1db5d5a-ad1b-11e7-8b6d-f309f862428a.png)

![composer_directory_2](https://user-images.githubusercontent.com/15624590/31338082-a1d8f448-ad1b-11e7-9fd6-5e77b61d9260.png)

**Expected behaviour**
The file should be created and saved with .bal extension

**Comment by NatashaWso2** [comment]
Fixed in the latest master 4c1b6e32de8f7ab83b0ae21641464c8582a3e285
