### ISSUE TITLE
Breadcrumb is not working

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/composer#3399]
Open JMS sample (which appears on the welcome page) on the composer. This will show a breadcrumb as below:

![breadcrumb](https://user-images.githubusercontent.com/7592890/31339151-92ed577c-ad1f-11e7-9b9d-df6ef5bd4b0a.png)

If I click on 'samples', I expect it to take me to the samples page. Right now, it is clickable, yet does not do anything.

**Comment by NatashaWso2** [comment]
Breadcrumb was removed from the composer by design in the latest master, hence this is no longer valid.
So this issue can be closed.
