### ISSUE TITLE
Soap connector - displays only constructSoapRequest function

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3412]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, currently only the constructSoapRequest function is displayed. According to [1] there is an additional send function as well.

[1] https://github.com/ballerinalang/connectors/blob/master/soap/src/org/wso2/ballerina/connectors/soap/soapConnector.bal

**Comment by NatashaWso2** [comment]
Soap connector is still under implementation so it will not be shown in the tool palette under the Connectors section, hence this issue can be closed.
