### ISSUE TITLE
Rename undo and redo labels as current wording is too long

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3418]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, currently the undo and redo options in the main menu contains very long texts. Rather a simple wording of <control name> <short cut key> would be enough

e.g. Undo Ctrl+z

![composer_undoredo](https://user-images.githubusercontent.com/15624590/31346941-5e4627f6-ad38-11e7-929e-82eff227a001.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 549fb26
