### ISSUE TITLE
[UX] Drop down does not get picked up back when clicking else where

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/composer#3421]
Following drop down menu does not get picked up when clicking else where on the composer window. Due to this, user has to go and click the drop down arrow again to pick it up. Usually, drop down menus get picked up when clicking else where. 

I would suggest this to be fixed to improve UX.

![drop-down](https://user-images.githubusercontent.com/7592890/31347239-50dc01b6-ad39-11e7-922e-5d20aaac9a78.png)

**Comment by dakshika** [comment]
New composer runs without any selection. hence this issue is no longer valid.
