### ISSUE TITLE
Style inconsistency in Stop Button

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3422]
It's better if we can keep a similar consistency in styling. Also, there should be a space between the square icon and the "Stop" text.

![screenshot from 2017-10-09 21-32-53](https://user-images.githubusercontent.com/7681361/31347343-a53a9100-ad39-11e7-8dc5-b1d4ab6e5b3e.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 549fb26fd56776d8885e971fe37dec5d56852529
