### ISSUE TITLE
The Stop Icon has a drop down arrow which doesn't provide any functionality

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3425]
The Stop Icon has a drop-down arrow which doesn't provide any functionality. This is confusing to the user and accidental clicks will stop the service. 

![screenshot from 2017-10-09 21-37-04](https://user-images.githubusercontent.com/7681361/31347568-6337bf52-ad3a-11e7-82e5-5ed366b1506c.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 549fb26fd56776d8885e971fe37dec5d56852529
