### ISSUE TITLE
Maintain same label for creating a new ballerina file

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3429]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, the shortcut menu contains label for creating a new ballerina file as "New Ballerina File" but in other menus this is shown as "New" and "New File". Please maintain a common label for creating new ballerina service at all points

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed
