### ISSUE TITLE
The content assistance/auto completion does not work when there are issues in the code

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3436]
The content assistance/auto completion does not work when there are issues in the code

**Comment by NatashaWso2** [comment]
In the latest master even if there are semantic errors in the code, suggestions/auto completion works fine.
![suggestions-with-errrors](https://user-images.githubusercontent.com/13446645/32938315-d4a6156e-cba1-11e7-8202-b4473f7c1d99.png)

hence this issue can be closed.
