### ISSUE TITLE
.bal extension is not added automatically when a new file is added through the file explorer

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3438]
Affected Version: 0.93

![screenshot from 2017-10-10 10-45-47](https://user-images.githubusercontent.com/7681361/31370646-1647bc0e-adaa-11e7-968f-dc1d5e95e471.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 549fb26fd56776d8885e971fe37dec5d56852529
