### ISSUE TITLE
FTP service is shown as file as opposed to sample in Ballerina by example

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3439]
Version 0.93
Browser: Chrome Version 61.0.3163.100 

As shown in the attached image, for ftp service the configuration of service is shown as <file>. But in [1] it's shown as <ftp>.

![composer_ftpconnector](https://user-images.githubusercontent.com/15624590/31370700-6f9547ae-adaa-11e7-805f-026b007c9ba7.png)

[1] https://ballerinalang.org/docs/by-example/ftp-server-connector

**Comment by erandidesilva** [comment]
Current syntax generates the following compilation error. Hence increasing the priority as blocker
```FileConnector.bal:14: undefined package name 'file' in 'file' ```

**Comment by hevayo** [comment]
Fixed in 0.95.1
