### ISSUE TITLE
Issues in the read me related to the version of the ballerina tools distribution

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3441]
It says "target/ballerina-tools-0.8.2.zip" in the readme of 0.93 release 

Building from the source
============================

If you want to build Ballerina Tools from the source code:

1. Get a clone or download the source from this repository (https://github.com/ballerinalang/distribution).
2. Run the following Maven command from the root Ballerina Tools directory: mvn clean install
3. Extract the Ballerina Tools distribution created at **`target/ballerina-tools-0.8.2.zip`** to your local directory.

**Comment by dilinisg** [comment]
This is in the README file of the ballerina-tools distribution

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
