### ISSUE TITLE
Inconsistent error messages when invalid params are entered

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3447]
Error when path/query params are partially entered
![path-query](https://user-images.githubusercontent.com/1845370/31373558-295b53b0-adb8-11e7-98c7-e9e189d1c018.png)

Error when a data type is partially entered
![length](https://user-images.githubusercontent.com/1845370/31373750-dcb088a4-adb8-11e7-8538-8db97bc5d3b6.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
