### ISSUE TITLE
Dynamic Tool Palette Issues

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#345]
<a href="https://github.com/maheeka"><img src="https://avatars.githubusercontent.com/u/1029806?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Tuesday Feb 07, 2017 at 15:50 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1576_

----

Tool Palette does not get updated for 
- [x] Function Delete
- [x] Function Rename
- [x] Connector Delete
- [x] Connector Rename
- [x] Connector Action Delete
- [x] Connector Action Rename
Also
- [x] Do not add main function to tool-palette
- [ ] Function return update should change the tool-palette node type

**Comment by nadeeshaan** [comment]
Last point has to be addressed as an enhancement. This has been tracked with #1307 and hence closing
