### ISSUE TITLE
Content Assist doesn't work for import key word

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3450]
![screenshot from 2017-10-10 13-46-23](https://user-images.githubusercontent.com/7681361/31376185-b52f33e4-adc1-11e7-8145-15472ba736b5.png)

**Comment by NatashaWso2** [comment]
Suggestions are given for the import key word in the latest master, hence closing this issue.
![import-keyword](https://user-images.githubusercontent.com/13446645/32929595-1918a8ec-cb7f-11e7-85f2-fe6af4487c34.png)
