### ISSUE TITLE
Suggestions are not available for functions in the packages

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3454]
Write messages: and pres ctrl+space. No suggestions given

**Comment by NatashaWso2** [comment]
Suggestions are provided for functions in the packages as below: 
![functions-packages](https://user-images.githubusercontent.com/13446645/32960574-63ef07b4-cbeb-11e7-9ce2-3e5021b35632.png)

Since this is fixed in the latest master, this issue can be closed.
