### ISSUE TITLE
Can add duplicate global variable names

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3460]
Affected version: 0.93

![screenshot from 2017-10-10 15-19-50](https://user-images.githubusercontent.com/7681361/31380316-add6c348-adce-11e7-865e-f8b104aa916b.png)

**Comment by NatashaWso2** [comment]
When global variables with the same name are added more than once, it will be added and an error would be shown to the user in the design view stating that the variable name is already re-declared.
![duplicateglobals](https://user-images.githubusercontent.com/13446645/32508229-a8c7907e-c40f-11e7-8946-238c4fff6461.png)
