### ISSUE TITLE
Rewording required: Warning! Are you sure you want to delete selected file?

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3467]
This should be changed to Warning! Are you sure you want to delete **the** selected file?
![the](https://user-images.githubusercontent.com/1845370/31384787-22d9b240-adde-11e7-82b5-d42ed15acce5.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 549fb26fd56776d8885e971fe37dec5d56852529
![delete](https://user-images.githubusercontent.com/13446645/32507089-89de29dc-c40c-11e7-8659-8017572b5fda.png)
