### ISSUE TITLE
Focus in directory structure retains in several places

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3472]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, when the focus is on a particular place in the structure, eventhough some other point is selected, then the previous focused directory element is not unfocused. Both directory elements are focused in the same time

![composer_focus](https://user-images.githubusercontent.com/15624590/31383748-cf78afba-add9-11e7-83a2-8ce3bb5fe85f.png)

**Comment by dakshika** [comment]
this is fixed in latest master
