### ISSUE TITLE
No auto completion support for user defined functions

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3475]
Release 0.93

1. Create a function.
2. Call the function in another place. Try to use auto completion support.

**Issue**
No auto completion support for user defined functions

**Comment by NatashaWso2** [comment]
Suggestions are given for user-defined functions in the latest master as below:
![user-defined-func-suggestions](https://user-images.githubusercontent.com/13446645/33017103-108321cc-ce17-11e7-8ebf-f98bdc2a644f.png)

Hence this issue can be closed.
