### ISSUE TITLE
[UX] Cannot create new folder in 'Save File' file browser window

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/composer#3476]
It would be better if the 'Save File' file browser allows to create new folders by right clicking on the folders on the file browser window itself. As this is not supported, users have to create folders first and then again try this action. 

![save-file](https://user-images.githubusercontent.com/7592890/31385148-b254b9dc-addf-11e7-8bf6-6ef5ab1cacef.png)

**Comment by NatashaWso2** [comment]
This issue is included in #4306, hence this issue can be closed.
