### ISSUE TITLE
How to add services other than http in design view?

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/composer#3479]
It was not clear how to add a JMS service from the composer. I could only find 'http' service on the palette. 

![http-service](https://user-images.githubusercontent.com/7592890/31386654-30ef2a02-ade5-11e7-8d0d-81420a9e06a8.png)

In addition to this, found connectors section on the palette, but cannot add a JMS service using those.

Finally, I ended up writing a JMS service using the source view.

**Comment by hevayo** [comment]
Implementation has differed we will have a service for each transport with 0.94.0.
