### ISSUE TITLE
Swagger for sample "ContentBasedRoutingServices"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3481]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

When a response is tried out using Swagger console for RoutingServices 405 returned. Please see attached image

Payload : ```{"name" : "nyse"}``` [1] 

![composer_swagger](https://user-images.githubusercontent.com/15624590/31388689-6e4f0a46-adec-11e7-9224-fb7563d7d02e.png)

[1] Please see the attached readme for payloads which is shipped with the pack
[README.txt](https://github.com/ballerinalang/composer/files/1372027/README.txt)

**Comment by hemikak** [comment]
The swagger try-it is now disabled. Instead have to use the composer's try-it feature.
