### ISSUE TITLE
Run and debug drop downs doesn't get cleared when mouse clicked else where in composer

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3482]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the image, when the run and the debug menus are expanded from the icon panel, they don't get minimized unless clicked on the minimize button. The other drop down menus get minimized when a mouse event is triggered else where in composer

![composer_run_menu](https://user-images.githubusercontent.com/15624590/31389532-e786b632-adee-11e7-8a95-3f2f94dbde3a.png)

**Comment by dakshika** [comment]
no longer valid with latest design
