### ISSUE TITLE
Run side icon has to be clicked twice for the menu to be opened when redeployed or stopped

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3489]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

**Steps**
1. Run a service
2. Go to run icon in the left side panel
3. Redeploy or stop the service

**Actual behaviour**
The left side panel minimizes. In order to get the panel again, should click twice on the icon

**Expected behaviour**
The left side panel should not minimize. If minimized, then it should be expanded from a single click

**Comment by dakshika** [comment]
cannot reproduce in latest master, hence closing the issue
