### ISSUE TITLE
[Editor][Improvement] Provide drop-down for Method annotation of a resource.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#349]
<a href="https://github.com/chaminda"><img src="https://avatars.githubusercontent.com/u/7115693?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chaminda](https://github.com/chaminda)**
_Wednesday Feb 08, 2017 at 04:20 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1597_

----

It's nice to have a drop down to select the HTTP method annotation for a resource of a service.

**Comment by hevayo** [comment]
Implementation has changed, we only allow one method for one resource also the annotation UI has changed where user is suggested with a drop down list of possible annotations.
