### ISSUE TITLE
Action box appears on Connector thread as well

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3491]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

Please see the attached image. Action box should not appear for connector thread start and end boxes.

![composer_debugoncon](https://user-images.githubusercontent.com/15624590/31396489-28ff8f00-ae01-11e7-86d7-babdabe458c2.png)

**Comment by NatashaWso2** [comment]
We should have the action box for the endpoint so that we could delete it and jump to its source. Since this is the expected behavior, this issue can be closed.
