### ISSUE TITLE
Transform temp variables cannot be edited

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3499]
Release 0.93

![trans1](https://user-images.githubusercontent.com/1845370/31427467-04018d6e-ae85-11e7-8506-e3e7dec23390.png)

After edit:
![trans2](https://user-images.githubusercontent.com/1845370/31427471-090a6b8c-ae85-11e7-8a34-d38d4b28dc20.png)

**Comment by roonyh** [comment]
This is fixed in 0.95. We have a a better UI for this now. [](https://user-images.githubusercontent.com/3872221/32872393-85ea56ce-caac-11e7-8104-c1e467a4002e.png)
