### ISSUE TITLE
Added temp variables are not preserved in the transform view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3501]
Release 0.93

Added temp variables are not preserved in the transform view, but in the code
![trans4](https://user-images.githubusercontent.com/1845370/31427800-2e7407ec-ae86-11e7-837d-c5ef728d0909.png)

![trans5](https://user-images.githubusercontent.com/1845370/31427802-30dd2ef0-ae86-11e7-8c0d-6fd1c43bb98d.png)

**Comment by keizer619** [comment]
This issue is fixed in following PR
https://github.com/ballerinalang/ballerina/pull/3603/
