### ISSUE TITLE
Can add duplicate structs

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3505]
Affected Version: 0.93
![screenshot from 2017-10-11 13-52-43](https://user-images.githubusercontent.com/7681361/31429414-982e8db0-ae8b-11e7-881a-b01732c569ba.png)

**Comment by NatashaWso2** [comment]
If the Structs are dragged to the canvas from the tool palette, the names of the Structs would be unique as they would be incremented. If a user adds another Struct from the source view with the same name, an error would be shown both in the source and design view stating that a Struct with that name already exists.
