### ISSUE TITLE
Incorrect error given when keywords are used as variable names

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3506]
Affected Version: 0.93

![screenshot from 2017-10-11 14-21-00](https://user-images.githubusercontent.com/7681361/31430799-98083904-ae8f-11e7-997e-5cd0045b5292.png)

**Comment by NatashaWso2** [comment]
The error message shown is the actual error message triggered by the compiler according to the grammar, so this is the excepted error, hence this issue can be closed.
