### ISSUE TITLE
Cannot copy code from the source view by right clicking

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3508]
It seems the copy option is disabled. Any specific reason for this?

Affected version: 0.93
Chrome: 58.0.3029.110
![screenshot from 2017-10-11 14-29-49](https://user-images.githubusercontent.com/7681361/31431290-df65d4d6-ae90-11e7-8171-5a3e3de4ceaf.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master
![copy-code](https://user-images.githubusercontent.com/13446645/32930626-c53d44ce-cb85-11e7-8170-253cebf314b0.png)

Hence this issue can be closed
