### ISSUE TITLE
Formatting issues when properties are added inside resource config

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3524]
1. Wrong indentation
2. Comma in the next line

![comma](https://user-images.githubusercontent.com/1845370/31443496-433771b0-aeb7-11e7-83ad-54898b76a122.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed. 
![indentation](https://user-images.githubusercontent.com/13446645/33159793-951ad07a-d03c-11e7-973a-6bd5190d9c5d.png)
