### ISSUE TITLE
[Editor] UI issue - drag and drop a worker 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#353]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Wednesday Feb 08, 2017 at 07:46 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1609_

----

Build from master 8-Feb; Using chrome 55.0; 
drag and drop a worker in side a function gives below issue

![worker1](https://cloud.githubusercontent.com/assets/15671620/22727781/c25ecc5e-ee00-11e6-8ece-4595bf4b04ae.jpeg)

**Comment by nadeeshaan** [comment]
Issue is fixed in the latest (From 0.8 onwards), hence closing
