### ISSUE TITLE
Issue with adding send statement inside a try-catch

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#3555]
Try adding a "send" inside a try-catch

<img width="903" alt="screen shot 2017-10-12 at 8 29 54 am" src="https://user-images.githubusercontent.com/6814264/31477076-961cfbc8-af27-11e7-93f7-aafa2fc42639.png">

<img width="719" alt="screen shot 2017-10-12 at 8 30 34 am" src="https://user-images.githubusercontent.com/6814264/31477105-c1b61a9e-af27-11e7-8111-145f89bf754f.png">

**Comment by NatashaWso2** [comment]
Fixed in the latest master 549fb26fd56776d8885e971fe37dec5d56852529
