### ISSUE TITLE
Connectors does not properly place in the service and resource.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#357]
<a href="https://github.com/hemikak"><img src="https://avatars.githubusercontent.com/u/4398820?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hemikak](https://github.com/hemikak)**
_Wednesday Feb 08, 2017 at 08:44 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1616_

----

Add multiple connectors to the service and resource level. See attachment.
<img width="1226" alt="screen shot 2017-02-08 at 1 49 15 pm" src="https://cloud.githubusercontent.com/assets/4398820/22729468/e09039c6-ee08-11e6-9c6d-da0ad41613c9.png">

**Comment by nadeeshaan** [comment]
Fixed with #1264. Hence closing
