### ISSUE TITLE
Main function tool tip contains description as "undefined"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3583]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image for $subject

![com_0 94_tooltip_main](https://user-images.githubusercontent.com/15624590/31491184-142a227a-af64-11e7-9660-5fc96c8e2353.png)

**Comment by NatashaWso2** [comment]
Fixed with : #3701
