### ISSUE TITLE
Missing tool tips in Explorer panel

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3585]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image, tool tips are missing for the icons present in the explorer tab

![com_0 94_missingtooltip](https://user-images.githubusercontent.com/15624590/31491418-d7c4a5ac-af64-11e7-9948-004e2c64b735.png)

**Comment by kaviththiranga** [comment]
Fixed with Fixed with https://github.com/ballerinalang/composer/pull/3756
