### ISSUE TITLE
Message for Delete File/Folder should be changed

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3587]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image, following should be changed
1. Font size should be uniform in the message. Currently there are two font sizes
2. Entire file is there, just the file name will be enough.
2. Message should be changed to:
`"File <filename> will be deleted from file system. Do you want to continue?"`

![com_0 94_deletefilemsg](https://user-images.githubusercontent.com/15624590/31491823-44a82ecc-af66-11e7-9b00-01aec7d1729c.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 9938a9a298383b2f47f32dd7e697217df6841f87
