### ISSUE TITLE
Wrong wording in "Delete file/folder" message when trying to delete a folder

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3588]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. Here I am trying to delete a folder, but the wording (below) mentions it as file.

```
File /home/erandi/ballerina_0.9/composerTest/testFolder_1 will be deleted from file system.
Do you want to delete the file from file system?
```
![com_0 94_deletefolder](https://user-images.githubusercontent.com/15624590/31491965-c693ba82-af66-11e7-9652-1af25d330336.png)

**Comment by maheeka** [comment]
Fixed with https://github.com/maheeka/composer/commit/543258efbc9987a441cd6c1ab79fa5a25a3d9109

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed
![deletefolderpopup](https://user-images.githubusercontent.com/13446645/32656890-a1f764fa-c639-11e7-940b-3b5c0b647cf3.png)
