### ISSUE TITLE
Wrong text field added when adding configuration value from the http:configuration "Add attribute"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3594]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. When the attribute is added from the "Add attribute"  single quotes are added where as double quotes shouild be added.

Afer removing such attribute, the entire configuration becomes unusable. 

![composer_0 94_config_1](https://user-images.githubusercontent.com/15624590/31492533-10da3dda-af69-11e7-8835-4fb809d6f492.png)

**Comment by nadeeshaan** [comment]
This is due to the way it looks. please refer the below. Double quotes are added accordingly
![selection_117](https://user-images.githubusercontent.com/1329674/31614171-07c2324c-b2a3-11e7-880e-48472e4d6784.png)
