### ISSUE TITLE
No tool tips for the top menu

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3597]
**Environment**
Java 1.8
Browser: Chrome 58.0.3029.110 (64-bit)

![screenshot from 2017-10-12 16-22-41](https://user-images.githubusercontent.com/7681361/31492658-afb71ee6-af69-11e7-9a90-d1eb6488b5a5.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3756
