### ISSUE TITLE
Error when a mapping is deleted as the temp variable is not automatically defined correctly

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3602]
Need a space between var and variable name
![5](https://user-images.githubusercontent.com/1845370/31493228-e6b2f80a-af6b-11e7-8617-6ecbda790db7.png)

**Comment by maheeka** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3912/files by @manuranga

**Comment by manuranga** [comment]
also https://github.com/ballerinalang/ballerina/pull/3652 is needed for fully work.
