### ISSUE TITLE
Indentation issues when a mapping is added/deleted

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3604]
![6](https://user-images.githubusercontent.com/1845370/31493436-da7a7350-af6c-11e7-8d88-fda6840ea795.PNG)

![7](https://user-images.githubusercontent.com/1845370/31493442-e098b35a-af6c-11e7-94d3-584513e68b93.PNG)

**Comment by maheeka** [comment]
This is fixed with : https://github.com/ballerinalang/composer/pull/3818
