### ISSUE TITLE
Mappings are not deleted when the statements inside transform are deleted

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3606]
1. In the split view, delete all the statements inside the transform block

**Issue**
Mappings are not deleted when the statements inside transform are deleted

**Comment by maheeka** [comment]
@dilinisg Is there a specific sample where you observed this issue? We are not able to reproduce this.

**Comment by keizer619** [comment]
Cannot reproduce in 0.95 release, hence closing the issue.
