### ISSUE TITLE
Content assist not working for function arguments

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3609]
![screenshot from 2017-10-12 16-52-48](https://user-images.githubusercontent.com/7681361/31493727-05e1c538-af6e-11e7-8d14-4ab311373ccb.png)

**Comment by NatashaWso2** [comment]
Suggestions are given for function arguments. 
![function-arguments](https://user-images.githubusercontent.com/13446645/32929703-df72a6f0-cb7f-11e7-891a-29e79602fd2f.png)

Closing this issue since it is fixed in the latest master.
