### ISSUE TITLE
Correct "File Contains Unsaved Content" pop up

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3610]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. Following problems are there

1. Different font sizes. Font size should be uniform and standard
2. Heading: "File Contains Unsaved Content" should be corrected to "Warning" or a generic format.
3. Body: "Do you want to save the changes you made to TestService.bal? Your changes will be lost if you don't save them." should be something similar to: "Save changes to <filename> before closing? If you don't save, changes will be permanently lost "

![com_0 94_unsavedcontent](https://user-images.githubusercontent.com/15624590/31493817-6a516816-af6e-11e7-8d1c-3698610682f5.png)

**Comment by maheeka** [comment]
This is as per design. 
The same message dialog is given in VSCode.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/1029806/31663210-dfe48498-b35e-11e7-811b-edd4199b1677.png">
