### ISSUE TITLE
Cannot configure HTTP resource methods 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3617]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image for $subject.

![com_0 94_http_methods](https://user-images.githubusercontent.com/15624590/31494421-db46ecce-af70-11e7-8ea3-7ba5e47be6b3.png)

**Comment by kaviththiranga** [comment]
This is working in HEAD 0bc25ba8c26171016a6b1bb61a7ebce16d2ffd17

**Comment by hevayo** [comment]
Check in the HEAD and it works. Closing the issue please reopen if encountered again.
