### ISSUE TITLE
Old syntax is added when autocompleting a try-catch

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3619]
When you add a try-catch following is added.
```
try {  
} catch (errors:Error err)   
}
```
But the correct syntax is,

```
try {
} catch (error err) {  
}
```

**Comment by dilinisg** [comment]
Not fixed in the second pack for QA. When trying to correct the error, another message will be displayed saying it is a bug. Hence, reopening 

![55](https://user-images.githubusercontent.com/1845370/31625215-e0662832-b2c2-11e7-9c09-eaf3bb93c9ca.png)

**Comment by nadeeshaan** [comment]
Please check in the latest head. It's already fixed
