### ISSUE TITLE
Shifted to source view automatically when @http:configuration pop up is opened while editing attribute field 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3620]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add a http:configuration attribute
2. While keeping the value text box in edit mode (without any value), click <http>

View is automatically switched to source view

**Comment by NatashaWso2** [comment]
This cannot be reproduced in the latest master, so closing this issue
