### ISSUE TITLE
Invalid syntax generated for operations when the mappings are removed

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3621]
1. Add a "Add" binary operator
2. Map two variables for the input and also the output
3. Remove the two input mappings

**Issue**
Composer generates the code as u.age = "" -""; which gives an error.
![10](https://user-images.githubusercontent.com/1845370/31494677-0bdb2642-af72-11e7-921f-7c014df65306.png)

**Expected**
Make it `u.age =  0 - 0;`

**Comment by dilinisg** [comment]
Same for length of 
` u.age =  lengthof"";`

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced in the latest master, hence this issue can be closed.
