### ISSUE TITLE
Missing http:configuration attributes in Add attribute menu and @http:configuration menu

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3623]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

According to [1] sslEnabledProtocols and ciphers is missing (refer added image). 

[1] https://github.com/ballerinalang/ballerina/blob/rewrite-compiler/modules/ballerina-http/src/main/ballerina/ballerina/net/http/annotation.bal

![com_0 94_httpconfig](https://user-images.githubusercontent.com/15624590/31495002-583460d4-af73-11e7-8a72-1f8509d29018.png)

**Comment by nadeeshaan** [comment]
This has been fixed in the latest head 9fa55de2d575745b4166446feff8d5ad23b16591

![screenshot from 2017-10-17 01-40-33](https://user-images.githubusercontent.com/1329674/31633068-c5780dfa-b2dc-11e7-92b2-2085777d5930.png)
