### ISSUE TITLE
"operator '^' not defined for 'int' and 'int'" when "power" operator is added

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3624]
"operator '^' not defined for 'int' and 'int'" when "power" operator is added

**Comment by maheeka** [comment]
Power operator is deprecated now. You need to use math:pow now.

**Comment by dilinisg** [comment]
@maheeka - If it is deprecated, shall we remove it from the binary operators list? If it is there, then it should be working correctly.

**Comment by maheeka** [comment]
Apologies. Missed this. Fixed with https://github.com/ballerinalang/composer/pull/4017/commits/d980a4398687cf66e2f9f882c7fa4191f9a86f61
