### ISSUE TITLE
Remove annotations fs and ftp as service construct is not available for them

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3625]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. Although service construct is not available for fs and ftp it's available in annotations. This should be either removed or the construct added. This has to be decided on what we will be shipping for this release.

![com_0 94_serviceannotation](https://user-images.githubusercontent.com/15624590/31495117-ebc9c10e-af73-11e7-9e40-4db21b2bca8c.png)

**Comment by NatashaWso2** [comment]
fs and ftp packages are removed from the annotation suggestions if the service constructs are not available,  in the latest master. 
![annotation-packages](https://user-images.githubusercontent.com/13446645/33016770-c7a1afb0-ce15-11e7-8192-3c4463097ef0.png)

Hence this issue can be closed
