### ISSUE TITLE
[Editor] Create new file from 'File Explorer' doesn't include package by default

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#363]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Wednesday Feb 08, 2017 at 10:17 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1628_

----

Steps:
- Add Folder to File explorer
- Add new bal file to any folder
- View the imports, it doesn't included the default package/s

**Comment by NipunaMarcus** [comment]
Related Issue: https://github.com/ballerinalang/composer/issues/2047

**Comment by hevayo** [comment]
Fixed
