### ISSUE TITLE
Add three attributes per page in @ws:configuration box

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3633]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Currently @ws:configuration pop up is not evenly distributed as the last page consist of only one attribute Since there are 9 attributes altogether, having 3 attributes per page will be more clean and nice.

**Comment by NatashaWso2** [comment]
Pagination is removed from the property window, so this issue is resolved.
Fixed with: https://github.com/ballerinalang/composer/pull/3880
