### ISSUE TITLE
Two arrows appear when auto scrolling

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3639]
Drag an arrow to an operator which is located at the very bottom. Then the browser will auto scroll resulting in two arrows as displayed below
![15](https://user-images.githubusercontent.com/1845370/31497532-0a1ed1b8-af7d-11e7-8a35-85c0aeaf7bf1.png)

**Comment by keizer619** [comment]
Cannot reproduce this issue after transformer revamp. Hence closing this issue.
