### ISSUE TITLE
Undo action removes all latest added attributes after an immediate add of an attribute

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3640]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add one or two attributes (att1, att2) with values for any configuration
2. Add another attribute (att3)
3. Click undo or press Ctrl+Z

**Acutal result**
All attributes including att1, att2 get undone

**Expected result**
Only att3 should be undone

**Comment by NatashaWso2** [comment]
This is fixed in the latest master branch
