### ISSUE TITLE
Alignment issues in Transform

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3641]
![16](https://user-images.githubusercontent.com/1845370/31497979-5fa2cb8e-af7e-11e7-844f-1c266208a705.png)

**Comment by dilinisg** [comment]
![26](https://user-images.githubusercontent.com/1845370/31504412-f7b7d62e-af8f-11e7-83d6-9b2d34d0c876.PNG)

**Comment by dilinisg** [comment]
Scroll bar does not scroll enough to display all the text
![10](https://user-images.githubusercontent.com/1845370/31769242-7a963d46-b4f0-11e7-9f1c-d3507c750b5e.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
