### ISSUE TITLE
Issues in highlighting 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3647]
Too many colors
![19](https://user-images.githubusercontent.com/1845370/31499086-5d66adce-af81-11e7-8879-3366a9b944d5.png)

![18](https://user-images.githubusercontent.com/1845370/31499104-6dfde788-af81-11e7-9b06-d0baf498c273.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence this issue can be closed.
