### ISSUE TITLE
File not added through directory structure when typed in without .bal extension

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3651]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Go to diretory listing
2. Open a program directory
3. Create new file by right click -> New file
4. Type in a name without .bal extension

The file is not created. 

**Expected result**
The file should be created with the .bal extension added, or an option should be given to user to select the file type

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3892
