### ISSUE TITLE
Invalid variables in the source and target variables list

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3654]
Some variables are already deleted but still shown in these lists
![20](https://user-images.githubusercontent.com/1845370/31500623-86b18c54-af85-11e7-800e-3f6fbe251867.PNG)

**Comment by maheeka** [comment]
This is due to an issue in core which does not set scopes for language server correctly.

**Comment by maheeka** [comment]
This is no longer valid with new Transformer construct where source and targets are fixed and defined in transformer signature.
