### ISSUE TITLE
Try-It icon is not visible

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3655]
![screenshot from 2017-10-12 19-48-54](https://user-images.githubusercontent.com/7681361/31500952-8f28980e-af86-11e7-9d18-91bcec401e80.png)

**Comment by hemikak** [comment]
<img width="596" alt="screen shot 2017-10-18 at 6 10 43 pm" src="https://user-images.githubusercontent.com/4398820/31719037-be2a46d6-b42f-11e7-967a-84d19ba294cd.png">

A try-it button will now appear in the console.
