### ISSUE TITLE
Source view alignment breaks with assignment 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3656]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. When the assignment element is added, the source view alignment breaks.

![com_0 94_assignment](https://user-images.githubusercontent.com/15624590/31501001-b34c156c-af86-11e7-82e8-ad1ece5d27b1.png)

**Comment by manuranga** [comment]
fixed in https://github.com/ballerinalang/composer/pull/3818/commits/e48eec1691862ead65539ce581328a63b7ed6863
