### ISSUE TITLE
Variables edited are not updated in the target

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3657]
1. Add a temp variable to the target
2. Edit the values and save. The source view is updated, but not in the design view

Updated values:
![21](https://user-images.githubusercontent.com/1845370/31500947-8bd773a0-af86-11e7-92c1-9b29d6276908.PNG)
After update:
![22](https://user-images.githubusercontent.com/1845370/31500955-9018b55a-af86-11e7-93eb-a47608c147fe.PNG)

**Comment by keizer619** [comment]
This issue is fixed by following PRs

https://github.com/ballerinalang/composer/pull/3964/
https://github.com/ballerinalang/ballerina/pull/3672
