### ISSUE TITLE
No tooltip or short cut for Import Swagger

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3660]
![24](https://user-images.githubusercontent.com/1845370/31501626-65728338-af88-11e7-8148-f47b73d43f6f.png)

**Comment by maheeka** [comment]
We have added shortcut for swagger import and diagram export with #4595 .  Tool tips are not required for menu items since they are self descriptive.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1029806/32772894-4712730c-c91f-11e7-8bd7-af2901a7d9df.png">

**Comment by maheeka** [comment]
Since swagger definition import is not a frequent operation, we are not planning on providing shortcut keys, as it will clutter the experience. Hence closing this issue.
