### ISSUE TITLE
Cannot give a statement for the assignment declaration

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3662]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Drop in assignment box
2. Type in an assignment. e.g. json data = {"name":"value"}

**Actual result**
The assignment box dissapears although the sample text shows assignment with declaration

![com_0 94_assignment_issue](https://user-images.githubusercontent.com/15624590/31501785-d6ee68c4-af88-11e7-90cb-b89ad0011f9f.png)

**Comment by nadeeshaan** [comment]
This is fixed in the latest head 515941c1f84cf360cf651817a8ccf696c7646419
