### ISSUE TITLE
[Try-it] Cannot add/delete headers if the value is added first

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3670]
**Steps**

1. Start the service and go to try-it.
2. Now in the header adding feild add the value first then the key.

**Issue:** You cannot add headers anymore or delete, till you clear out the values in your headers.

![screenshot from 2017-10-12 21-10-25](https://user-images.githubusercontent.com/7681361/31505201-fc027b88-af91-11e7-9215-067ab248a9bb.png)

**Comment by NatashaWso2** [comment]
Referred this issue in #4673, hence closing this issue.
