### ISSUE TITLE
Shortcut for "Toggle Bottom Panel" is confusing

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3677]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

As shown in the attached image, the shortcut key for Toggle Bottom Panel (ctrl+`) is confusing and not readable

![com_0 94_shortcut](https://user-images.githubusercontent.com/15624590/31507020-d865fc4a-af96-11e7-94f8-9c29c8d469a0.png)

**Comment by NatashaWso2** [comment]
The same shortcut is used in VSCode to toggle the bottom panel, hence this issue can be closed.
https://code.visualstudio.com/docs/editor/integrated-terminal
