### ISSUE TITLE
Issues in try-catch block

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3688]
1. error e is not displayed in the design
2. The whole try catch cannot be deleted at once. Have to delete catch and then try
![29](https://user-images.githubusercontent.com/1845370/31508265-257a9b5e-af9b-11e7-9c83-2ff28578be8a.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master f0358421d6b57aa2448f3ab73bc7a6075ab09bbd
