### ISSUE TITLE
Run-time values are not shown in debugger 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3699]
![screenshot from 2017-10-13 11-49-49](https://user-images.githubusercontent.com/7681361/31532785-eaeb3fda-b00c-11e7-98d5-0387349155b6.png)

**Comment by pahans** [comment]
this is a ballerina core issue

**Comment by pahans** [comment]
created a issue here https://github.com/ballerinalang/ballerina/issues/3639

**Comment by hevayo** [comment]
Issues is fixed in the runtime hence closing.
