### ISSUE TITLE
Block inside a block is considered as a single block when inner block exist without any child elements

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3705]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add while block
2. Add if block

As shown in the attached image, both considered as a single unit (when deleted, entire thing get deleted). But when an element is added inside the if, all three are seperated. But the seperation is only visible from top to bottom (child element, if, while). If mouse hovered from bottom to top, the two blocks are still considered as one.

![com_0 94_loop](https://user-images.githubusercontent.com/15624590/31533605-b92ac23c-b010-11e7-9e3a-c1aeb04e9e9a.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master 4c1b6e32de8f7ab83b0ae21641464c8582a3e285 
Checked with all the compound statements and works without any issue, so this issue can be closed
