### ISSUE TITLE
Try-it allows method body for GET request

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3710]
Browser: Chrome version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image, for a GET request, the message body is allowed. Ideally this shouldn't be allowed.

![com_0 94_tryit_1](https://user-images.githubusercontent.com/15624590/31534457-a211c3da-b014-11e7-948c-8e74119673b2.png)

**Comment by NatashaWso2** [comment]
Referred this issue in #4673, hence closing this issue.
