### ISSUE TITLE
Try-it response body shows up a cursor; ideally should be a disabled field

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3712]
Browser: Chrome version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. A movable cursor is there in the field. This field should be disabled.

![com_0 94_tryit_2](https://user-images.githubusercontent.com/15624590/31534635-6c787754-b015-11e7-87bd-032fb6cf962f.png)

**Comment by maheeka** [comment]
Even though the cursor is visible, the text box is not editable. The cursor is needed for copy behaviour. Without the cursor, users cannot select a text and copy. 

Closing the issue.
