### ISSUE TITLE
http connector is added to the wrong parent

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#372]
<a href="https://github.com/roonyh"><img src="https://avatars.githubusercontent.com/u/3872221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roonyh](https://github.com/roonyh)**
_Wednesday Feb 08, 2017 at 14:27 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1663_

----

1. Create a service
2. Add a http connector to the resource inside service
3. Drop another http connector on to the added http connector

The new connector is added to the outer service.

![screenshot from 2017-02-08 19-52-43](https://cloud.githubusercontent.com/assets/3872221/22741305/c31dd490-ee38-11e6-8a07-4cfc30ebaa71.png)
![screenshot from 2017-02-08 19-53-13](https://cloud.githubusercontent.com/assets/3872221/22741310/c7f2ad60-ee38-11e6-9a3a-6818b3238e08.png)

**Comment by SupunS** [comment]
Reopening the issue, and closing the same issue reported at https://github.com/ballerinalang/ballerina/issues/1663

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing
