### ISSUE TITLE
Icon view change when more libraries accessed

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3723]
Browser: Chrome version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Change view in icon panel
2. Go to more libraries
3. Navigate back to icon panel

The previous selected view is now changed. Ideally the user preference should be retained

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3756
