### ISSUE TITLE
Composer keeps on loading when accessing remotely

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3744]
**Steps**

1. Deploy the composer on a remote server.
2. Access a composer and create a new file.

*Issue*: Composer keeps on loading. This doesn't happen all the time.

**Environment**
Java: 1.8.0_144 (build 1.8.0_144-b01)
Browser: Chrome 58.0.3029.110 (64-bit)

![screenshot from 2017-10-16 09-39-40](https://user-images.githubusercontent.com/7681361/31595343-b5ab6e14-b258-11e7-8d63-35d89ee93ef9.png)

**Comment by pahans** [comment]
tested on 0.94 release it works as expected. Please reopen if reoccured.
