### ISSUE TITLE
The tab naming is inconsistent

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3746]
If you create the file with .bal extension the tab title will have .bal extension. If you create a new file without the extension it will not have an extension.

![screenshot from 2017-10-16 10-18-01](https://user-images.githubusercontent.com/7681361/31595783-ae7e1b84-b25b-11e7-86b1-7f895455a469.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3756
