### ISSUE TITLE
Cannot add structs

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3747]
When I drag and drop a Struct, composer switches to the source view with a syntax error.

![screenshot from 2017-10-16 10-42-03](https://user-images.githubusercontent.com/7681361/31596258-ef8c63da-b25e-11e7-979f-e4b66e4f4408.png)

**Comment by NipunaMarcus** [comment]
This works in the latest master Head #03f64c83e7fc48aacb13df48e16d8784612aa489

**Comment by NipunaMarcus** [comment]
Fixed with the PR: #3801
