### ISSUE TITLE
Debugger is failing to connect

### ISSUE THREAD

**Issue by srsharon** [ballerinalang/composer#3751]
Add a debug point and run debugger the following appears

Please refer screen dump 

![image](https://user-images.githubusercontent.com/10986966/31598348-b910904a-b26a-11e7-8ad0-053602b77948.png)

![image](https://user-images.githubusercontent.com/10986966/31598549-e3d4e4b0-b26b-11e7-9585-23341b11ffd9.png)

**Comment by pahans** [comment]
fixed in 0.9.4
