### ISSUE TITLE
Unknown type message, syntax error when adding a service

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3766]
![screenshot from 2017-10-16 20-01-03](https://user-images.githubusercontent.com/7681361/31617459-e3434474-b2ac-11e7-88c9-c75ed18b9fdc.png)

**Comment by dilinisg** [comment]
Same error observed when opening the StructTransform sample

```
error: ballerina.net.http[0.0.0]/natives.bal:245:1: redeclared symbol 'Session'
error: ballerina.net.http[0.0.0]/session.bal:12:40: unknown type 'message'
error: ballerina.net.http[0.0.0]/session.bal:17:29: unknown type 'message'
```

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced  in the latest master branch 8244d0e1b9e19d6fc3691f0b9705dbb7905921d3
So closing this issue
