### ISSUE TITLE
Errors are popping up in design view while entering code in source view

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3769]
![screenshot from 2017-10-16 20-07-23](https://user-images.githubusercontent.com/7681361/31617757-b999e60e-b2ad-11e7-995c-016676ba3e75.png)

**Comment by nadeeshaan** [comment]
This is by design. The idea here is to avoid the interaction with the design view when there are errors in the source. The errors are the antlr parser errors.
