### ISSUE TITLE
Diagram dissapear when running a program for the first time

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3771]
Steps

1. Create a new file.
2. Add the main function.
3. Save the file.
4. Hitt the run button.

Issue: the design diagram disappears.

![screenshot from 2017-10-16 20-14-07](https://user-images.githubusercontent.com/7681361/31618138-be719bda-b2ae-11e7-85cd-8f4d1a2ac007.png)

**Comment by NipunaMarcus** [comment]
This is fixed in current master hence closing the issue.
