### ISSUE TITLE
[Firefox] Transform design is not drawn in the struct transform sample

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3774]
- Transform design view is not drawn in the struct transform sample
- Structs and other variables are not populated in the source/target view
![50](https://user-images.githubusercontent.com/1845370/31618339-4c7d75c0-b2af-11e7-8413-5430db150e67.png)

**Comment by keizer619** [comment]
Cannot not reproduce this issue now, hence closing this
