### ISSUE TITLE
Source view breaks when transaction retry count is changed - only works when reloaded

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3778]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Steps
1. Add transaction block
2. Change retry count
3. Change to source view

Please see the attached images. The source view get changed to the canvus. This starts working again when the bal file is reloaded

![com_0 94_retry_2](https://user-images.githubusercontent.com/15624590/31618973-074684ae-b2b1-11e7-848a-8db03771d8b4.png)

![com_0 94_trans_retry_1](https://user-images.githubusercontent.com/15624590/31618975-077aeec4-b2b1-11e7-8350-7c19e14b3f0f.png)

**Comment by NipunaMarcus** [comment]
Fix with https://github.com/ballerinalang/composer/pull/3901, hence closing this issue.
