### ISSUE TITLE
Inconsistant behaviour for syntax errors in source view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3786]
As given in the following image, when the transaction block is deleted, due to design view construction issue, it's not able to switch to design view.

![com_0 94_trans_syntax_1](https://user-images.githubusercontent.com/15624590/31621680-f1f7fb9e-b2b7-11e7-8094-a5a3b161e4a4.png)

But for an instance as given below, which also returns a syntax error its able to navigate to the design view cause there is no problem in this case in constructing the design.

![com_0 94_trans_syntax_2](https://user-images.githubusercontent.com/15624590/31621732-18530874-b2b8-11e7-8c63-c1bdd05a0ac0.png)

Since there are two contradicting behaviours for syntax errors this can be bit misleading for a user.

**Comment by kaviththiranga** [comment]
@erandidesilva 
Second one is coming as semantic issue from Backend, we only block switch to design when there are syntax errors in which case we cannot parse and build the model.

**Comment by maheeka** [comment]
Closing as per above comment. 
We cannot allow switching to design at syntax errors. But semantic errors are different to syntax errors and will have a parsable valid model. When we have a model, we allow switching to design view and even show the semantic errors in design view. When we have the data, we try to show the design and stop from doing so, when building the tree is blocking.
