### ISSUE TITLE
Cannot delete the finally block when there are errors in the try catch block

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3797]
When try-catch block is defined with incorrect syntax, cannot delete the finally block. But catch blocks can be deleted. So not consistent in behaviour
```
 try {
    }
    catch(error e) {
    }
    catch(errors:Error e) {
    }finally {
    }
```

**Comment by NatashaWso2** [comment]
This is fixed in the latest master 9938a9a298383b2f47f32dd7e697217df6841f87
