### ISSUE TITLE
Cannot add comments in a struct

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3798]
![screenshot from 2017-10-16 22-00-00](https://user-images.githubusercontent.com/7681361/31623557-69785b6e-b2bd-11e7-9f8a-cdb8120dcb21.png)

**Comment by nadeeshaan** [comment]
According to the grammar, comments are not allowed inside the structs
https://github.com/ballerinalang/ballerina/blob/master/docs/grammar/BallerinaParser.g4#L527
