### ISSUE TITLE
[Intermittent] Bal file get unusable as the syntax errors occurs in source view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3808]
Above issue occured after following the below steps
1. Load bal file
2. Add a transaction 
3. Add a sql client connector
4. Keep the browser untouched for some time.

When the browser is made active again, issue as shown in the image occurs with the following log

```
error: ballerina.net.http[]/natives.bal:245:1: redeclared symbol 'Session'
error: ballerina.net.http[]/session.bal:12:40: unknown type 'message'
error: ballerina.net.http[]/session.bal:17:29: unknown type 'message'
```
![com_0 94_intermittent_1](https://user-images.githubusercontent.com/15624590/31625629-53a9f868-b2c4-11e7-8a8c-e19251beb627.png)

**Comment by nadeeshaan** [comment]
This is fixed in the latest head
