### ISSUE TITLE
"Cannot update design view due to below syntax errors" error pop up even when there are no errors

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3809]
1.Create a syntax error. Then this error will pop up
2. Correct the error

**Issue**
This will still show up. Need to refresh the page to get rid of it

![57](https://user-images.githubusercontent.com/1845370/31625742-ce6c74c2-b2c4-11e7-8ad9-b228a3a6b828.png)

**Comment by kaviththiranga** [comment]
@dilinisg Can you attach a sample source, I tried to reproduce with 'echo service' sample with no luck.

**Comment by kaviththiranga** [comment]
Closing as cannot reproduce on current head b2f904b87fcaf40567f1748e0b5cb8d18b01a218
