### ISSUE TITLE
Design view is not working when there is a continue statement

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3810]
1. Add the below code in a new file. The design view will not be drawn
2. Remove the continue statement. Then the design will be drawn

```
function main (string[] args) {
    while (i == 0) {
        if (i == 0) {
            continue;
system:print(null);
                
        }else{
system:println(null);
            
        }
    }
}
```

**Comment by NatashaWso2** [comment]
"continue" statement is not supported by the grammar now. "next" statement can be used in place of "continue". 
"next" statement is still being implemented from the composer side, so closing this issue
