### ISSUE TITLE
Typo in variable tool tip

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3813]
Please see the attached image. In this tool tip the word "Boolean" should be changed to "boolean"

![com_0 94_variable_tooltip](https://user-images.githubusercontent.com/15624590/31626792-add91e32-b2c8-11e7-9dd1-514810c74a11.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3817
