### ISSUE TITLE
Cannot add debug points to nested try-catch

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3814]
![screenshot from 2017-10-16 23-35-17](https://user-images.githubusercontent.com/7681361/31627362-afbc1cfc-b2ca-11e7-868a-504b0e7cbb51.png)

**Comment by hevayo** [comment]
Reducing the priority since this is some of an edge case based on 80, 20 rule.

**Comment by pahans** [comment]
fixed in 0.94 release
