### ISSUE TITLE
Typo in fork-join tool tip

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3816]
Please see the attached image. The typo "workersand" should be corrected to "workers and"

![com_0 94_fork_typo](https://user-images.githubusercontent.com/15624590/31627680-b62ae644-b2cb-11e7-8e54-cdf7abd27c06.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3817
