### ISSUE TITLE
Cannot import a package after ballerina.net.http 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3828]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add main function
2. Add http client connector

After the http import, add another import (e.g. ballerina.lang.system). As shown in the attached image some unknown issues occurs and afterwards the bal file becomes unusable, unless the import is removed.

![com_0 94_packageimport](https://user-images.githubusercontent.com/15624590/31630938-cbb8e740-b2d5-11e7-844a-721d3b21b7a1.png)

**Comment by NipunaMarcus** [comment]
This is working without any error in current master hence closing the issue.
