### ISSUE TITLE
Continue is shown as a correct statement with a transaction block

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3829]
![screenshot from 2017-10-17 00-58-41](https://user-images.githubusercontent.com/7681361/31631306-febf1992-b2d6-11e7-91a2-17b64ed085f6.png)

**Comment by NipunaMarcus** [comment]
Continue is no longer supported and is replaced with Next keyword. Implementation of the Next model for composer is still ongoing. After Next implementation Continue will be remove from composer.
