### ISSUE TITLE
HTTP Client Connector configuration parameters are incomplete

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3837]
Please see the below image. In this, the Option attribute should contain not only "port". Rather it should contain other details as given in [1] 

[1] https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-http/src/main/ballerina/ballerina/net/http/natives.bal

![com_0 94_http_client](https://user-images.githubusercontent.com/15624590/31633920-5f242f90-b2df-11e7-880f-11c93dab5abe.png)

**Comment by NatashaWso2** [comment]
Fixed with : https://github.com/ballerinalang/composer/pull/3880
