### ISSUE TITLE
HTTP Client Connector config parameter label names

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3840]
Please see attached image. Rather than providing labels in the current way, it's better to provide a meaningful name to the labels in the dialog box. E.g. "serviceUri" to "Service URI". This is more clear and user friendly. Please change client connector properly label names in the above manner

![com_0 94_httpconproperties](https://user-images.githubusercontent.com/15624590/31634529-853768a8-b2e1-11e7-8f32-a33253580913.png)

**Comment by NatashaWso2** [comment]
Fixed with: https://github.com/ballerinalang/composer/pull/3915
