### ISSUE TITLE
SQL Client Connector label name "options" is not informative enough

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3841]
Please see the attached image. According to [1] it should be "ConnectionProperties options". Please provide the full details on configuring this with a minimum sample.

[1] https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-builtin/src/main/ballerina/ballerina/data/sql/natives.bal

![com_0 94_sqlconn_config](https://user-images.githubusercontent.com/15624590/31634859-7c82fa3c-b2e2-11e7-97cc-01e9ae897135.png)

**Comment by NatashaWso2** [comment]
The property window for the connectors is now improved with: 
https://github.com/ballerinalang/composer/pull/3880
https://github.com/ballerinalang/composer/pull/3909
The user can view all the fields inside structs i.e. inside the "options" attribute as well
This is fixed in the latest master branch
