### ISSUE TITLE
Default log level value is incorrect

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3843]
When you add a log the default values are as follows.

`system:log(0, null);`

But according to https://ballerinalang.org/docs/api/0.93/ballerina.lang.system.html Log levels are 1,2,3,4,5

**Comment by hevayo** [comment]
When you drag and drop a function for the parameters we assign set of default values based on parameter type. And for the composer their is no way of identifying these values unless you use an enum for the param or annotate it.

**Comment by maheeka** [comment]
Closing this issue as per above comment. We have no way of identifying what values are allowed unless they are part of the function signature or documentation annotation or argument declaration. 

Raised a suggestion/query in ballerina-core to inquire about this. 

Closing this issue in favour of https://github.com/ballerinalang/ballerina/issues/4037
