### ISSUE TITLE
Logs are not getting printed in console

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3845]
Tried with the following code with different log levels.

import ballerina.lang.system;

function main (string[] args) {
system:log(4, "Test Log Log");
}

**Comment by hevayo** [comment]
Logs are not getting printed even if you run the program directly, so this is probably a runtime issue.

**Comment by pubudu91** [comment]
This is the wrong logger. The new log API is in `ballerina.utils.logger`.
