### ISSUE TITLE
Provide meaningful placeholder default values in HTTP poperties

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3846]
![screenshot from 2017-10-17 02-45-49](https://user-images.githubusercontent.com/7681361/31635730-7bf46292-b2e5-11e7-8f31-9aee29cbda72.png)

**Comment by maheeka** [comment]
Will be populating placeholders from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.

**Comment by NatashaWso2** [comment]
This issue is referenced in #4065 , so closing this issue
