### ISSUE TITLE
UI get disorted when http server config pop is open with split view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3847]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

As shown in the attached image, the UI get disorted when http server config pop is open with split view.

![com_0 94_splitview_1](https://user-images.githubusercontent.com/15624590/31635790-b7d17d36-b2e5-11e7-8d01-e1c41981464b.png)

**Comment by NatashaWso2** [comment]
Pagination is removed from the property window and this is fixed in the latest master branch.
