### ISSUE TITLE
Closing the sql connector config pop up makes the composer not work correctly

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3857]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add a function or a resource
2. Add a sql client connector instance
3. Delete the configuration pop up

As shown in the image below, the composer becomes unusable until refresh

![com_0 94_sqlconn](https://user-images.githubusercontent.com/15624590/31638552-de69e15c-b2f1-11e7-8159-c3fe13fa7573.png)

**Comment by NatashaWso2** [comment]
Fixed with: https://github.com/ballerinalang/composer/pull/3880
Closing this issue as this is fixed in the latest master branch
