### ISSUE TITLE
Text is cutoff by the Header value place holder

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3858]
![screenshot from 2017-10-17 04-20-26](https://user-images.githubusercontent.com/7681361/31638718-b7e9c03c-b2f2-11e7-8809-f989694b7a2f.png)

**Comment by yasassri** [comment]
Same is evident in Content-Type placeholder as well

**Comment by yasassri** [comment]
Same in the response data,

![screenshot from 2017-10-17 04-31-29](https://user-images.githubusercontent.com/7681361/31639014-3c3923e0-b2f4-11e7-8ffe-1eac882f7094.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master c3dbf84fb021c68495071330b7cd26fb753fc690
