### ISSUE TITLE
Cannot add a json variable to the transform statement

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3861]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Drop in a transform statment
2. Expand transform view
3. Add a json type variable. E.g. json myValue {"my":"test"}

**Acutal result**
The added json variable dissapears. When added another variable say a string, then the previously added json appears as well

**Comment by keizer619** [comment]
Same issue has been reported before and we are looking into this. 
Hence closing this issue
https://github.com/ballerinalang/composer/issues/3657
