### ISSUE TITLE
[Firefox] Design view elements blinks when view is minimized and then maximized

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3865]
Browser: Firefox 56.0 (64-bit)

When the service panel is minimized and again maximized the design components blinks. After this only the operation takes place.

**Comment by maheeka** [comment]
Design component blinking issue is no longer their in master branch. Can you please explain what you mean by "After this only the operation takes place." ?

**Comment by NatashaWso2** [comment]
Design component blinking issue is no longer there in the latest master, hence closing this issue.
