### ISSUE TITLE
Version in About pop up

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3867]
Currently the version of the "About" pop up shows up as "0.93". Please change it to the latest released version. Better if it reflects snapshot version before release and the release version when to be released.

![com_0 94_version](https://user-images.githubusercontent.com/15624590/31639948-30925ebc-b2f9-11e7-958f-923132ad2ce7.png)

**Comment by kaviththiranga** [comment]
Fixed in https://github.com/ballerinalang/composer/pull/3876
