### ISSUE TITLE
Composer source view breaks when adding multiple global variables

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3868]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add a global variable 
2. Add another global variable

**Acutal behaviour**
The source view breaks with syntax errors as the second global variable get added within the import statements as shown in the image below

![com_0 94_globalvar_1](https://user-images.githubusercontent.com/15624590/31640134-2812a12e-b2fa-11e7-9bd8-e46ac06bb1af.png)

![com_0 94_globalvar_2](https://user-images.githubusercontent.com/15624590/31640135-283ac096-b2fa-11e7-9061-3adce8b0b155.png)

**Comment by kaviththiranga** [comment]
Fixed with
https://github.com/ballerinalang/composer/pull/3950
