### ISSUE TITLE
Swagger view to source view goes to a blank canvas 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3870]
**Steps**

1. Create an HTTP resource.
2. Open split view.
3. Open the swagger view.
4. From swagger view click source view again.

**Issue:** Composer opens a blank canvas. 

![screenshot from 2017-10-17 05-31-04](https://user-images.githubusercontent.com/7681361/31640581-f0c070d6-b2fc-11e7-807d-171b536edae4.png)

**Comment by maheeka** [comment]
This issue was reproducible earlier. But cannot be reproduced in master. Hence closing.
