### ISSUE TITLE
Text of the Open Directory dialog box should be uniform and in a standard size

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3871]
Please see the below image. The text size should be standard and uniform accordingly.

![com_0 94_textsize_1](https://user-images.githubusercontent.com/15624590/31640749-c42270b4-b2fd-11e7-9613-a96208133f16.png)

**Comment by kaviththiranga** [comment]
@erandidesilva 
Did u mean the "Location" label vs input box text? Please clarify

**Comment by erandidesilva** [comment]
@kaviththiranga 
In the above attached image "Open Program Directory" text size and "Location" text sizes are in noticable two different sizes. Ideally UI should have a standard text sizes in different locations. E.g. for header a uniform text size which is used for all headers in pop ups should be there, so as to the body of the pop up.

**Comment by erandidesilva** [comment]
Mistakelny closed

**Comment by maheeka** [comment]
All the dialogs have same title text size.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1029806/32850354-cdfd4864-ca29-11e7-9a11-113f3521d005.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1029806/32850386-dee3af2e-ca29-11e7-9f38-8d7148011b1d.png">
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1029806/32850391-e4c288e8-ca29-11e7-9f30-d0b3fd3a07c8.png">

Popup headers have the same title text size
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1029806/32850347-c7160f7c-ca29-11e7-8217-393edff81af2.png">

As per above screenshots and comments, closing the issue. Please reopen if this is not what you are trying to explain above.
