### ISSUE TITLE
Able to create an empty space on variable box inside a connector

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3875]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add a connector
2. Add a variable
3. For the next row press enter without entering anything

As shown in the below image, an empty row is added in the dialg box

![com_0 94_var_empty](https://user-images.githubusercontent.com/15624590/31641628-8d395436-b303-11e7-881e-a33708883125.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3882
