### ISSUE TITLE
[Intermittent] Errors when creating files from the left pane

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3883]
Windows-Chrome
Note that this location has permission to create files
![30](https://user-images.githubusercontent.com/1845370/31647973-eba6a1fc-b328-11e7-9df3-64d40849345a.PNG)
![32](https://user-images.githubusercontent.com/1845370/31647974-ebdf6b36-b328-11e7-934e-35c66827dded.png)

**Comment by kaviththiranga** [comment]
This is fixed with 76d21e613877280bd37a39819575877b66ecadee
