### ISSUE TITLE
Warnings in the console when starting the pack

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3886]
![4](https://user-images.githubusercontent.com/1845370/31648440-5cbf850a-b32b-11e7-95db-1ffaa53e7910.png)

**Comment by maheeka** [comment]
There are no warnings during startup now.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/1029806/32850152-46751458-ca29-11e7-901a-8ab653cb6478.png">
