### ISSUE TITLE
No suggestions for connector initialization 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3895]
No suggestions for connectors initialization 
![37](https://user-images.githubusercontent.com/1845370/31650314-6bedd712-b334-11e7-87f8-8ac0688bb929.PNG)
![38](https://user-images.githubusercontent.com/1845370/31650315-6c2c1306-b334-11e7-91a3-88bac06599ea.PNG)

**Comment by hevayo** [comment]
The language syntax related to with keyword will be changed in the next release hence we will not implement this for now.
