### ISSUE TITLE
The text boxes are not well formatted in try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3907]
The text boxes are not well formatted in try-it 
![41](https://user-images.githubusercontent.com/1845370/31657692-af5be076-b34c-11e7-8452-7fe2834d92bc.PNG)
![42](https://user-images.githubusercontent.com/1845370/31657704-b5379e86-b34c-11e7-820d-29804137b20b.PNG)

**Comment by hemikak** [comment]
I was able to reproduce this with 33% zoom out. But that is not working at all with any website.

Following is with 75% on a mac.
<img width="562" alt="screen shot 2017-10-17 at 6 06 12 pm" src="https://user-images.githubusercontent.com/4398820/31665272-e85b203a-b365-11e7-9b67-69b7aa12b995.png">
