### ISSUE TITLE
Inconsistant UX when editing annotations

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/composer#3921]
Please refer https://github.com/ballerinalang/ballerina/issues/2591 for details.

**Comment by hemikak** [comment]
The current UI is different for annotations now. See attachment:
<img width="261" alt="screen shot 2017-10-18 at 2 47 27 pm" src="https://user-images.githubusercontent.com/4398820/31710699-6cd5ed9c-b413-11e7-801a-58265e2b737f.png">

Please reopen if an issue persists.
