### ISSUE TITLE
Same component's render call multiple time unnecessarily 

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/composer#3943]

**Comment by NipunaMarcus** [comment]
@nadeeshaan - you mean sizing and positioning called twice? if it is it is the normal way of calculating. I saw the same issue but that is how the calculations are done. @hevayo knows about this.

**Comment by nadeeshaan** [comment]
@NipunaMarcus - no. just the rendering part. Seems like there are multiple place we do not silently update the properties

**Comment by nadeeshaan** [comment]
Issue no longer reproducible in the latest head. Hence closing
