### ISSUE TITLE
Drag n drop responds slow on cloud

### ISSUE THREAD

**Issue by pahans** [ballerinalang/composer#3955]
Dragging items in tool palette takes time to respond in the cloud.

**Comment by kaviththiranga** [comment]
@pahans is it the drag start which is slow to happen or is it slow while dragging too?

**Comment by kaviththiranga** [comment]
@pahans Drag start is slow due to network call for fragment parse maybe

**Comment by pahans** [comment]
@kaviththiranga yes. it is due to fragment parser call.

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/4630
