### ISSUE TITLE
[Editor] [Improvement] change 'text area' to 'text box' for Path annotation from graphical view to make more user experience 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#396]
<a href="https://github.com/kavithasub"><img src="https://avatars.githubusercontent.com/u/15671620?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kavithasub](https://github.com/kavithasub)**
_Thursday Feb 09, 2017 at 06:29 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1710_

----

Path annotation to resources given a text area, so user can add much characters with spaces in graphical view (see attached). But source view it removed the spaces.
![path_space](https://cloud.githubusercontent.com/assets/15671620/22771711/90bf19f6-eebe-11e6-9e9f-32be7d5ba1b1.jpeg)

**Comment by nadeeshaan** [comment]
This has been removed and have been introduced the annotation editor
