### ISSUE TITLE
Redo does not work in transform

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3973]
1. Add args[] variable to the transform view
2. Undo. The variable will be removed
3. Redo. The variable will not be added back

Note: this works for other variables

**Comment by dilinisg** [comment]
In the 0.94.1 release, this is not working for other variables as well. Hence, increasing the severity

**Comment by maheeka** [comment]
With the new transformer syntax, variables cannot be added in the transformer view. However, adding a parameter and removing them with redo and undo is working in the current master. Hence closing the issue.
