### ISSUE TITLE
"Mapping source cannot be found" error message for each variable added

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3975]
1. Add a new variable for the source

"Mapping source cannot be found" error message appears for each variable added
![8](https://user-images.githubusercontent.com/1845370/31765792-35b239b2-b4e3-11e7-8ddc-72d514c2883f.png)

![9](https://user-images.githubusercontent.com/1845370/31768781-71f217c0-b4ee-11e7-9292-8ce349d31419.png)

**Comment by keizer619** [comment]
This does not happen in 0.95 with transformer changes, hence closing this issue
