### ISSUE TITLE
Run Icon in the left pane is confusing

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3984]
Can we change this icon and the tooltip since this doesn't really run the program?

 
![screenshot from 2017-10-19 16-23-49](https://user-images.githubusercontent.com/7681361/31767771-10414ed2-b4ea-11e7-83db-52410447f2a0.png)

**Comment by maheeka** [comment]
Changed the wordings of the debugger panel as below. 
![image](https://user-images.githubusercontent.com/1029806/32825724-ebd6f2dc-c9dd-11e7-8aab-f0b7e07b79a5.png)
