### ISSUE TITLE
Debugging unsaved files does't work

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3987]
**Steps**

1. Create a new file.
2. Add the main function and a println.
3. Add a debug point to print statement.
4. Click on debug option.
5. You will be asked to save the file. Now save it.

**Issue:** The user is presented with a blank page, and the debug point doesn' get hit. 

![screenshot from 2017-10-19 16-28-15](https://user-images.githubusercontent.com/7681361/31768129-92888184-b4eb-11e7-854a-f029b3208978.png)

**Comment by yasassri** [comment]
It's the same behavior for Run as well.

**Comment by kaviththiranga** [comment]
Fixes https://github.com/ballerinalang/composer/pull/4027
