### ISSUE TITLE
Provide sample values for client connector configuration pop up placeholders

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3990]
As shown in the attached image, currently there is no indication to what the values expected for each configuration. Please provide sample config values so that the user will know what to put accordingly by following the sample

![com_0 94_2](https://user-images.githubusercontent.com/15624590/31768265-3f32dd3a-b4ec-11e7-94ef-e3d062ea536a.png)

**Comment by NatashaWso2** [comment]
Will be populating placeholders from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.

**Comment by NatashaWso2** [comment]
This issue is referenced in #4065 , so closing this issue
