### ISSUE TITLE
Rename SQL client connector configuration pop up field labels

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3994]
As shown in the attached image, the current labels of fields are not user friendly. Please change them so as to they represent the correct english word
e.g. Db name -> Database name

![com_0 94_2](https://user-images.githubusercontent.com/15624590/31768803-818c78b0-b4ee-11e7-8210-e8e51a99a7ff.png)

**Comment by NatashaWso2** [comment]
Will be populating the proper input label name from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.

**Comment by NatashaWso2** [comment]
This issue is referenced #4065 , so closing this issue
