### ISSUE TITLE
Sql client connector: auto commit value should be default to true

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3999]
Please see the below image, it shows the default value for auto commit as false. But according to [1] it should be set to true.

[1] https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-builtin/src/main/ballerina/ballerina/data/sql/natives.bal#L15

![com_0 94_3](https://user-images.githubusercontent.com/15624590/31769424-26d15f5a-b4f1-11e7-82c3-8b5700b5f827.png)

**Comment by NatashaWso2** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4037
