### ISSUE TITLE
Inconsistent behaviour when debugging variables inside transform

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4016]
Add debug points only within the transform block

**Issue**
Two types of behaviors are observed
1. No variables are displayed at all in the variable view
2. Repetitive values as in the image
![16](https://user-images.githubusercontent.com/1845370/31771483-ecd014a0-b4f9-11e7-81dc-9dcf8006929e.png)

**Comment by pahans** [comment]
closing in favour of https://github.com/ballerinalang/composer/issues/4013
