### ISSUE TITLE
Cannot drop in any statement after a if statement

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4023]
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

As shown in the below image cannot add any statement after a if statement from design view.

![com_0 94_trans_7](https://user-images.githubusercontent.com/15624590/31772664-0b5c3a30-b4fe-11e7-93b7-db8d0fb589d9.png)

**Comment by kaviththiranga** [comment]
Fixed with 
https://github.com/ballerinalang/composer/pull/4027
