### ISSUE TITLE
Function not identified eventhough belongs to same package

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4028]
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

As shown in the below image, the function is not identified and shows an error. But this file runs fine by runtime and does not contain any compilation errors

**Error observed in backend**
```
line 9:46 token recognition error at: '"]\n    }\n    resource transSuccessResource (http:Request req,http:Response res) {\n        error e;\n        var result,err = disTransctionSuccess();\n        \n        if (err == null) {\n            res.setStringPayload(result);\n            \n        } else  {\n            res.setStringPayload(err.msg);\n        }\n        res.send();\n    }\n}'
line 9:46 token recognition error at: '"]\n    }\n    resource transSuccessResource (http:Request req,http:Response res) {\n        error e;\n        var result,err = disTransctionSuccess();\n        \n        if (err == null) {\n            res.setStringPayload(result);\n            \n        } else  {\n            res.setStringPayload(err.msg);\n        }\n        res.send();\n    }\n}'

```

![com_0 94_trans_10](https://user-images.githubusercontent.com/15624590/31774134-79a56166-b502-11e7-9d65-3ab8dd3f393d.png)

**Comment by maheeka** [comment]
Can you please share the relevant configuration? If there are any syntax/semantic errors in the other bal file, functions will not be picked by the other bal file.

**Comment by kaviththiranga** [comment]
This was due to the way we used compiler for validating syntax in source editor. It was not aware of package scope previously and we fixed this for a later release and working fine now.
