### ISSUE TITLE
Debug points are aligned wrongly in design view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4035]
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

As shown in the attached image, debug points for the else and the statement inside else are clustered to a single point. The points should be seperatly given.

![com_0 94_trans_13](https://user-images.githubusercontent.com/15624590/31776074-0e56331c-b508-11e7-99a5-29c8c098830b.png)

**Comment by erandidesilva** [comment]
Another instance at transaction block.

![com_0 94_trans_14](https://user-images.githubusercontent.com/15624590/31776352-e80af71e-b508-11e7-925b-9ae1a45b97be.png)

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/4195
