### ISSUE TITLE
Can we show syntax errors in design view as well?

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4036]
Take the following example,

![screenshot from 2017-10-19 20-01-16](https://user-images.githubusercontent.com/7681361/31776218-8b9b335e-b508-11e7-8f64-f48d3606972d.png)

**Comment by NipunaMarcus** [comment]
This feature is in the roadmap of composer and will be included with future releases.

**Comment by NipunaMarcus** [comment]
Related Issue: #4045

**Comment by NatashaWso2** [comment]
This is fixed in the latest master with :
https://github.com/ballerinalang/composer/pull/4268
https://github.com/ballerinalang/composer/pull/4237
https://github.com/ballerinalang/composer/pull/4225

**Comment by NatashaWso2** [comment]
![semanticerror_2](https://user-images.githubusercontent.com/13446645/32155874-2b84fe04-bd60-11e7-878b-e12754c5d0fe.png)
![semanticerror_1](https://user-images.githubusercontent.com/13446645/32155875-2bc3155e-bd60-11e7-965e-483385ac1724.png)
This issue can be closed

**Comment by NipunaMarcus** [comment]
Related issue #1956
