### ISSUE TITLE
No semantic errors when wrong packages are used

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4038]
In the below code segment, when both line 2 and 8 are present no semantic errors are shown to the user. Gives an error only when running the code
![20](https://user-images.githubusercontent.com/1845370/31776288-b8cc36ca-b508-11e7-847d-1f7a91845841.png)

**Comment by maheeka** [comment]
This is now resolved.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1029806/31948655-1a78d244-b8f5-11e7-8367-9c2b1c0c74f1.png">

Please note that error package is not needed now as it is a builtin package. You can declare errors by mentioning `Error error = {};`
