### ISSUE TITLE
Fix case for HTTP client connector options

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4052]
Ssl should be SSL. IMO its better to rename it as SSL Configs or Options
![screenshot from 2017-10-20 09-54-47](https://user-images.githubusercontent.com/7681361/31805249-f4b64c56-b57c-11e7-9413-b4b660eb2afd.png)

**Comment by NatashaWso2** [comment]
Will be populating the proper input label names from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.

**Comment by NatashaWso2** [comment]
This issue is referenced in #4065 , so closing this issue
