### ISSUE TITLE
Give options to select from, in HTTP connector options

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4054]
In some HTTP options, the entering free text doesn't make sense, because ballerina decides supported options, We need to add drop downs for these fields.

![screenshot from 2017-10-20 10-07-46](https://user-images.githubusercontent.com/7681361/31805522-f85862d4-b57e-11e7-986c-fe3950de1d68.png)

**Comment by NatashaWso2** [comment]
Will be populating the supported options of the property field from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.

**Comment by NatashaWso2** [comment]
This issue is referenced in #4065 , so closing this issue
