### ISSUE TITLE
[Firefox] Cannot move the cursor with arrow keys after jumping to the source 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4056]
**Environment**
Java: 1.8.0_144 (build 1.8.0_144-b01)
Browser: FireFox 53.0 (64-bit)

![screenshot from 2017-10-20 11-08-12](https://user-images.githubusercontent.com/7681361/31806670-12bbbdd0-b587-11e7-973c-fa9b7f8d9f5c.png)

**Comment by hevayo** [comment]
Fixed with 0.95.6
