### ISSUE TITLE
Although cursor changes to resize, the Run/debug panel is not actually resizable

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4062]
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

Steps
1. Run/debug program
2. Try to resize the run panel

This is actually not resizable. Either it should be resizable or the cursor shouldn't change to a resize one.

**Comment by maheeka** [comment]
The resize is working for run panel. However, we have restricted a minimum size for resizing. If the panel is not needed (e.g. console view) it can be closed. Closing the issue as this is by design.
