### ISSUE TITLE
Cannot close websocket prop window

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4086]
![screenshot from 2017-10-20 15-15-58](https://user-images.githubusercontent.com/7681361/31815248-c2a5956e-b5a9-11e7-83d5-851db9afedd3.png)

**Comment by yasassri** [comment]
**Environment**
Java: 1.8.0_144 (build 1.8.0_144-b01)
Browser: FireFox 53.0 (64-bit)

**Comment by yasassri** [comment]
Also, it feels really slow when entering prop values. This might be the reason for above.

**Comment by NatashaWso2** [comment]
This is fixed in the latest master 70001d2f82d46b3e6b79322bbc12a8837aa83aca
