### ISSUE TITLE
Can add both service and a main function to the same bal file

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4125]

**Comment by NipunaMarcus** [comment]
Having service and main function in a same ballerina file is supported from the language level so restricting this from ballerina composer is pointless. Also when we have a ballerina file with both service and main function when run invoke there should be a launcher option given to user to choose whether to run the service or the main. This is a feature that we need to include in to composer.

**Comment by NipunaMarcus** [comment]
This is related to #4157
