### ISSUE TITLE
Can add workers to functions

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4133]
![screenshot from 2017-10-22 12-39-46](https://user-images.githubusercontent.com/7681361/31859209-264c9e82-b726-11e7-8816-3ba07ebd1c63.png)

**Comment by NatashaWso2** [comment]
According the grammar we can add workers to functions https://github.com/ballerinalang/ballerina/blob/master/docs/grammar/BallerinaParser.g4#L61
