### ISSUE TITLE
Cannot package bal programs

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4134]
When packages are added composer throws following error.

`error: /home/yasassri/QA_STUFF/current_work/code/ballerina/samples/getting_started/serviceChaining/servicechaining/samples/ATMLocatorService.bal:1:1: invalid package declaration 'servicechaining.samples': no package declaration is needed for default package`

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/4652
