### ISSUE TITLE
Delete button location issue in the headers of try it

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4138]
Release 0.94
When adding headers the delete button appears below the text box taking lot of space in the UI and it is not very appealing to the user. 
You need to scroll down to see the area to add the body as well.
![3](https://user-images.githubusercontent.com/1845370/31874519-4f680308-b7e7-11e7-8584-9731c65db4ab.png)

**Comment by dakshika** [comment]
fixed in latest master
