### ISSUE TITLE
Custom types are not detected 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4143]
I created a struct in a different file in the same package, But they are not detected by the composer.

![screenshot from 2017-10-23 14-15-06](https://user-images.githubusercontent.com/7681361/31880219-84cf7e5c-b7fd-11e7-8e18-b15474b2eee0.png)

**Comment by NipunaMarcus** [comment]
There is a common task created to track the progress of the new language server implementation with the mentioned features hence closing this issue and referencing this as a feature wanted in the language server.
