### ISSUE TITLE
Auto-fill the service if only one service is avaialble and the content type in try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4145]
1. If there is only one service in the package/file that is running, auto fill the service
2. If there is only one resource in the service, auto fill the resource name
3. If the content type (consumes) is configured, auto fill the content type. This will reduce the probability of the user making an error when sending a request

**Comment by dakshika** [comment]
+ 1 for the suggestion

**Comment by hemikak** [comment]
Fixed with #4352, #4363, #4366
