### ISSUE TITLE
Inconsistency in the drop down lists in Try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4146]
Inconsistency in the drop down lists in Try-it.
![6](https://user-images.githubusercontent.com/1845370/31886959-219dc016-b814-11e7-894e-6cee0e9ec5a0.png)

**Comment by srsharon** [comment]
Try-it Ui is under Design review at the moment, hence this will change.

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4352, https://github.com/ballerinalang/composer/pull/4363, https://github.com/ballerinalang/composer/pull/4366
