### ISSUE TITLE
Inner level mappings are not shown when a inner struct is mapped to a struct

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4154]
**Current**
![8](https://user-images.githubusercontent.com/1845370/31927928-c7935f68-b8b3-11e7-880c-c59e45e39616.png)

**Expected**
![9](https://user-images.githubusercontent.com/1845370/31927959-dd74743e-b8b3-11e7-90c3-0bb3551f6be3.png)

**Comment by keizer619** [comment]
Now we are not going to show attribute connections when mapping struct to another struct directly.
Reason is once struct conversions are supported, user would map different types of structs (Here its same Address struct). This even can happen once transform will be changed as reusable first level constructs.
