### ISSUE TITLE
Focus has to be set to the added "Add variable" field in "Configure Application Arguments"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4162]
**Steps**
1. Open Configure Application Arguments 
2. Add a variable

Here unless specifically clicked on the field, the focus is not there in the added text field. It would be better for the focus to be in the text field when added, so that the user doesn't have to click again in the field

![com_0 94m1_2](https://user-images.githubusercontent.com/15624590/31938168-67d5f542-b8d4-11e7-89f9-c5d0efe86a46.png)

**Comment by dakshika** [comment]
fixed
