### ISSUE TITLE
File become unusable until refreshed when saved by "saved as" option

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4167]
**Steps**
1. Add a new file
2. Make a change and save
3. Click "save as"  and save the file with another name

At this point the file is saved and the name is changed to the latest name given in save as. When the source is clicked all view options dissapear. Until file is reloaded, the file becomes unusable

![com_0 94m1_3](https://user-images.githubusercontent.com/15624590/31941120-43cd242c-b8de-11e7-89d9-0caf57672f2c.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4178
