### ISSUE TITLE
Validate calls are happening even when entering a comment

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4174]
![screenshot from 2017-10-24 18-53-41](https://user-images.githubusercontent.com/7681361/31945439-cd585cd0-b8ec-11e7-9a1d-0ff2f5b12878.png)

**Comment by hevayo** [comment]
This is by design we need to do a validate call for each change to see if there are errors.

**Comment by yasassri** [comment]
@hevayo  But whats there to be checked in comments for errors? The problem is if you try to type something fast, composer lags and doesn't detect the keys you press. This is really frustrating. Shouldn't we improve this?
