### ISSUE TITLE
Runtime errors do not render the design

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4241]
Can we provide an error alert for runtime errors?

Consider any source having a runtime error.
```
import ballerina.lang.system;

function main (string[] args) {
}

```
This code is errorneous because of the import. Notice below.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/1029806/32136744-d47a2088-bc30-11e7-90a6-8e9beba13e40.png">

However, there are no errors in the composer.
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1029806/32136753-0d5fd79e-bc31-11e7-910c-00a88f867b1c.png">

**Comment by kaviththiranga** [comment]
Fixed with 8fc9416fe4a27e28d8f5ee3222be0af59a26017e
