### ISSUE TITLE
After renaming a directory cannot run a program

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4253]
![screenshot from 2017-10-29 08-16-01](https://user-images.githubusercontent.com/7681361/32140284-78908b58-bc81-11e7-8a87-65091da3bf45.png)

**Comment by NipunaMarcus** [comment]
This is still not supported in composer. Only file rename will update the related file paths.This is in the road map.

**Comment by NatashaWso2** [comment]
Since this issue is referred in #4306, this issue can be closed.
