### ISSUE TITLE
[Functions] Http annotations are shown and selection only contains websocket

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4257]
Browser: Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)

For functions the http annotation configuration is shown. When clicked on this as shown in the image, only the websocket selection is shown

![com_0 94_new_2](https://user-images.githubusercontent.com/15624590/32140573-3dfa72e6-bc8c-11e7-967d-09ef0d274013.png)

**Comment by hemikak** [comment]
This is fixed in core side.
