### ISSUE TITLE
[BuiltIn] Default assignment contains a syntax error

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4258]
Please see the attached image. The default syntax for the drop down contains a syntax error

![com_0 94_new_3](https://user-images.githubusercontent.com/15624590/32140600-1e079b34-bc8d-11e7-927c-048a0b88f021.png)

**Comment by NipunaMarcus** [comment]
Related issues:

Fix #4254

**Comment by NipunaMarcus** [comment]
This issue is fixed in the current master hence closing this issue.
