### ISSUE TITLE
Errors are shown in wrong places in design view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4262]
1. Open the StructTransform sample
2. Edit the first struct by importing a sample json (which is different to the existing one)

![30](https://user-images.githubusercontent.com/1845370/32140766-81c484d4-bc92-11e7-8891-39d9c24f2bf7.png)
![31](https://user-images.githubusercontent.com/1845370/32140782-cfc49f70-bc92-11e7-8457-95fdbb0bcb26.png)

**Comment by NatashaWso2** [comment]
This is fixed with https://github.com/ballerinalang/composer/pull/4268

**Comment by NatashaWso2** [comment]
Closing this issue since it is fixed in the latest master branch
