### ISSUE TITLE
Composer keeps on loading if http operation is dragged and drop into a worker

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4263]
This happens since the connection initialization happens within a worker, this  gives extraneous input syntax error

![screenshot from 2017-10-29 10-19-12](https://user-images.githubusercontent.com/7681361/32140788-06baae52-bc93-11e7-9269-3c7336a814e7.png)

**Comment by nadeeshaan** [comment]
This is fixed in v0.95, with the new endpoint implementation
Hence closing
