### ISSUE TITLE
"Bad String" error when the key is not a string when importing a json

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4269]
**Steps**
1. Import the following json which a valid nested json object in Ballerina
`{fname:"Peter", lname:"Stallone", "age":32,  address:{line:"20 Palm Grove",city:"Colombo 03",country:"Sri Lanka"}}`

**Issue**
"Bad String" error is displayed to the user and blocks the user from adding it
![37](https://user-images.githubusercontent.com/1845370/32141060-6592647a-bc9c-11e7-991f-ba6983a8bb70.png)

**Expected**
Valid json objects in Ballerina should also be able to import from composer

**Comment by NipunaMarcus** [comment]
related task: #4287
