### ISSUE TITLE
Can edit the http method in try it

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4271]
![40](https://user-images.githubusercontent.com/1845370/32141138-77d8c79e-bc9e-11e7-8b36-66de90d2130c.png)

**Comment by hemikak** [comment]
This is to allow custom http methods. But there was an issue where the typed value is not being picked up as the http method. This is been fixed in https://github.com/ballerinalang/composer/pull/4530.

**Comment by hemikak** [comment]
Please reopen if needed.
