### ISSUE TITLE
Collapse annotation view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4273]
Currently only single annotations are collapsible. Should we provide a way to collapse the whole annotation view since it takes a lot of space?

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1029806/32150650-ab35999e-bd3b-11e7-992f-580801633d9b.png">

**Comment by NatashaWso2** [comment]
This is fixed in the latest master with https://github.com/ballerinalang/composer/pull/4312
