### ISSUE TITLE
Should we add an action by default to a connector?

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4275]
Similar to services having a resource by default, should we add an action by default to the connector. It makes sense since a connector has no value without having any actions. Also, it helps with the blank look of an empty connector.
<img width="654" alt="image" src="https://user-images.githubusercontent.com/1029806/32150948-8b6314e0-bd3e-11e7-85b6-7bfcda109674.png">

Also shall we left align variable a bit in connector. It is okay for services, but doesn't look good in connectors. 

Similar to Add Resources in services, we should have the same for Connectors to add actions. 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1029806/32150950-8fc36242-bd3e-11e7-8e41-20adc56794db.png">

@dakshika , @hevayo

**Comment by NipunaMarcus** [comment]
I think we added a action as a default previously. I think we should do the same now as it will be easy to user.

**Comment by hevayo** [comment]
Fixed in HEAD
