### ISSUE TITLE
Check and fix basic compatibility issues on Microsoft Edge

### ISSUE THREAD

**Issue by kaviththiranga** [ballerinalang/composer#4307]

**Comment by kaviththiranga** [comment]
No major breaks are found. Did some smoke tests on Edge.

**Comment by kaviththiranga** [comment]
![capture22](https://user-images.githubusercontent.com/1505855/32207877-e9fbddf2-be24-11e7-8527-58bb6355f1c3.PNG)
Minor issues with diagram styles. See text positions

**Comment by kaviththiranga** [comment]
![dragdrop](https://user-images.githubusercontent.com/1505855/32208054-063ea1ce-be26-11e7-88b9-22863a2a989f.png)
Drag Preview also has some issues, seems it is getting the image on tool palette + drag icon both

**Comment by hevayo** [comment]
implementation has differed tool palette was removed from 0.95.6
