### ISSUE TITLE
Syntax of HTTP action invocation statement is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4317]
1. Add a HTTP connector
2. Add a method (GET) from the design view

**Issue**
The syntax of the code generated in incorrect
![46](https://user-images.githubusercontent.com/1845370/32219182-55ec50c2-be53-11e7-88e7-a89b29591e95.png)

**Comment by NipunaMarcus** [comment]
This is fixed in the current master hence closing the issue.
