### ISSUE TITLE
Issues in the Client Connector property view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4336]
1. Add a HTTP client connector and configure the connector options

**Issues**
1. The error message is not readable when an invalid value is set
![50](https://user-images.githubusercontent.com/1845370/32274840-cedefa1c-bf2e-11e7-8aff-20e61d1507ec.png)

2. Cannot read the entire configuration once the connector options are configured
![51](https://user-images.githubusercontent.com/1845370/32274934-4f702138-bf2f-11e7-8ebe-6883dc030a5a.png)

**Comment by NatashaWso2** [comment]
The user can read the entire configuration when the connector options are configured by horizontally scrolling over the text field.
