### ISSUE TITLE
Cannot collapse the tree view of file explorer when a file is opened

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4342]
**Steps**
1. Open a folder from the file explorer
2. Expand and collapse. It should be working file
3. Open a file in that folder in the design view
4. Expand and collapse the tree view again

**Issue**
Cannot collapse the tree view again unless the program/service that was opened is closed

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4362
