### ISSUE TITLE
Label changes required in annotation configurations

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4358]
Need the following labels all in capital

**HTTP:** SSL
![55](https://user-images.githubusercontent.com/1845370/32320103-b5a1fc34-bfe2-11e7-8090-61ccf9eb07d7.png)

**WS:** WSS port

**Comment by dilinisg** [comment]
Same should be done for Client Connector configurations

**Comment by NatashaWso2** [comment]
Will be populating the proper label name from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.

This issue is referenced in #4065 , so closing this issue
