### ISSUE TITLE
Errors when opening Transform statement sample

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4407]
Errors in both JSONTransform and StructTransform samples. Therefore, cannot run the sample.
![5](https://user-images.githubusercontent.com/1845370/32401866-2b7e0900-c13e-11e7-89cc-60022c7b222d.png)

**Comment by keizer619** [comment]
I checked with head and correct sample is loading as its fixed in the core
https://github.com/ballerinalang/ballerina/issues/3898
