### ISSUE TITLE
Compilation errors when running most of the samples

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4408]
![6](https://user-images.githubusercontent.com/1845370/32401902-e658963c-c13e-11e7-9e4b-64d008377c32.png)

**Comment by dilinisg** [comment]
Issue 2:
Same when running the Service Chaining sample

**Comment by dilinisg** [comment]
All other samples; RESTful service, Routing services, web socket are giving compilation errors when running

**Comment by nadeeshaan** [comment]
This is fixed with the latest head
