### ISSUE TITLE
[Firefox] Experiencing a lag when adding constructs to the canvas

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4413]
Experiencing a lag when adding constructs to the canvas
![8](https://user-images.githubusercontent.com/1845370/32402132-4ae641fe-c143-11e7-81bf-f37d1154a8fb.png)

**Comment by NipunaMarcus** [comment]
@pahans - will this be fix with the catching?

**Comment by pahans** [comment]
Fixed in latest master (0.95.1)
