### ISSUE TITLE
[HTTP] Undefined import is added with endpoint. This causes run failure

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4416]
As seen in the below image, when an endpoint is dropped an import statement is there called undefined. This causes the run failure. 

![com_0 95_5](https://user-images.githubusercontent.com/15624590/32402247-bd60245a-c145-11e7-8ee8-012509f851c3.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master dad44a9972ca89d44b96fca5e30ae70ba9951e8c
