### ISSUE TITLE
[HTTP] RetryClient is not being drawn correctly in composer

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4420]
Steps
1. Add a service
2. Add a RetryClientConnector

Added code
```
http:RetryClient var1 = create http:RetryClient({},0,0);
```
Expected code
```
endpoint<http:ClientConnector> ep {
               create http:RetryClient(create http:ClientConnector("http://localhost:9090", {}), 6, 5000);
       }
```
![com_0 95_8](https://user-images.githubusercontent.com/15624590/32402548-85f08f6c-c14c-11e7-983a-1c1ddfe24e02.png)

![com_0 95_9](https://user-images.githubusercontent.com/15624590/32402552-8e31e702-c14c-11e7-8227-8f456eee121c.png)

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master
