### ISSUE TITLE
"Import undefined" when adding a function from the current package

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4425]
1. Add a function from the current package and verify the imports

**Issue**
"Import undefined" when adding a function from the current package
![12](https://user-images.githubusercontent.com/1845370/32402710-1d44f35a-c150-11e7-80c0-25d13425878e.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master dad44a9972ca89d44b96fca5e30ae70ba9951e8c
