### ISSUE TITLE
[Fork-Join] Cannot add the a fork join 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4428]
Pack: https://wso2.org/jenkins/view/All%20Builds/job/ballerinalang/job/tools-distribution/880/org.ballerinalang.tools$ballerina-tools/

Cannot add a fork join as shown in the attached image

![com_0 94_10](https://user-images.githubusercontent.com/15624590/32402832-206d0bba-c152-11e7-9572-fa4346b3f6c7.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master a52cd47a69b2595621a44c7626e40547120c95c8
