### ISSUE TITLE
Wrong error message when a struct is passed as a variable in a resource

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4429]
1. In the echo service sample, include a struct as a param for the resource

**Issue**
1. An error will be shown as in the screen shot which is wrong. Ideally it should ask the user to remove the struct.

![13](https://user-images.githubusercontent.com/1845370/32402825-0d5df1ec-c152-11e7-89aa-8da5f7879ea9.png)
2. When the newly added struct is removed from the design view, the following code segment will be automatically removed.
```
    @http:resourceConfig {
        methods:["POST"],
        path:"/"
    }
```

**Comment by nadeeshaan** [comment]
The issue addressed at point 1 is invalid since the error message shown is the actual error message triggered by the compiler according to the grammar.

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced in the latest master, hence this issue can be closed.
