### ISSUE TITLE
[Transaction] Cannot add a transaction block

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4430]
Pack: https://wso2.org/jenkins/view/All%20Builds/job/ballerinalang/job/tools-distribution/880/org.ballerinalang.tools$ballerina-tools/

Please see attached image. Cannot add a transaction block

![com_0 95_11](https://user-images.githubusercontent.com/15624590/32402868-3c2caec2-c153-11e7-898c-2150d1ad1731.png)

**Comment by NatashaWso2** [comment]
Fixed in the latest master a52cd47a69b2595621a44c7626e40547120c95c8
