### ISSUE TITLE
Does not show the mapping between a property of an anon struct and a struct

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4437]
![16](https://user-images.githubusercontent.com/1845370/32403278-d64b760c-c15b-11e7-8fbc-d8222f3528b7.png)

**Comment by dilinisg** [comment]
Does not show mappings between anon struct to anon struct
![21](https://user-images.githubusercontent.com/1845370/32405453-69e0918e-c18b-11e7-85da-9645300afe6c.png)

**Comment by keizer619** [comment]
Need to revisit consider anonStruct behavior within new transformer when supporting anonymous structs in the composer 
https://github.com/ballerinalang/composer/issues/4287

**Comment by keizer619** [comment]
With latest anonStruct fixes in Transformer this has been fixed. Now these will be reflected in the code and now we don't show a type name for anonymous structs as following screenshot
![screen shot 2017-11-17 at 6 11 06 pm](https://user-images.githubusercontent.com/2918812/32947766-a2d1934e-cbc2-11e7-818d-2a3a6789b26c.png)
