### ISSUE TITLE
No proper way to add a lambda function from the tool pallet

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4440]
No proper way to add a lambda function from the tool pallet. 

Only way possible is,
1) drag drop assigment
2) click on it
3) delete '1' and type 'function(){}'
4) enter

**Comment by nadeeshaan** [comment]
@dilinisg Labmda function generation via the composer is an ongoing feature and the drag-drop design and the functionality are yet to be finalized. Hence keeping this on hold.

**Comment by hevayo** [comment]
With the new design revamp (0.95.6+) we will be not showing lambda in the design view. Will create an issue if the requirement comes in the future.
