### ISSUE TITLE
Code is not generated for binary/unary operators

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4448]
Adding two strings: Code is not generated
![23](https://user-images.githubusercontent.com/1845370/32405572-1180b980-c18e-11e7-84ed-da04d69e3972.png)

Adding two integers: Code is partially generated
![24](https://user-images.githubusercontent.com/1845370/32405576-260b5bb2-c18e-11e7-88e1-f55b3089ff0a.png)

**Comment by roonyh** [comment]
Could not reproduce in the current master.

This could happen in the last pack, because we had an issue where source view and design view gets detached. It was fixed in a432cebed

**Comment by roonyh** [comment]
Closing since this is not reproduced in 0.95. Please reopen if needed
