### ISSUE TITLE
Try-it fails when using it while debugging

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4449]
1. Add debug points to a service
2. Debug the service
3. Go to try it and send a request

**Issue**
1. Request fails and error is shown to the user which is not correct
2. Can continue debugging even when the request has failed. Will stuck at the time the response should be sent to the client
![26](https://user-images.githubusercontent.com/1845370/32405673-d5ba3488-c18f-11e7-9bdf-006a2d935c71.png)

**Comment by nadeeshaan** [comment]
This is since the timeout for tryit is set to a small value. We need to increase this. Since this is not a blocker setting the severity Major.

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4505
