### ISSUE TITLE
Change the appearance of param icon when we have added params

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#445]
Currently there is no way to identify whether certain resources or functions contain params or not. Idea is to change the appearance of params icon when its not empty. Something similar to following image.

<img width="201" alt="screen shot 2017-02-10 at 7 50 30 pm" src="https://cloud.githubusercontent.com/assets/6814264/22829822/5cb5a1ea-efca-11e6-8e68-7927fe133178.png">

**Comment by hevayo** [comment]
Implementation has changed with new implementation you can always see the parameters.
