### ISSUE TITLE
Increase the timeout in try-it

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4458]
If you try to debug a flow by sending a request with try-it. Try-it fails very quickly by giving the following error. Can we do the $subject if that's the issue?

![screenshot from 2017-11-05 14-53-59](https://user-images.githubusercontent.com/7681361/32413554-70fd21b8-c239-11e7-8b23-c54bc29cdc73.png)

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4505
