### ISSUE TITLE
[Action view] Doesn't compact the code but compacts the design

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4469]
As shown in the below image, the design is compacted, but not the source when action view is triggered

![com_0 95_new_5](https://user-images.githubusercontent.com/15624590/32413895-c9eb7cf0-c240-11e7-8ab2-58891710190e.png)

**Comment by nadeeshaan** [comment]
Perspectives are only for the design view. This is by design and hence closing the issue
