### ISSUE TITLE
Client Response struct is not shown in debug mode

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4474]
![screenshot from 2017-11-05 16-39-05](https://user-images.githubusercontent.com/7681361/32414213-2418b312-c248-11e7-864f-e00859611ee0.png)

**Comment by pahans** [comment]
This is a ballerina core issue reported here https://github.com/ballerinalang/composer/issues/4474

**Comment by pahans** [comment]
closing this in favour of https://github.com/ballerinalang/ballerina/issues/4124
