### ISSUE TITLE
[Intermittent] Invalid values in source and target lists in Transform 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4491]
![38](https://user-images.githubusercontent.com/1845370/32422174-ac5ac00e-c2c4-11e7-8bea-a1084e282fc2.png)

**Comment by maheeka** [comment]
Cannot reproduce in master. 

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1029806/32883680-ec2c2ef0-caaf-11e7-9a13-c334e96addc5.png">
