### ISSUE TITLE
UI issues in transform when adding/editing parameters and variables

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4493]
As shown in the screen shot,
1. The fields are not properly aligned
2. Does not have space to see the full text.
3. Cannot see the data types properly when editing
4. The data types are not properly displayed in the drop down list when editing the data types
![40](https://user-images.githubusercontent.com/1845370/32422376-f04070c4-c2c5-11e7-87bc-7e3f31a8023c.png)
![41](https://user-images.githubusercontent.com/1845370/32422419-2ca80234-c2c6-11e7-8813-a7ca9abd4569.png)

**Comment by roonyh** [comment]
Changed in #4613 to,

![image](https://user-images.githubusercontent.com/3872221/32872452-c9970584-caac-11e7-842e-9b7739d14ffb.png)
