### ISSUE TITLE
Source is not generated for the parameters added in transform

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4494]
1. Add a new parameter. No source code will be generated
2. Add a binary operator and map the parameter added

**Issue**
1. Source is not generated for the parameters added. Therefore, when try to map get an error saying the parameter added is undefined.
![42](https://user-images.githubusercontent.com/1845370/32422535-e5d5a2ca-c2c6-11e7-9284-2638ecc0b56d.png)

**Comment by keizer619** [comment]
This only happens when transformer does not have the name with brackets to include parameters. Transformers with names with brackets work as expected. For these cases we will generate a name with brackets,
