### ISSUE TITLE
Cannot edit fork-join properties from the UI

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4496]
**Environment**
Java: 1.8.0_144 (build 1.8.0_144-b01)
Browser: FireFox 53.0 (64-bit)

![screenshot from 2017-11-06 07-59-49](https://user-images.githubusercontent.com/7681361/32422874-eff71566-c2c8-11e7-97df-fb7815fe4b30.png)

**Comment by manuranga** [comment]
Duplicate of #4496
