### ISSUE TITLE
When result map declaration name is edited it disappears and leads to a syntax error

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4497]
![screenshot from 2017-11-06 08-06-43](https://user-images.githubusercontent.com/7681361/32422948-7b39044a-c2c9-11e7-9a49-c427609ceb48.png)

![screenshot from 2017-11-06 08-06-53](https://user-images.githubusercontent.com/7681361/32422950-7d36e9b0-c2c9-11e7-976b-236c73bd7163.png)

**Comment by manuranga** [comment]
Marcus, I will not be able yo look at this for few hours , if ugent please
take a look

**Comment by NipunaMarcus** [comment]
This issue is fixed hence closing this issue.
