### ISSUE TITLE
Current package docs link gives a 404

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4499]
Also, there are no tooltips for this,

![screenshot from 2017-11-06 08-15-04](https://user-images.githubusercontent.com/7681361/32423238-370d3c12-c2cb-11e7-97c7-fe09c2789dff.png)

![screenshot from 2017-11-06 08-15-30](https://user-images.githubusercontent.com/7681361/32423240-391f8f46-c2cb-11e7-942a-d7a6529ecb9e.png)

**Comment by NipunaMarcus** [comment]
Current package cannot have a doc as for now only native packages has documents hence document icon should not be available to current package items... @hevayo WDYT?
