### ISSUE TITLE
Cannot save / open the file by keyboard enter

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#454]
1. Select 'Open file' From 'File Menu' and select the file. Press **keyboard enter** key to open.
2. Open a new file. Select save from 'File Menu' and enter file name & location, and press **keyboard enter** to save. 
- Mouse click on save & open is working fine.

Used build from master 11-Feb (e33c12e5536bad80838cff66c8d5a30d387a657b)

**Comment by NipunaMarcus** [comment]
Issue is fixed hence closing the issue.
