### ISSUE TITLE
Composer swagger import not working with escaped quotes

### ISSUE THREAD

**Issue by ArjanVliem** [ballerinalang/composer#4540]
when i try to import swagger definition with escaped double quotes in for example description, the quotes get through and not escaped.

example part of definition that fails on import:
`"/salt_returns/{job_id}" : { "get" : { 
              "description" : "Retrieve the salt return for job id \"job_id\"",
              "parameters" : [ { "$ref" : "#/parameters/job_id" } ],
              "responses" : { 
                  "200" : { 
                      "description" : "OK",
                      "schema" : { "$ref" : "#/definitions/job_data" }
                    },
                  "401" : { "$ref" : "#/responses/401response" }
                },
              "summary" : "Retrieve the salt return for job id \"job_id\"",
              "tags" : [ "salt_returns" ]
            } },`

**Comment by hemikak** [comment]
@ArjanVliem we are looking into this. Thanks for reporting!.
