### ISSUE TITLE
CORS properties are not detected

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4552]
![screenshot from 2017-11-09 13-29-15](https://user-images.githubusercontent.com/7681361/32594468-269e1502-c552-11e7-95cc-9f87077b888d.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, so this issue can be closed.
![cors](https://user-images.githubusercontent.com/13446645/32597880-04554efa-c55e-11e7-82c8-5bd29668fb8c.png)
