### ISSUE TITLE
Provide a description about the properties in connectors

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4553]
When trying to configure a connector (for eg: SQL connector), the property window shows a list of fields to configure, But does not say what that property does (eg: Db type). Because of this, the user might get confused on what to configure.
![62](https://user-images.githubusercontent.com/1845370/32594895-c33f97ea-c553-11e7-8cf0-5f0843ff4883.png)

This is a screen shot on how Mysql workbench shows the description of the properties
![70](https://user-images.githubusercontent.com/1845370/32595077-6e438958-c554-11e7-9949-81d6efae0c4c.png)

**Comment by NatashaWso2** [comment]
Will be populating placeholders from doc annotations in the core when it is available. Until this support is available, will place this issue on hold.
This issue is referenced in #4065 , so closing this issue
