### ISSUE TITLE
composer.bat --port 9092 does not work

### ISSUE THREAD

**Issue by robbla** [ballerinalang/composer#4568]
When running in Windows 10, the --port parameter does not work. This is possible on Linux environments.

**Windows** 
composer.bat --port 9092
Not supported option or command or value : --port
ECHO is off.
Start Ballerina Composer using 'composer.bat'

**Centos 7**
 ./composer --port 9092
INFO: Ballerina Composer URL: http://localhost:9092

**Comment by kaviththiranga** [comment]
FIxed with https://github.com/ballerinalang/tools-distribution/pull/212
