### ISSUE TITLE
composer running in VM like virtualbox does not allow browser access

### ISSUE THREAD

**Issue by robbla** [ballerinalang/composer#4571]
Composer 0.95 running in a centos box built with vagrant on VirtualBox does not allow browser access to the composer interface. The same goes for running on AWS environment. 

Port was forwarded in vagrant but does not make the connection to the composer running. It is available from within the VM (e.g. curl -v http:/localhost;9091) but from outside throws an error

curl: (7) Failed to connect to localhost port 9091: Connection refused

Only when ssh tunneling  into the vm like this

ssh -L 9999:127.0.0.1:9091 -i .vagrant/machines/Ballerina/virtualbox/private_key vagrant@192.168.33.77

will work and show the composer interface

it seems like it is only listening on 127.0.0.1 rather than anything else

**Comment by hemikak** [comment]
Hi @robbla ,

Yes, we are forcefully binding to the 127.0.0.1 for the composer as of now.

To bind to 0.0.0.0, you can modify the composer script and add the following line to the java command.

`-Dmsf4j.host=0.0.0.0 \` at https://github.com/ballerinalang/tools-distribution/blob/master/modules/ballerina-tools/bin/composer#L205

Meaning that you can override the 127.0.0.1 binding using the "msf4j.host" system property.

Regards,

**Comment by hemikak** [comment]
Closing as per comment.
