### ISSUE TITLE
Revisit statement UI and tool palette

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4580]
The current statement design needs improvements to address a few issues. 

1. Dragging and dropping statements makes no sense - users are not and do not need to know the details of statement types. e.g. assignment vs variable def statement makes no sense from a user's point of view. Everything are statements. Hence we should not add different statements to the tool palette. This is only true for single statements. For block nodes like if-else or while, tool palette makes sense. 
2. We must provide a simple way of typing statements in design view. Maybe a statement box in lifeline where users can keep adding statements with enter or some similar behaviour. (This was discussed before as well)

**Comment by maheeka** [comment]
Also reported in https://github.com/ballerinalang/composer/issues/2063 as 

> It is not clear whether to use an assignment statement or a variable def statement. Since we now allow interchanging among statement types, we can support adding a generic statement box.
> 
> Also it is easier without having to drag drop, when hovering over the lifeline a [+] icon appearing indicating to add a statement box. (we can also consider adding a statement box underneath current one when hitting enter)

**Comment by hevayo** [comment]
implementation has differed tool palette was removed from 0.95.6.
