### ISSUE TITLE
Adding a const from UI will duplicate the const definition

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4581]
Add a new constant by typing `const string i = "hello"` and hit enter. UI will show two constants and the error of duplicated creation. However, source is generated correctly.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/1029806/32717291-fc9ae774-c850-11e7-989f-c129e779e75d.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1029806/32717319-19391892-c851-11e7-9d74-eca7fa9d4c39.png">

**Comment by NatashaWso2** [comment]
Global variables  are added correctly both in the design and the source view.
![globals](https://user-images.githubusercontent.com/13446645/32845103-f33eea68-ca49-11e7-852c-2475baeff7f4.png)

This cannot be reproduced in the latest master, hence closing this issue.
