### ISSUE TITLE
[Connector] distorted variable component in connector design view, with lengthy variable declaration

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4589]
As shown in the below image, the design view is distorted with a lengthy expression

![composer_3](https://user-images.githubusercontent.com/15624590/32766169-b3719a8c-c933-11e7-8a5d-0c3c3f1bf23b.png)

**Comment by NatashaWso2** [comment]
If the variable declaration is too long, we truncate it and show a part of it and on the tooltip the entire variable declaration is shown.
