### ISSUE TITLE
UI issues in Try-it when the service name is lengthy

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4597]
**Description:**
There are UI issues in the try-it when the service name is lengthy as shown in the screen shots below
![85](https://user-images.githubusercontent.com/1845370/32773057-f4ee6ebc-c94d-11e7-816c-89cc94166d99.png)
![86](https://user-images.githubusercontent.com/1845370/32773070-fe01ae9c-c94d-11e7-94f9-25e87c0b21b5.png)

**OS, DB, other environment details and versions:**   
Firefox

**Comment by NatashaWso2** [comment]
Referred this issue in #4673, hence closing this issue.
