### ISSUE TITLE
Composer doesn't detect file changes from file system

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4609]
**Description:**
Imagine I'm working on a project and I do a git pull to get the latest changes from the file system. But the composer doesn't detect file changes.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.95
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Open a File in composer
2. Edit the file from the file system
3. Check whether it is detected.

**Related Issues:**

**Comment by NatashaWso2** [comment]
This issue is referred in #4306, hence this issue can be closed.
