### ISSUE TITLE
No suggestions when adding a package

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4614]
**Description:**
No suggestions when adding a package.

![screenshot from 2017-11-16 10-07-13](https://user-images.githubusercontent.com/7681361/32874102-1d07c902-cab6-11e7-9fe9-74d40e08e407.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.95
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Open composer.
2. Try to add a package from the source view or design view.

**Comment by NatashaWso2** [comment]
This issue related to the language server is tracked in #4696, hence this issue can be closed.
