### ISSUE TITLE
Refactor Transform code base to Transformer

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4626]
**Description:**
 - Remove all references to transform and change them to transformer.
 - Refactor render logic to remove unnecessary logic of maintaining vertices from transform

**Comment by keizer619** [comment]
Removed old transform files and codes in following PR. Still need to do renaming from "transform" to "transformer"
https://github.com/ballerinalang/composer/pull/4756

**Comment by keizer619** [comment]
File names have been renamed from "transform" to "transformer" in following PR
https://github.com/ballerinalang/composer/pull/4911
