### ISSUE TITLE
[Intermittent] mouse click on outside doesn't collapse the argument/ annotation windows

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#463]
mouse click on the outside of the window doesn't reflect to collapse both windows (argument / annotation)

![click](https://cloud.githubusercontent.com/assets/15671620/22852499/86347bce-f063-11e6-817b-ad29f02ae765.jpeg)

**Comment by hevayo** [comment]
Annotation UI has changed thus the issue is no longer relevent.
