### ISSUE TITLE
source view does not show the right code

### ISSUE THREAD

**Issue by robbla** [ballerinalang/composer#4641]
running a ballerina program throws an error, saying that the variable is not defined  (snewfortune)
![afbeelding](https://user-images.githubusercontent.com/11582659/32938708-664f31aa-cb7d-11e7-8be8-5d8f1f1c9972.png)
The source view shows the variable however without the 's' newfortune

only after closing the bal file and reloading it it is shows the error 

![afbeelding](https://user-images.githubusercontent.com/11582659/32938802-aa248aba-cb7d-11e7-9b5f-1ad6c95a19c9.png)

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
0.95, w10 
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
hard to reproduce but an error in representing the source

**Related Issues:**

**Comment by hevayo** [comment]
Hi robbla We fixed a bug ( https://github.com/ballerinalang/composer/issues/4579 ) which can be the possible cause for the above issue, it is currently available in master and will be shipped with next release.

**Comment by hevayo** [comment]
We have release the fix with 0.95.1 [1]. Will close the issue since the fix is released.

[1] https://ballerinalang.org/downloads/
