### ISSUE TITLE
UX issue - while highlight the resource name with mouse movement

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#465]
- Drag and drop a service
- Click on resource name, start to highlight from the white space, and with the mouse movement the below image appears in graphical

![dragg](https://cloud.githubusercontent.com/assets/15671620/22852692/f0d56714-f067-11e6-8996-e06a4a56922f.jpeg)

**Comment by hevayo** [comment]
Above issue is no-longer reproducible after react migration.
