### ISSUE TITLE
Adding multiple catch blocks distort the design view

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4663]
**Description:**
![screenshot from 2017-11-18 17-43-07](https://user-images.githubusercontent.com/7681361/32980182-07d83d40-cc88-11e7-98cf-dc16863d66f2.png)

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
Firefox

**Comment by NatashaWso2** [comment]
When multiple catch blocks are added it does not distort the design view in Chrome and Firefox.
![catch chrome](https://user-images.githubusercontent.com/13446645/33002917-445dbe24-cddd-11e7-8e0e-6ab00efc84e9.png)

This cannot be reproduced in the latest master, hence this issue can be closed.
