### ISSUE TITLE
Syntax errors not given for duplicate variables

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4664]
**Description:**
![screenshot from 2017-11-18 17-52-14](https://user-images.githubusercontent.com/7681361/32980285-821b37a0-cc89-11e7-9154-439d39c8c57c.png)

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
Firefox

**Comment by NipunaMarcus** [comment]
Following are the scenarios on how the ballerina var variable works. 
1. if there are no new variable you cannot use var, so in this case 
``` Ballerina
var var1, var2 = ... 
```
will give an error saying "No new variables on the left side".
2. if there are new variables it will work without an error so in this case
```Ballerina
var var3, var4 = ...
```
will work.
3. if there are new variables and existing variables then ballerina will create new variables and reference existing one so new values will be assigned to existing variable. so in this case
```Ballerina
var var3, var2 = ...
```
means var3 will be the newly created variable and var2 will be refer to the existing variable.
