### ISSUE TITLE
[Directory structure] Close and refresh buttons not properly placed at default panel size

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4669]
As shown in the below image, even at default panel size, the close and refresh buttons are not placed properly

![issue_2](https://user-images.githubusercontent.com/15624590/33004303-06df208e-cde6-11e7-8247-ce7c383112e8.png)

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence closing this issue.
![directory-struc](https://user-images.githubusercontent.com/13446645/33004491-166256ba-cde7-11e7-8a3d-f0e5607b060a.png)
