### ISSUE TITLE
Cannot add a function to a large file with lot of functions

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4670]
Please see the attached code. When adding another function as shown in the attached image, errors are thrown and becomes unusable. 
Relates to: https://github.com/ballerinalang/composer/issues/4559

[issue.txt](https://github.com/ballerinalang/composer/files/1486647/issue.txt)

![issue3](https://user-images.githubusercontent.com/15624590/33005414-b659f6ec-cdeb-11e7-9d73-55a56a03782d.png)

**Comment by keizer619** [comment]
This is a white space issue. White space in function header is getting removed when adding a new function. The previous function body should have a field accessing from an array element. This can be easily reproduced with following code piece.

`function new(){
    myArray[0].status;
}`

**Comment by erandidesilva** [comment]
When a new function get added, as mentioned above the issue occurs. From the user's perspective, this is blocking his usage.

![issue_10](https://user-images.githubusercontent.com/15624590/33064852-1a05888c-cecd-11e7-8132-6a19ae49e200.png)

**Comment by hevayo** [comment]
Fixed in 0.95.3
