### ISSUE TITLE
[Design view] Remove unwanted suggestions being popped up

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4676]
Currently when typing in http: , a list of suggestions that are not applicable pops up. It's better to remove these unwanted suggestions as it will be disrupt for the user. Either we must give appropriate suggestions or not give anything at all.

![issue_7](https://user-images.githubusercontent.com/15624590/33060536-93aa93b2-cebe-11e7-9d0d-8d646ae115e3.png)

**Comment by nadeeshaan** [comment]
This issue has been addressed at #4696. Hence closing the issue
