### ISSUE TITLE
[Design view] Cannot make a function public, wrong syntax is given

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4677]
As shown in the below image, when trying to make a function public by design view, it results in an error as the generated syntax is wrong.

![issue_8](https://user-images.githubusercontent.com/15624590/33060821-99b945d6-cebf-11e7-9f43-ec3c93b7d5b1.png)

**Comment by keizer619** [comment]
This is a whitespace issue caused when we make public where there is a space within brackets as in following sample code piece

``` ballerina
function function1(  ){
}
```
