### ISSUE TITLE
Cannot scroll the Globals pane

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4685]
**Description:**
The globals value pane cannot be scrolled nor automatically expanding

![1](https://user-images.githubusercontent.com/1845370/33069939-357c6b30-cedc-11e7-8f9d-79647f41b8e2.png)

**Comment by NatashaWso2** [comment]
If the variable declaration is too long, we truncate it and show a part of it and on hover in the tooltip the entire variable declaration is shown.
