### ISSUE TITLE
Language Server completions/suggestions/resolving for constructs

### ISSUE THREAD

**Issue by NatashaWso2** [ballerinalang/composer#4696]
**Description:**
Providing correct code completions/suggestions for constructs both in the source view and design view.

Suggestions should be provided for the following : 

- [x] Config properties of services, resources and connectors
- [x] Packages
- [ ] Argument Parameters
- [x] Return types
- [x] Imports
- [x] Global variables and  service and connector level variables
- [x]  Function Invocations
- [x] Named Returns
- [x] Struct properties
- [x] Action invocations
- [ ] Anonymous Structs
- [x] Transformer
- [ ] Errors in Try-Catch
- [x] Boolean values : true/false
- [x] Else construct
- [ ] Service and resource level annotations
- [ ]  Parameter and Connection Properties for endpoints and connector declarations
- [ ] Variables for the conditions of If, While
- [ ] Json arrays
- [x] Enum attributes
- [ ] Package level property and parameter resolving
- [ ] Workspace level renaming
- [ ] Content support for Lambda 
- [x] Expression editor content completion support

**Related Issues:**
https://github.com/ballerinalang/composer/issues/4547
https://github.com/ballerinalang/composer/issues/4032
https://github.com/ballerinalang/composer/issues/3855
https://github.com/ballerinalang/composer/issues/3591
https://github.com/ballerinalang/composer/issues/3471
https://github.com/ballerinalang/composer/issues/2722
https://github.com/ballerinalang/composer/issues/2469
https://github.com/ballerinalang/composer/issues/2446
https://github.com/ballerinalang/composer/issues/4689
https://github.com/ballerinalang/composer/issues/3485
https://github.com/ballerinalang/composer/issues/4614
https://github.com/ballerinalang/composer/issues/4423
https://github.com/ballerinalang/composer/issues/4417
https://github.com/ballerinalang/composer/issues/3800
https://github.com/ballerinalang/composer/issues/3616
https://github.com/ballerinalang/composer/issues/3473
https://github.com/ballerinalang/composer/issues/3459
https://github.com/ballerinalang/composer/issues/3376
https://github.com/ballerinalang/composer/issues/3365
https://github.com/ballerinalang/composer/issues/2838
https://github.com/ballerinalang/composer/issues/2830
https://github.com/ballerinalang/composer/issues/2826
https://github.com/ballerinalang/composer/issues/2399
https://github.com/ballerinalang/composer/issues/2398
https://github.com/ballerinalang/composer/issues/2369
https://github.com/ballerinalang/composer/issues/3502
https://github.com/ballerinalang/composer/issues/4631
https://github.com/ballerinalang/composer/issues/4143
https://github.com/ballerinalang/composer/issues/2445
https://github.com/ballerinalang/composer/issues/4729
https://github.com/ballerinalang/composer/issues/4441
https://github.com/ballerinalang/composer/issues/3444
https://github.com/ballerinalang/composer/issues/315

**Suggested Labels:**
Language Server, Content-Assist,  Task

**Comment by NipunaMarcus** [comment]
move the issue to language server repository as language features are now handled from language server.
https://github.com/ballerinalang/language-server/issues/105.
