### ISSUE TITLE
Support workspace wide rename (ie. function, transform rename) capability.

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4729]
**Steps to reproduce:**
1. Open the transform sample
2. Add a name to the transform block

**Issue**
The error as in the screen shot will be prompted to the user
![6](https://user-images.githubusercontent.com/1845370/33207759-ec4174e6-d134-11e7-9459-3d982af54713.png)

**Comment by roonyh** [comment]
This is like renaming a function. When a function is renamed all its invocations will give a similar error.

When a transformer is renamed, need to find the transformer invocations and change them too.
In this case the invocation should be,
```ballerina
u = <User, myTrans()> p;
```

This will be fixed when the [rename capability](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_rename) is added to the language server.

**Comment by NipunaMarcus** [comment]
This is tracked with language server new implementation task hence closing this issue.
