### ISSUE TITLE
Renaming an opened file will result in endless file switching loop

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4749]
**Description:**
Renaming an opened file result to swap the focus on opened files.
https://drive.google.com/file/d/1o36O4pulktfFBezo3yGpfMluIkj_C5rM

**Affected Product Version:** 0.95.1

**OS, DB, other environment details and versions:**    Chrome 62.0/OSX 10.13.1

**Steps to reproduce:**
- Open multiple files
- Now select one file and rename the same
- Observe the swapping as in description

**Comment by kaviththiranga** [comment]
Fixed with 454bcd6298dc0e84bc416516fd18366e113b3d61
