### ISSUE TITLE
Comments are hard to read in source view due to color (dark grey)

### ISSUE THREAD

**Issue by robbla** [ballerinalang/composer#4758]
The standard Ballerina environment is dark grey in source mode. the comments are in slightly less dark gray and therefor hard to read. can we have a different color setting?
![afbeelding](https://user-images.githubusercontent.com/11582659/33371382-d082759c-d4fa-11e7-9037-696d8bdb25ff.png)
 

   // Create an empty Ballerina message.
    jms:JMSMessage queueMessage = jms:createTextMessage(getConnectorConfig());
    // Set a string payload to the message.

**Comment by nadeeshaan** [comment]
Hi @robbla,
in the latest master, we have made the comments much lighter and much clearer to visible. Hence closing the issue.
