### ISSUE TITLE
No split view button from source view

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4761]
**Description:**
Considering the user behaviour, users might want to switch to split view from source view as well. Hence, we must provide the capability from source view. Not just from design view. 

**Affected Product Version:** 0.95.1

**OS, DB, other environment details and versions:**   N/A 

**Steps to reproduce:** N/A

**Related .bal file source** N/A

**Related Issues:** N/A

**Comment by hevayo** [comment]
fixed in 0.95.7
