### ISSUE TITLE
Connector instance variable should be able to view in the argument list of 'Action'

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#477]
For the action's argument, relevant connector variable needs to be added to the drop down (either custom or as editable list). Currently it is not available in the list (see attached)

![connector_argument](https://cloud.githubusercontent.com/assets/15671620/22853740/fe95d8c2-f083-11e6-97d9-093e190f98b0.jpeg)

**Comment by nadeeshaan** [comment]
Resolved with #1306
