### ISSUE TITLE
Group builtin package by type

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4784]
**Description:**
Currently, built in package is too long and looses the meaning other than being a long list. Good if we can introduce a grouping, probably by the bound type.

One example is 'isSingleton' function. Looking at the name in the tool palette has no meaning at all. This is function attached to XML type. Showing that information is useful.

<img width="206" alt="image" src="https://user-images.githubusercontent.com/1029806/33551663-19982c6a-d918-11e7-9168-7ee5f0704918.png">

**Affected Product Version:** 0.95.3

**OS, DB, other environment details and versions:**  N/A  

**Steps to reproduce:** N/A

**Comment by hevayo** [comment]
implementation has differed tool palette was removed from 0.95.6
