### ISSUE TITLE
The 'typeof' operator to BuiltInTypeName or UserDefinedTypeName is not supported

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerinalang/composer#4793]
**Description:**
The typeof operator for BuiltIn Type Name or  User Defined Type Name is introduced to language with the PR https://github.com/ballerinalang/ballerina/pull/3853

Currently this is not supported by the composer. We need to support this as a language feature and also this is will be used in connector APIs.

**Affected Product Version:**
Ballerina 0.95.3

**Comment by maheeka** [comment]
Also check operator tool palette in transformer with this change.
