### ISSUE TITLE
Documentation not working - 404

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4794]
**Description:**
Clicking on library documentation gives 404.
<img width="808" alt="image" src="https://user-images.githubusercontent.com/1029806/33609068-afa290ae-d9ec-11e7-94fc-f189e49a1fcf.png">

**Affected Product Version:** 0.95.3

**OS, DB, other environment details and versions:**    
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
macOS - 10.13.1 (17B1003)

**Steps to reproduce:**
 - Create a new bal file
 - Click on documentation icon of any function in the library

**Comment by NipunaMarcus** [comment]
Checked this with Ubuntu 14.04 and macOS - 10 with a pack built using the latest master and showing docs works fine. 
![docs working](https://user-images.githubusercontent.com/9109762/33644908-ee9eb6ee-da6d-11e7-9685-5bd6be32bdd0.png)

Is there any error on the back end? did you build the latest docerina master?

**Comment by NipunaMarcus** [comment]
This is working in latest master hence closing this issue.
