### ISSUE TITLE
Generating connector definition from design

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4844]
**Description:**
During the design phase, consider the following workflow.

- User drags in a generic endpoint
- Draw action invocations for that endpoint

Essentially, the actions provide the interface for the connector that is used to define the endpoint. 

Therefore, we should provide a way to generate the connector definition when designing the ballerina program with generic endpoints.

**Comment by maheeka** [comment]
Fix the following issue, when the invocation contains a non-existing endpoint.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1029806/34032638-1e5801d4-e19d-11e7-82ee-2bf315f6e9bc.png">

**Comment by hevayo** [comment]
Feature available with 0.96.8
