### ISSUE TITLE
If icon not visible in add menu

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#4957]
**Description:**
If icon is missing in [+] menu.
<img width="237" alt="image" src="https://user-images.githubusercontent.com/1029806/35028252-20141a74-fb7b-11e7-8a44-860568e048ee.png">

**Affected Product Version:** 0.95.7

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
- Add a function
- Click on + button on lifeline

**Comment by keizer619** [comment]
If Icon is visible in the latest pack

<img width="266" alt="screen shot 2018-01-24 at 11 40 33 am" src="https://user-images.githubusercontent.com/2918812/35319820-80349078-0107-11e8-8f07-27b6cf83b423.png">
