### ISSUE TITLE
Composer (0.95.7) home page - copyright points to 'Ballerina Composer v0.93'

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/composer#4992]
**Description:**
Copyright text still points to 'Ballerina Composer v0.93'

**Affected Product Version:**
0.95.7

**Related Issues:**
Created this to track: https://github.com/ballerinalang/ballerina/issues/4456

**Comment by kaviththiranga** [comment]
This was an issue with page cache and fixed with https://github.com/ballerinalang/composer/pull/4984
