### ISSUE TITLE
Cannot decrease the size of the location panel after a certain point

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#533]
Please see the attached image. The size cannot be decreased after the shown point
Browser: Chrome: 
![editor_afterm4_bug1](https://cloud.githubusercontent.com/assets/15624590/22874737/cb93a6aa-f1ed-11e6-8299-fc5dc5028e74.png)
54.0.2840.100 (64-bit)

**Comment by hevayo** [comment]
This is a feature since we do not want to completely hide the file browser panel. Also by clicking on the browse icon user can toggle the said panel thus if panel is taking up space user can collapse it if required. 

Closing the issue as per the above explanation.
