### ISSUE TITLE
Compilation level errors are validated only in Source view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#535]
Currently in editor, the compilation level errors are validated in source view against save. Please note that this is only done in source view which is two different behaviours and design view become inaccessible afterwards.

**Comment by NipunaMarcus** [comment]
As to the current design user will be able to see the issues on source view and user won't be able to move to the design view without fixing them. Validating the source has done upon on text change in source view. This is the current design for now hence closing this issue.
