### ISSUE TITLE
Source view suggestions are not consistent

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#542]
In editor, currently source view suggestions are given which is not comprehensive.

E.g.@PUT
@Path ("/invoke")
    resource httpMethodTestResource(message m) {
        message response = {};
        http:ClientConnector ep_1 = create http:ClientConnector ("http://ip:9793/jaxrs_starbucks_service/services/Starbucks_Outlet_Service");
        response = http:ClientConnector.put(ep_1, "/orders", m);
        reply response;
    }
}

Here suggestions will consist of PUT, httpMethodTest and the local names already used. If I try add another method say @DELETE, it will not give suggestions, and does not give suggestions for inbuilt functions as http:put as well. 

Rather than having inconsistent suggestions, its better to remove it entirely if it cannot be supported within the given time frame

**Comment by maheeka** [comment]
Implementation deferred. This issue is fixed now.
