### ISSUE TITLE
Empty else block is added if there is no else block

### ISSUE THREAD

**Issue by malinthaadikari** [ballerinalang/composer#565]
Steps: Deserialize and serialize following source code

`
function sum(int a)(int ) {
	int x;
	if (a > 0) {
		x = sum(a - 1);
		a = a + x;		
	}
	return a;	
}
`
gives following source code

`
function sum(int a)(int ) {
	int x;
	if (a > 0) {
		x = sum(a - 1);
		a = a + x;		
	}
	else {
		}return a;	
}
`

**Comment by nadeeshaan** [comment]
Related #137
