### ISSUE TITLE
First service on canvus @ pop up does not close when clicked else where in the workspace

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#568]
Tested on: 375a3190af3bb84c8737d89040ef7bd966190268
The @ pop up doesn't get closed when clicking else where in the canvus for the very first service on it. For subsequent services, the @ pop up get closed when clicked else where on the canvus

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master. Hence closing
