### ISSUE TITLE
[Blocker] Adding a swagger definition does not generate the source code

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#577]
Pack - M4
Browser - Firefox 51.0.1

1. Add a swagger definition as below
swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Resource
basePath: /echannelService
paths:
  /checkAvailability:
    post:
      parameters: []
      responses:
        '200':
          description: Successful
          examples:
            application/json: Ok

2. Switch to the source view (cannot navigate to the design view which is reported in another issue)

Issue
The source code is not generated from swagger definition

**Comment by hevayo** [comment]
Fixed in 0.88
