### ISSUE TITLE
Reformat code shortcut locks the monitor

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#579]
Pack - M4
Browser - Firefox 51.0.1
OS - Ubuntu

Reformat code shortcut key (ctrl +Alt + L) locks the monitor.

**Comment by nadeeshaan** [comment]
This is a standard key combination for code formatting. Editors such as Intellij Idea uses the same key combination. The conflict is that Ubuntu has mapped this key combination to lock screen. 
Alternative is either we allow the key mapping in the editor or in the Operating system. Currently we do not allow the key map configuration in the editor. So you can change the key map in the Operating system to avoid the conflict. 
Hence Removing the Label for Bug and this will be addressed as a feature/ enhancement in the future.

**Comment by dakshika** [comment]
This is fixed in latest master. 

new shortcut key handler map to Ctrl + Shift + L
