### ISSUE TITLE
Reformat code indentation and spacing issues

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#581]
Pack - M4
Browser - Firefox 51.0.1

1. The spaces we keep between the imports and the methods, two services, two methods, two variables get adjusted when we reformat the code. Even if we want to have spaces in between intentionally, we can't have it.
2. Indentation issues as in the screen shots.

![ind2](https://cloud.githubusercontent.com/assets/1845370/22915386/d58eb1ea-f29c-11e6-99cb-b1f92d369cef.png)
![ind1](https://cloud.githubusercontent.com/assets/1845370/22915387/d5912a06-f29c-11e6-8e0b-661f1e59f2d5.png)

Expected
IMO Indenting the code will be sufficient for this feature

**Comment by kaviththiranga** [comment]
All formatting issues are now fixed with new implementation of formatting which is based on a parsed AST.
