### ISSUE TITLE
Files not displayed on Open File modal when saved on root directory. 

### ISSUE THREAD

**Issue by erangatl** [ballerinalang/composer#583]
- Save file in the root directory (D:\)
- File is not displayed in the Open File tree view  

![image](https://cloud.githubusercontent.com/assets/20179540/22915997/3dd7f3e8-f2a1-11e6-8f49-d39fddf89034.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2122
