### ISSUE TITLE
Hover state in the resource is not visible

### ISSUE THREAD

**Issue by srsharon** [ballerinalang/composer#590]
![screen-shot-2017-02-14-at-11 47 59-am-1](https://cloud.githubusercontent.com/assets/10986966/22917745/97989a1c-f2ac-11e6-95f5-e99181e877b1.png)

**Comment by maheeka** [comment]
Fixed in new view

<img width="393" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/26510023/f85aa270-4278-11e7-8d63-a3a861b9382e.png">
