### ISSUE TITLE
Swagger definition doesn't added if two or more annotation added

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#602]
- Add a service and more methods to resource[1]. 
- Swagger view doesn't show resource definition for both methods and also Resource page shows one method[2].
- Add method one by one and navigate each time to swagger view, same issue in the swagger definition[3]; but resource page shows both methods.

[1]
![2annot](https://cloud.githubusercontent.com/assets/15671620/22921539/2630e5c8-f2c0-11e6-9384-d977c9290620.jpeg)
[2]
![anoot3](https://cloud.githubusercontent.com/assets/15671620/22922068/2e618fc0-f2c2-11e6-8f5e-100dafac9636.jpeg)

[3]
![annot2](https://cloud.githubusercontent.com/assets/15671620/22921545/292169a6-f2c0-11e6-826c-7a057d760d48.jpeg)

**Comment by hevayo** [comment]
With the new implementation we will only support one method for a given resource, hence closing the issue.
