### ISSUE TITLE
[Intermittent] Delete button in the resource panel is not visible

### ISSUE THREAD

**Issue by srsharon** [ballerinalang/composer#608]
<img width="1168" alt="screen shot 2017-02-14 at 3 19 23 pm" src="https://cloud.githubusercontent.com/assets/10986966/22923879/176d1224-f2c9-11e6-8e8e-0e4bc32eadf8.png">

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master. Hence closing the issue
