### ISSUE TITLE
[Improvement] Support for drag and drop for calling function inside the conditional statements

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#620]
We could observe a usability issues while doing usability test:
1. When user wants to have a function call inside the 'if' or 'while' statements 
e.g. if ( string:equalsIgnoreCase(httpMethod, "GET") ) - the first try was drag and drop into the condition 
Shouldn't we support above?

2. When a variable assigned to function which will be return (user defined function) 
e.g. string testHeader = constructHeader(consumerKey, title) - first try was drag and drop function from current package into assignment statement 
 Shouldn't we support above?

![fun1](https://cloud.githubusercontent.com/assets/15671620/22933516/d7038a0a-f2f1-11e6-9b70-5caf173deff4.jpeg)

**Comment by hevayo** [comment]
On a general note the direction we are heading now is to give source editing for workers ( statement inside workers ). A better way to overcome the usability issue mention here is to give completion in each of the scenarios.
