### ISSUE TITLE
Selecting a package import should add that as import statement

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#628]
At the moment, when you type a package in package import section, it gives suggestions. Clicking the suggestion adds it to the text box. then I have to select '+' button again to import. Shouldn't selecting the suggestion import straightaway?

**Comment by dakshika** [comment]
I think this issue is no longer valid with latest version

**Comment by dakshika** [comment]
The latest version supports for this. hence closing the issue
