### ISSUE TITLE
Going to source view and editing something and returning to graphical view collapses the package definition

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#640]
Steps:
Enter a package and keep it open. 
Go to source view. Edit something (add space and remove space)
Go to graphical view. 
Package definition is closed. 

Can we remember the previous state and bring it back if the corresponding section is not modified?

**Comment by nadeeshaan** [comment]
This has been addressed with the latest design decision of allowing the package to be visible all the time, if the package is not empty. Hence closing
