### ISSUE TITLE
Can we show the path and methods if the annotations are given? 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#642]
Like shown in the picture. Any concern from UX point of view? 
![screen shot 2017-02-15 at 10 23 23 am](https://cloud.githubusercontent.com/assets/2410076/22961093/6aae12a8-f369-11e6-89ec-25334eba40d5.png)

**Comment by dakshika** [comment]
@srsharon : Can you have a look on this?

**Comment by srsharon** [comment]
Hi @uthaiyashankar @dakshika we have changed the annotation view like in the image below. This has fixes for some of the areas pointed out. This is being implemented by @hemikak   
![image](https://cloud.githubusercontent.com/assets/10986966/25605747/c5c696f4-2f2a-11e7-9f15-544f6e53c27f.png)

**Comment by hemikak** [comment]
Updated the view as per @srsharon 's design.
<img width="424" alt="screen shot 2017-05-23 at 12 47 07 pm" src="https://cloud.githubusercontent.com/assets/4398820/26342519/06cc61ba-3fb6-11e7-88e5-582d20c27698.png">

Hence, closing.
