### ISSUE TITLE
Can we not show the suggestion if the package is already imported? 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#647]
for example, in the following screenshot, ballerina.lang.message is already imported. Showing that as one of the suggestion is not needed. We can show other packages and use the real estate. 
<img width="787" alt="screen shot 2017-02-15 at 10 52 32 am" src="https://cloud.githubusercontent.com/assets/2410076/22961560/05286e70-f36d-11e6-810f-00b0cede9232.png">

**Comment by hevayo** [comment]
Duplicate with #1682 since the implementation has changed I will close this issue.
