### ISSUE TITLE
Empty Document Error when navigating to the swagger view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#649]
1. Create a new file. (don't add anything)
2. Navigate to the swagger view. Warning message shows to the user.
3. Navigate to the design view
4. Navigate to the swagger view again

Issue
Now an error message shows as "Empty Document Error" which was not shown in step 2. If you repeat step 3 and 4 again, the error message will disappear suddenly and the warning will be showed. This is not consistent

**Comment by hevayo** [comment]
From 0.87 if the bal program do not have a service the editor will not allow to switch to swagger view.
