### ISSUE TITLE
Different behaviour for defining string in constant and variables

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#652]
For constant definition, we  shouldn't give double quotes (if we give, generated code will also put a double quote and will endup in const string foo = ""bar"";

For variable definition in services, we should give double quote. 

This is inconsistent behaviour. Can we have the same behaviour for variable as well?

**Comment by roonyh** [comment]
This can be closed. In current master we use the fragment parser in both variable and const/globad var definition UIs. So they behave the same expected way now.
