### ISSUE TITLE
For constant definition (and for variable definition), can we check the double quote before generating the source?

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#654]
Please see #652 as well

This improvement is to take "bar" as well as bar (without quote) as valid string in graphical view. When generating code, check whether the string already have a start and end quote and not generate additional quote if it already has. 

Also, if the string has quote or double quote in the middle, we should escape them as well when generating the code.

**Comment by maheeka** [comment]
Since the UI for creating constants is now an expression editor, users must type the constant with correct quotations. Hence closing this issue.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1029806/32717360-4e6b249c-c851-11e7-980a-4e62d382269f.png">
