### ISSUE TITLE
unable to scroll right to delete imports when more than 5 imports exist

### ISSUE THREAD

**Issue by shavantha** [ballerinalang/composer#657]
unable to scroll right to delete imports when more than 5 imports exist

steps
1.add more than 5 imports
Note: each are stacked to the right
2.attempt to delete the right most imported package
Note: at this point I had to delete the one before the last  import package before deleting the last one. Refer the file "unable_to_scroll_right" I had to delete ballerina.lang.map before I was able to delete ballerina.net.http
![unable_to_scroll_right](https://cloud.githubusercontent.com/assets/6552100/22962568/977a3636-f373-11e6-860f-9221d97187ff.png)

**Comment by nadeeshaan** [comment]
Fixed with the current vertical expand of the imports pain. Hence closing
