### ISSUE TITLE
[Tooling] There is no way to delete connection/arrows alone

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#66]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Sunday Jan 08, 2017 at 05:43 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/653_

----

Currently we need to delete the connector operation to delete the connection/arrow. There should be a way to delete the connection alone.

**Comment by nadeeshaan** [comment]
Since the arrow deletion requirement has been addressed as aforementioned by Shankar, we are closing this issue. This is because the design decision was not allow the user to delete the arrows, instead we allow them  to reconnect them to different destination
