### ISSUE TITLE
imports not validated by editor to determine if they are ballerina scope specific

### ISSUE THREAD

**Issue by shavantha** [ballerinalang/composer#661]
imports not validated by editor to determine if they are ballerina scope specific

1.add an import statement for any type ex:jenkins.model.Jenkins;
2.the editor seems to add the package. Ideally only ballerina specific packages imports should be allowed

**Comment by dakshika** [comment]
related issue https://github.com/ballerinalang/composer/issues/287

**Comment by maheeka** [comment]
Resolved as explained  in https://github.com/ballerinalang/composer/issues/287
