### ISSUE TITLE
Shadow when importing the packages

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#666]
commit 2d51a8c9cd82e59db134545342d6c4a06f899d58
Browser - Firefox
OS - Ubuntu

![shadow](https://cloud.githubusercontent.com/assets/1845370/22964043/82b4c1ea-f37c-11e6-82bb-26663fde5818.png)

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/1232
