### ISSUE TITLE
[Tooling] Securing Ballerina editor related MSF4J services

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#67]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Sunday Jan 08, 2017 at 08:21 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/654_

----

**Comment by hevayo** [comment]
For 0.89 release we will bind the services for localhost.
