### ISSUE TITLE
Cannot add multiple MIME types for Consumes and Produces

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#700]
1. Add multiple MIME types for Consumes and Produces as follows
@Consumes({"application/json", "application/xml"})
@Produces({"application/json", "application/xml"})
2. Switch to the swagger view or design view

Issue
Only one MIME type will be displayed in the swagger definition/design view and also in source view once switched back

**Comment by nadeeshaan** [comment]
This is is on hold due to the swagger related revamping.

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/2406/
