### ISSUE TITLE
Why do we need annotations for connector action definition?

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#702]
At the moment, we can't do anything. Can we remove the annotation from connector action? 

Or this is something we will enable in future? 
<img width="1117" alt="screen shot 2017-02-15 at 8 22 35 pm" src="https://cloud.githubusercontent.com/assets/2410076/22979553/d1160c3c-f3bc-11e6-882e-b78da2a7fed1.png">

**Comment by hevayo** [comment]
Annotations for connector and action are supported currently by language. see[1]

[1] https://github.com/ballerinalang/ballerina/blob/bf3ac26b48e64c901ee3a56c1d106ac35f865230/docs/grammar/Ballerina.g4#L94-L95
