### ISSUE TITLE
Cannot navigate to both design and swagger view when there is a comment

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#721]
1. Add a service and a connector
2. Comment the connector declaration
3. Try to navigate to the design and swagger view

Issue
Cannot navigate to the design view. Error message prompts when tried to navigate to the swagger view

![error](https://cloud.githubusercontent.com/assets/1845370/23011346/878c9358-f446-11e6-9cd0-e7b84979ab78.png)

**Comment by nadeeshaan** [comment]
Issue is fixed in the current master. Hence closing the issue
