### ISSUE TITLE
Debugger & Launcher Improvements

### ISSUE THREAD

**Issue by hevayo** [ballerinalang/composer#723]
- [x] Only allow to add debug points if the working file is saved. 
- [x] **Variables and frames need to be merged together in the debug view.**
- [x] When a file is closed remove all the debug points from debug manager. 
- [x] Improve debug point close in design view make it more intuitive.
- [x] **Implement service and application shutdown.**
- [x] Allow passing of arguments to main method.
- [x] General debug styles ie. debug button hover. 
- [x] When a service it started give a try it button in run and debug view. 
- [x] Allow minimizing / reopen / resize console.
- [x] Move launcher port to system properties.

**Comment by pahans** [comment]
#1 is done but need some testing because `file.isDirty` logic changed after implementing it.

**Comment by hevayo** [comment]
fixed in 0.94
