### ISSUE TITLE
Switching between views are not appearing in editor - Edge browser

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#728]
see attached. Used build from master 16-Feb (aa9e72394ac2c1e8cd7c9618ba531437dbef9379)

![edge](https://cloud.githubusercontent.com/assets/15671620/23014030/4ec74c72-f453-11e6-80d7-b3c177982ff1.jpeg)

**Comment by hevayo** [comment]
Implementation of the composer has differed closing this issue since a duplicate of 
https://github.com/ballerinalang/composer/issues/2460
