### ISSUE TITLE
Issues related to importing packages

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#730]
1. All imports are not listed when only "bal" is typed
![screenshot from 2017-02-16 14-29-37](https://cloud.githubusercontent.com/assets/1845370/23014309/80968834-f454-11e6-9607-c32faba9954e.png)

2. When one import is added, it will be displayed in the text box when trying to add another one.
![screenshot from 2017-02-16 14-29-04](https://cloud.githubusercontent.com/assets/1845370/23014347/9ce6dce6-f454-11e6-9aaf-3ed5273129ca.png)

**Comment by hevayo** [comment]
Implementation has differed hence closing the issue.

Please find a new list of issues with the import controller in #1682.
