### ISSUE TITLE
Need a horizontal scroll bar for the editor

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#732]
Browser : Firefox
commit 36675f2b982cd688afae1c8e9f4ff626a373092a

1. Cannot scroll horizontally
![scrollbar1](https://cloud.githubusercontent.com/assets/1845370/23014928/f60d80ca-f456-11e6-9bfd-e50a09740009.png)

2. Need to manually drag the scroll bar of resources horizontally
![scrollbar3](https://cloud.githubusercontent.com/assets/1845370/23014927/f60ac196-f456-11e6-9eb8-b44f99952a00.png)

**Comment by hevayo** [comment]
From 0.87 scroll will appear for the entire diagram, and there will be a horizontal scroll bar if the diagram width is larger than browser window.
