### ISSUE TITLE
[Tooling] Export diagram as an image option

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#74]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Monday Jan 09, 2017 at 07:17 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/674_

----

When we have a large diagram, we cannot just get a screenshot of the whole diagram. In that case we need a diagram image export option. (as a .png or .jpg etc)

**Comment by pahans** [comment]
For this we might have to read DOM and draw DOM representation in a HTML canvas image. https://html2canvas.hertzen.com/

**Comment by NipunaMarcus** [comment]
This feature has been implemented and it imports a image.
