### ISSUE TITLE
Elements can be dropped into 'typeconvertor' in graphical

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#741]
- Drag and drop a typeconvertor
- Try to drag and drop elements in side of it (e.g. if, assignment, variable, while, try-catch, callfunction)
In graphical view doesn't show but source view elements are added (see attached)

![ele](https://cloud.githubusercontent.com/assets/15671620/23019294/9fc8a24c-f467-11e6-88cc-02b464a50127.jpeg)

**Comment by TanyaM** [comment]
This issue is no longer there in RC2

**Comment by nadeeshaan** [comment]
Tested in the latest master and this issue has been resolved. Hence closing
