### ISSUE TITLE
Improve menu controller to add external contributors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#75]
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Jan 10, 2017 at 05:52 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/690_

----

Right now the menu controller is static - that is after initialization, it will stay the same. However, someone should be able to alter menu's state externally on demand.

 Eg, depending on the active tab,
           -   enable/disable a menu item
           -   add new menus 
           - change menu title - for redo/undo  display what's going to undo/redo

**Comment by hevayo** [comment]
Done with plugin implementation on 0.9.4
