### ISSUE TITLE
Make constant and imports expanded when clicking open arrow, if there are no constants / imports defined already

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#764]
Eg.: Instead of 
<img width="136" alt="screen shot 2017-02-17 at 10 03 30 am" src="https://cloud.githubusercontent.com/assets/2410076/23052581/74c77636-f4f8-11e6-812f-ddd488904c37.png">

Make it 
<img width="640" alt="screen shot 2017-02-17 at 10 03 38 am" src="https://cloud.githubusercontent.com/assets/2410076/23052586/7ba4c72e-f4f8-11e6-9724-2e7b03eb6baf.png">

**Comment by nadeeshaan** [comment]
This improvement has been added to the latest master, with the new design. Hence closing
