### ISSUE TITLE
Gap issues in constants, imports

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#765]
<img width="640" alt="screen shot 2017-02-17 at 10 03 38 am" src="https://cloud.githubusercontent.com/assets/2410076/23052616/b9ce81f2-f4f8-11e6-802e-349cc10febef.png">

Note the gap between type and identifier Vs identifier and value

Also, gap between import and text box vs test box and action buttons.

**Comment by maheeka** [comment]
Resolved in new global variable/constant view
<img width="353" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/26481640/2f069672-4200-11e7-9cd1-d549ffae4c2c.png">
