### ISSUE TITLE
Import package in source view listed all keywords for suggestion

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#777]
- Open a new file
- Go to source view and import a package : suggestion list contains all keywords

![import5](https://cloud.githubusercontent.com/assets/15671620/23059353/13a74b84-f51f-11e6-9d06-f9b49556b869.jpeg)

**Comment by roonyh** [comment]
Fixed in current master. 
![image](https://user-images.githubusercontent.com/3872221/28523559-a9097d72-709a-11e7-90cb-5d1bdfbf629e.png)
