### ISSUE TITLE
On Ballerina editor (graphical view) "File > Settings" doesn't work as expected for Safari (Version 10.0)

### ISSUE THREAD

**Issue by Sewmi** [ballerinalang/composer#840]
**Environment**
OS : Mac OS (10.12)
Browser : Safari 10.0

**Steps**
1. Access Ballerina editor using Safari web browser.
2. Select 'File' > 'Settings' in order to open settings.

**Issue**
1. Nothing happens. 

**Expected**
1. Settings window should open.

**Comment by nadeeshaan** [comment]
Checked in the latest master and the issue has been fixed. Hence closing
