### ISSUE TITLE
Cannot expand the folder from file explorer if it has added when first folder hierarchy expanded already

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#841]
- Add folder to file explorer
- Expand the bal file hierarchy (keep expands)
- Add another folder to file explorer
- Click on the secondly added folder expand : all the time first folder get expanded/ collapsed
Issue: cannot expand the second folder from file explorer

![expand](https://cloud.githubusercontent.com/assets/15671620/23090938/16e2e716-f5d0-11e6-9b3b-28aaeee5bb25.jpeg)

**Comment by dakshika** [comment]
Cannot reproduce on latest master 19956702379f9413a48be47f734dd6862be5c4c2
