### ISSUE TITLE
Double clicks are required to open child directories inside a parent directory through File Explorer

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#845]
Built on:b9cf76edd0661dec50e07839d6eab0092cb89c10
Steps
1. Open a parent directory that has multiple child directories (Composer_Bug_openDirectory_1.png)
2. Click on the parent directory -> this will open the next immediate child directory/directories. (Composer_Bug_openDirectory_2.png)
3. After this, for all the subsequent child directories double clicks are required to open. 

This behaviour is contradictory and inconsistent
![composer_bug_opendirectory_1](https://cloud.githubusercontent.com/assets/15624590/23091026/509032f0-f5d2-11e6-9384-a2da4b214419.png)
![composer_bug_opendirectory_2](https://cloud.githubusercontent.com/assets/15624590/23091027/50edb402-f5d2-11e6-839a-5589d37ea3a0.png)

. Either it should be a single click for all or double click for all

**Comment by dakshika** [comment]
Fixed
