### ISSUE TITLE
[Editor] Annotation Pane and Argument pane for Resources does not position when multiple connectors are added.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#85]
<a href="https://github.com/hemikak"><img src="https://avatars.githubusercontent.com/u/4398820?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hemikak](https://github.com/hemikak)**
_Saturday Jan 14, 2017 at 07:53 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/772_

----

![image](https://cloud.githubusercontent.com/assets/4398820/21953428/94974696-da5c-11e6-98e8-94fd732c7ac7.png)

**Comment by sumuditha-viraj** [comment]
PR #1177

**Comment by sumuditha-viraj** [comment]
Fixed with #1177

**Comment by sumuditha-viraj** [comment]
Fixes regarding connector action editor panes is with PR #1189
