### ISSUE TITLE
Warn the user of the limitation with reagard to packages when running

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#852]
Since there is a limitation to support packaging in Composer, shall we warn the user of it before running. This will help increase user experience.
![composer_bug_run_1](https://cloud.githubusercontent.com/assets/15624590/23091243/700dd9ca-f5d7-11e6-8a0a-cd609e40ca35.png)

**Comment by pahans** [comment]
fixed with fixed with https://github.com/ballerinalang/composer/pull/1821
