### ISSUE TITLE
Provided open file shortcut in Ballerina editor (graphical view) opens system file browser.

### ISSUE THREAD

**Issue by Sewmi** [ballerinalang/composer#854]
**Environment**
OS: Mac OS (10.12.3 )
Browser: Safari Version 10.0.3 

**Issue**
Provided open file shortcuts in Ballerina editor (graphical view) opens system file browser instead of opening file browser provided by Ballerina.

**References**  

1. Expected Result

<img width="1436" alt="ballerina-open-file-window" src="https://cloud.githubusercontent.com/assets/7960586/23091336/c399dbe6-f5d9-11e6-8336-fd7a6f8ddfd4.png">

2. Actual Result

<img width="1437" alt="system-file-window" src="https://cloud.githubusercontent.com/assets/7960586/23091340/d6721116-f5d9-11e6-8694-a17fefa49548.png">

**Comment by dakshika** [comment]
closing due to similar duplicate
