### ISSUE TITLE
Delete button turns to be a grey square when user clicks inside a function and then clicks outside the function. 

### ISSUE THREAD

**Issue by Sewmi** [ballerinalang/composer#857]
**Environment**

OS: Mac OS (version 10.12.3)
Browser: Safari (varsion 10.0.3 )

**Steps**
1. Access Ballerina editor (graphical view)
2. Add a service
3. Add an argument for the created resource.
4. Add a function invocation (note that this is not specific to functions you can also add an    assignment)
5. Click on the added function and then click outside the function. 

**Actual outcome**
1. In step 5 delete button will change to a gray box (see reference1)

**Reference**
<img width="1434" alt="reference1" src="https://cloud.githubusercontent.com/assets/7960586/23091781/f88321be-f5e3-11e6-9dea-576b9cf893f2.png">

**Comment by hevayo** [comment]
With the new diagram implementation this is no longer reproducible.
