### ISSUE TITLE
When deleting a resource having arguments section is expanded, argument sections remains even without the resource.

### ISSUE THREAD

**Issue by Sewmi** [ballerinalang/composer#859]
**Environment**

OS: Mac OS (version 10.12.3)
Browser: Safari (varsion 10.0.3 )

**Steps**

1. Access Ballerina editor (graphical view)
2. Add a service
3. Add an argument for the created resource. 
4. Expand arguments on the resource.
5. Delete resource while the argument window is expanded.

**Actual outcome**

Without the resource that the added arguments belong to arguments section remains undeleted. 
Also note that only way to recover this is deleting the whole service and adding it again. 

**Reference**

<img width="1402" alt="after-deleting-resource" src="https://cloud.githubusercontent.com/assets/7960586/23092084/657041b2-f5e9-11e6-8255-7e482ff3dd05.png">

**Comment by nadeeshaan** [comment]
This has been fixed in the latest Master. Hence closing
