### ISSUE TITLE
XML variable definition cannot be added with value contains XML prolog 

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#860]
XML variable definition with XML prolog value is not added correctly in both graphical and source view.
- Drag and drop a variable definition
- Edit it for xml variable with complex value [1] and enter : It has added successfully
(e.g. xml myxml=`<emp><name>Chaminda Jayawardena</name><address><no>371/D/6</no><city>Robert Gunawardena Mw.,Battaramulla</city><country>Sri Lanka</country></address></emp>`)
- Edit it with a value contains XML prolog [2] and enter : It has removed the part of value [3] 
(e.g. xml payload=`<?xml version="1.0" encoding="UTF-8" ?>
      	   <name>kavitha</name>`)

[1]
![xml3](https://cloud.githubusercontent.com/assets/15671620/23092469/90cfc3ca-f5f1-11e6-964b-6b3b6ad81aa4.jpeg)
[2]
![xml](https://cloud.githubusercontent.com/assets/15671620/23092021/7d209cd6-f5e8-11e6-9cd9-94d19fc452d2.jpeg)
[3]
![xml2](https://cloud.githubusercontent.com/assets/15671620/23092022/7fe743ca-f5e8-11e6-88ea-72ed84782d7c.jpeg)

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing. Please re open if the issue further reproduces
