### ISSUE TITLE
Cannot drag and drop a http connector inside the worker

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#864]
- Add a service
- Add a worker
- In side the worker add http connector 
Issue: Graphical view is blocking to add. 
- But when drop a connector in resource, it has been added on top of the worker(see attached)
: this is not supported from ballerina core syntax - and we should define everything below the worker block

![after](https://cloud.githubusercontent.com/assets/15671620/23092310/cb60fd6e-f5ed-11e6-8484-ca9b0b9b5cc5.jpeg)

**Comment by nadeeshaan** [comment]
This is due to the limitation of representing the worker declaration inside a worker, currently we have not finalized the representation

**Comment by nadeeshaan** [comment]
This Has been Fixed with #2657
