### ISSUE TITLE
[Critical] Composer needs a redeploy option 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#865]
Currently the debugger doesn't have a redeploy functionality. This is needed as the developer may want to change the bal code and redeploy. This specially comes in handy with debugging.

**Comment by hevayo** [comment]
Currently user has the option of stopping the current debug session and start again. IMO this is sufficient for the user to do some change and start debugging again.

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/1812

**Comment by hevayo** [comment]
Fixed in 0.88
