### ISSUE TITLE
Footer doesn't adjust when browser is zoomed in. 

### ISSUE THREAD

**Issue by Sewmi** [ballerinalang/composer#877]
**Environment**

OS: Mac OS (version 10.12.3)
Browser: Safari (varsion 10.0.3 )

**Steps**
1. Access Ballerina editor (graphical view)
2. Zoom out the view.

*Issue*

<img width="1439" alt="footer-issue" src="https://cloud.githubusercontent.com/assets/7960586/23092979/c360277a-f5fc-11e6-83f3-f0b1c329aff2.png">

**Comment by dakshika** [comment]
no longer valid since we remove the footer from composer.
