### ISSUE TITLE
Alignment issue of available actions (collapse, delete, etc) for a function when it is defined in the same file that has a service.

### ISSUE THREAD

**Issue by Sewmi** [ballerinalang/composer#878]
**Environment**

OS: Mac OS (version 10.12.3)
Browser: Safari (varsion 10.0.3 )

**Issue**
Alignment issue of actions available (collapse, delete, etc) for a function when it is defined in the same file that has a service.

<img width="1196" alt="reference1-formatting-issue" src="https://cloud.githubusercontent.com/assets/7960586/23093049/bde0d392-f5fe-11e6-8423-021d33a807e7.png">

**Comment by hevayo** [comment]
Diagram Implementation has changed and with the new implementation above behavior is not observed.
