### ISSUE TITLE
Composer -> Run gives wrong result for the 'xmlutils:toString'

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#880]
- Draw a main function for below

import ballerina.lang.system;
import ballerina.lang.xmlutils;
function main(string[] args) {
	xml newXml = `<emp><name>Doe</name></emp>`;
	system:println(xmlutils:toString(newXml));	
}

- Run the file from editor
Actual Result: Doe
Expected result: `<emp><name>Doe</name></emp>`
- But the runtime gives the correct result.

**Comment by maheeka** [comment]
fixed with https://github.com/ballerinalang/composer/pull/1310
