### ISSUE TITLE
Remove JQuery-UI libraries.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#89]
<a href="https://github.com/hemikak"><img src="https://avatars.githubusercontent.com/u/4398820?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hemikak](https://github.com/hemikak)**
_Monday Jan 16, 2017 at 04:43 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/799_

----

We are not using Jquery-UI libraries for any work, hence we need to remove them.

**Comment by dakshika** [comment]
this should be changed to react based drag and drop

**Comment by hevayo** [comment]
removed in 0.9.4
