### ISSUE TITLE
Have a way to clear browser storage for the editor. Probably through a menu item.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#90]
<a href="https://github.com/hemikak"><img src="https://avatars.githubusercontent.com/u/4398820?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hemikak](https://github.com/hemikak)**
_Monday Jan 16, 2017 at 05:51 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/802_

----

This is useful in many ways.
1. Helps the user to do a reset on the editor so that they can start from the very beginning.
2. If we(devs) modify the way we store content in the browser storage, the user's will can clear the existing stored data so that it wont conflict with the new and the old way of storing data.

**Comment by maheeka** [comment]
Storage should be transparent to the user.
