### ISSUE TITLE
Code formatting not considered as dirty state

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#911]
If there is a syntax error that stops user from navigating to design or swagger view, by doing a code format user is allowed to switch to design/swagger. This is because code formatting is not considered as a dirty state. At this point all the content is removed when switching to design/swagger view and back to source.

**Comment by kaviththiranga** [comment]
Fixed with 2b104bf20d31766c56ce52c7bccb0c330754a527 & 52efc7b2fb2097e643adad0ea17d3f092ef542d9
