### ISSUE TITLE
Add a scroll for struct field types

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#917]
Not all types are listed below even though type and filtering is provided.
<img width="269" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23097253/31116704-f655-11e6-8745-d1b3ca0ba0ff.png">
<img width="254" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23097258/523676ea-f655-11e6-8b4b-2cf3dc259c73.png">

Can we provide a scroll for this?

**Comment by roonyh** [comment]
![screenshot from 2017-07-24 15-28-09](https://user-images.githubusercontent.com/3872221/28518307-0df67c96-7085-11e7-9438-602d9b868c9a.png)
In current master a scroll is provided. And all the types seem to be listed.

**Comment by pahans** [comment]
closing based on above comment.
