### ISSUE TITLE
[Editor] When connector and action available in a resource adding a long function expression arrow between connector and action does not connect correctly

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/composer#919]
Steps:
[1]. Add a service and resource.
[2]. Add a connector to resource.
[3]. Add a long function from an package
![issue-1](https://cloud.githubusercontent.com/assets/9109762/23097341/6d993132-f657-11e6-9c01-bba22b837bd6.png)

**Comment by maheeka** [comment]
issue still exists in latest.
<img width="603" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23297169/76da771a-fa9e-11e6-9836-0f695cd0335d.png">
Add three action invocations as in the screenshot. Modify one to have a long expression. Arrows get misaligned.

**Comment by hevayo** [comment]
Fixed with the react based diagram rendering.
