### ISSUE TITLE
UX- Run console not disappears properly when move to next file's source view and close the console

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#930]
- Add two bal files (program or service)
- Run one bal : Run console will be appear at bottom
- Move to next file -> source view : Still you can see the run console at bottom
- Close the console : Now you can see the console window still appears as dark panel. If you scroll the source window, it looks like the codes coming out from another layer.

![console](https://cloud.githubusercontent.com/assets/15671620/23099983/52cd30c2-f69a-11e6-96c4-1ef31d6a97f2.jpeg)

**Comment by nadeeshaan** [comment]
The last mentioned point has been fixed. Hence removing the label Bug

**Comment by hevayo** [comment]
Fixed in 0.9.4
