### ISSUE TITLE
Change the default font size displays in Setting->Font Size as per actual font size appears in source view

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#931]
By default it displays 10px in 'Font Size' text field, but actual font size looks more than that (~18px).
Usability issue: User wants to increase and change it to >10px (e.g. 14px) but it get decreased since font appears size already more than that.

![pixel](https://cloud.githubusercontent.com/assets/15671620/23100081/ffeff968-f69c-11e6-9df9-a11e8ab3d004.jpeg)

**Comment by dakshika** [comment]
Current now it's 14px but we need to show the default value on the settings page. currently its not showing the default values.

**Comment by NatashaWso2** [comment]
This feature is currently not available. So the composer preferences cannot be changed by the user. This will be supported by future versions of composer hence closing this issue.
