### ISSUE TITLE
Cannot change the size of the console

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#941]
Currently the console cannot be changed in size. This obstructs use of functionalities as debugger as the user have to scroll up/down to view even near neighbours.
Chrome: 54.0.2840.100
![compose_bug_consoleresize](https://cloud.githubusercontent.com/assets/15624590/23101383/4f69ded0-f6b8-11e6-9e68-f291afef32db.png)

**Comment by hevayo** [comment]
Duplicate issue this is originally captured in enhancements task list see #723. Will close this issue and use the task list for tracking.
