### ISSUE TITLE
Design view gets distorted when switched from source view to design view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#947]
Please see the attached images. The design view is distorted after switching back from source view to design view

**Image 1**
![compose_bug_designview_1](https://cloud.githubusercontent.com/assets/15624590/23101678/4ca9defa-f6bf-11e6-8bca-ec9d716d3490.png)

**Image 2**
![composer_bug_designdistorted](https://cloud.githubusercontent.com/assets/15624590/23101685/6ba97586-f6bf-11e6-8219-cc1fb834e631.png)

**Comment by nadeeshaan** [comment]
Can you please specify the steps to reproduce the mentioned scenario

**Comment by hevayo** [comment]
The implementation has differ and the mention issue is no longer seen after 0.87 release.
