### ISSUE TITLE
connector action call from conditional statement misplaced if another statement removed from same block

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#948]
connector action call misplaced if another statement deleted from conditional statement block
- Draw a main function, connector and an action
- Drop "if" or "while" statement 
- drop any statements (e.g. variable) inside "if"
- drag and drop connector action call inside of "if"
- delete one of previous statement (variable) : connector call misplaced

![conn4](https://cloud.githubusercontent.com/assets/15671620/23101675/2db409ee-f6bf-11e6-9fb6-1211318075b3.jpeg)
![conn5](https://cloud.githubusercontent.com/assets/15671620/23101734/991862d8-f6c0-11e6-985c-c38917d0eb3c.jpeg)

**Comment by sumuditha-viraj** [comment]
Came across some other issues as well while adding connector declarations and function declarations inside if/else 

<img width="325" alt="screen shot 2017-03-15 at 1 57 28 pm" src="https://cloud.githubusercontent.com/assets/6814264/23939579/5f2004f8-0987-11e7-8624-d15647a533c3.png">
<img width="339" alt="screen shot 2017-03-15 at 1 57 02 pm" src="https://cloud.githubusercontent.com/assets/6814264/23939590/6942a396-0987-11e7-9f20-da43586c847d.png">

**Comment by nadeeshaan** [comment]
closing since the fix is merged
