### ISSUE TITLE
When debugging is stopped and another request comes, the debug control view does not get refreshed

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#951]
**Steps**
1. Initialize a debug
2. Stop debug without completing the debug process (do not stop the server)
3. Send a request

Expected result: The debug control view should be cleared and the button focus should be on resume
Actual result: The previous debug information is still there as shown in the image.

![composer_bug_debuggernotcleared](https://cloud.githubusercontent.com/assets/15624590/23101987/a30b8b8e-f6c6-11e6-8abd-7762c87a5b11.png)

**Comment by pahans** [comment]
added a event to clear existing debug hit on completing debug session. https://github.com/ballerinalang/composer/pull/1179/commits/583e9cd7cd99c3c9de9407ee1780a119948881df#diff-28997319bc91376299f122b4368ac687R445

**Comment by nadeeshaan** [comment]
Closing since fix https://github.com/ballerinalang/composer/pull/1179 merged
