### ISSUE TITLE
Open folder throws errors when path is given and enter key is pressed

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#955]
**Steps**
1. Select open folder from menu
2. Provide a path for the desired path and press enter key

Expected result: The folder location should be open
Actual result: Error is thrown in browser with a redirection as shown in the image
![composer_bug_openfolder](https://cloud.githubusercontent.com/assets/15624590/23102338/82a6363a-f6cd-11e6-8870-bb4db3d92b01.png)

**Comment by sumuditha-viraj** [comment]
Fixed with #1195

**Comment by sumuditha-viraj** [comment]
Fixed
