### ISSUE TITLE
Same location is opened and duplicated in file explorer

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#957]
**Steps**
1. Open a folder location by providing folder path -> Opens the location in file explorer
2. Again provide the same path and open the folder location

Expected result: User should be directed to the already opened folder location
Actual result: The same location is opened twice in file explorer as shown in the image.

![composer_bug_openfolder_2](https://cloud.githubusercontent.com/assets/15624590/23102402/6b1a8880-f6ce-11e6-9979-26dfd5c641cc.png)

**Comment by sumuditha-viraj** [comment]
Fixed in #1226

**Comment by sumuditha-viraj** [comment]
Fixed.
