### ISSUE TITLE
Issue when rendering components of file editor

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#958]
Current rendering logic for consts, packages and imports is not consistent. The components are sometimes redrawn and sometimes missed due to visitor and sequential drawing conflicts.

Revisit the logic and refactor this.

Refer related issues below : 
When backend is down and refresh composer : 
<img width="403" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/23102439/3fe94862-f6cf-11e6-83d9-07a816a47cea.png">
When navigating back and forth with errorneous source in swagger : 
![image](https://cloud.githubusercontent.com/assets/1029806/23102447/605960f0-f6cf-11e6-9f7b-2a4e33433fb7.png)

**Comment by sumuditha-viraj** [comment]
Closing as per the comment in #928

**Comment by sumuditha-viraj** [comment]
This is a different issue than #928

**Comment by hevayo** [comment]
Closing the issue since the implementation has differed.
