### ISSUE TITLE
jsonutil:set signature is not informative enough

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#959]
Currently in the composer the jsonutil:set signature is as below

`jsonutils:set(json , string , string );`

The runtime method signature for setting a string value is as below

`set (json j, string jsonPath, string value)`

The current method signature shown in the compser does not provide a clear picture to the user to how to use it. So please change it so it will be similar to the method signature provided by the runtime.

**Comment by maheeka** [comment]
Captured in https://github.com/ballerinalang/composer/issues/2059. Hence closing.
