### ISSUE TITLE
xmlutils:set() - only "xmlutils:set(xml, string, xml, map)" was added to tool palette, and it is not working.

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#960]
- From the xmlutils native function below 3 are listed:
1. set (xml x, string xPath, xml value, map namespaces)
2. set (xml x, string xPath, string value) 
3. set (xml x, string xPath, string value, map namespaces)

- function with name space [1.] is available in tool palette but it is not working [4]
- There is no function for others [2.] & [3.]
- with modified #arguments, it is working anyway (see attached xmlutils.txt - bal file)

Shouldn't we add all functions in the tool palette? or as per user preference he needs to change #arguments?
[4] Error:
ballerina: stockQuoteRESTService.bal:15: reference type initializer is not allowed here
[xmlutils.txt](https://github.com/ballerinalang/composer/files/785869/xmlutils.txt)

**Comment by hevayo** [comment]
This issue is no longer exist since we do not support method overloading.
