### ISSUE TITLE
Debugger Active draws long with json value length

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#966]
As showed in the image, with the json value length, the view grows broader. We need to handle this so that a lengthy json will be shown smartly without much expand to the "Debugger Active" view

![composer_bug_debugger_4](https://cloud.githubusercontent.com/assets/15624590/23103847/cd510024-f6e7-11e6-96f2-6d7f544fff73.png)

**Comment by pahans** [comment]
fixed with https://github.com/ballerinalang/composer/pull/2818
