### ISSUE TITLE
SQL: Connector definition always comes to the first line.

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/composer#967]
When we define the sql connector we have to provide a map to that.
Steps:
 1. Add and declare a map and initialize
 2. Add a sqlConnector 
 3. Switch to source view.

The connector is in first line before the map.

![image](https://cloud.githubusercontent.com/assets/7115693/23104059/6f2f8948-f6ec-11e6-87c1-ed94e40c03b0.png)

**Comment by nadeeshaan** [comment]
This statement positioning issue has been fixed in the current master. Now the connector initialization also added in the order as we are adding the other statements. Since closing
