### ISSUE TITLE
Alignment issue when the variable's value is long(sql datasource map)

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/composer#969]
Steps:
1. Add a service and resource
2. Add a map type variable
3. Initialize the map with long value.(ex:- sql data source)
Better to wrap the text to the visible area
plz, refer the image below.

![image](https://cloud.githubusercontent.com/assets/7115693/23104186/fc041288-f6ee-11e6-8ec3-2b334ccec3d7.png)

**Comment by hevayo** [comment]
The implementation has differed but we need to check if the same issue is there in the new implementation.

**Comment by roonyh** [comment]
![screenshot from 2017-07-24 15-00-32](https://user-images.githubusercontent.com/3872221/28517116-06343bb4-7081-11e7-8b05-e2fbdf629d7c.png)

The new implementation truncates long variable names. This can be closed.

**Comment by nadeeshaan** [comment]
Closing according to the previous comment
