### ISSUE TITLE
Cannot debug a newly added segment 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#970]
1. Create a service in composer
2. Debug it.
3. Add a new segment (e.g. assignment)
4. Save and restart the debugging server
5. Try to add a debug point to the newly added segment

As shown in the attached image, the debug point is not added for the newly added segment (for the image its int i=2)

![composer_bug_debugger_6](https://cloud.githubusercontent.com/assets/15624590/23104258/39869738-f6f0-11e6-8517-9557afb64973.png)

**Comment by hevayo** [comment]
Can you please specify the version this was tested, also can you try this out in the latest release 0.8.

**Comment by hevayo** [comment]
Ack we were able to reproduce this in 0.8.

**Comment by pahans** [comment]
fixed in 0.90
