### ISSUE TITLE
Syntax when initializing a struct is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#974]
1. Add a struct with 2 variables
2. Add a main method and a variable definition and add the following in the variable definition
Person p22 = {name:"Graham",age:39}
3. Check the code generated

Issue
The code generated will be as follows. This should be corrected
```
Person p22 = {name:"Graham", age:39
	}
	;
```

**Comment by TanyaM** [comment]
Syntax is correct. Issue is in the formatting of the syntax.

**Comment by pahans** [comment]
this is fixed in the latest master.
