### ISSUE TITLE
Composer failes to stop the started servevice with IBM JDK 1.8

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/composer#978]
Issue:
1. Start composer on IBM JDK 1.8
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3-20160428_01(SR3))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20160427_301573 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160427_1620_B301573
JIT  - tr.r14.java.green_20160329_114288
GC   - R28_Java8_SR3_20160427_1620_B301573_CMPRSS
J9CL - 20160427_301573)
JCL - 20160421_01 based on Oracle jdk8u91-b14

2. Draw the following service 
```
import ballerina.net.jms;
import ballerina.lang.system;
import ballerina.lang.messages;
@http:BasePath("/myService")
service jmsWSO2MBQueueSenderService {
	
	@http:POST
	@http:Path("/base")
	resource onMessage1(message m) {
		jms:ClientConnector endpoint = create jms:ClientConnector("org.wso2.andes.jndi.PropertiesFileInitialContextFactory", "jndi.properties");
		system:println("Message In Queue:::::::::::" + messages:getStringPayload(m));
		string messageType;
		messageType = "ObjectMessage";
		map dataMap = {};
		boolean result = jms:ClientConnector.send(endpoint, "QpidConnectionFactory", "ballerina", "queue", messageType, m, dataMap);
		system:print(result);
		
	}

}
```
3. Run the service using Composer-->Run --Service

4. Stop the service

Issue:
Composer fails to completely stop the service
![selection_190](https://cloud.githubusercontent.com/assets/3368635/23104597/f7b25e44-f6f6-11e6-8cf6-c4ad843632f1.png)

Composer Console has following issue
![selection_191](https://cloud.githubusercontent.com/assets/3368635/23104602/0aaff498-f6f7-11e6-9e54-5faf10268feb.png)

On Oracle JDK 1.8 this works as expected
![selection_192](https://cloud.githubusercontent.com/assets/3368635/23104606/1b5dbb68-f6f7-11e6-851c-70ffc80a811b.png)

**Comment by hevayo** [comment]
This is fixed with the new terminate logic.
