### ISSUE TITLE
For both Application and service, the stop option shows only "Stop Application"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#980]
Currently in composer there are two run and debugging options as Application and Service. But when stopping it shows as Application. This is misleading. Ideally when a service is up and running, it should show as "Stop service" and when an application is running it should show as "Stop Application"

**Comment by NipunaMarcus** [comment]
What if we only show label as "Stop"? that will indicate to stop the whatever that is running now.

**Comment by hevayo** [comment]
in 0.9.4 for both application and service it will say stop.
