### ISSUE TITLE
Import section get distorted when more than three imports are added

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#983]
Please see the attached image, the import section is distorted when more than three imports added. 
![composer_bug_imports_1](https://cloud.githubusercontent.com/assets/15624590/23104975/c055f062-f6fd-11e6-942f-935a0e9ca098.png)

**Comment by maheeka** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/1055/commits
