### ISSUE TITLE
Remoting debugging is not working.

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#986]
1. Started a ballerina runtime distribution with debug 5006 option
2. Connected composer to that using url as "localhost:5006"

Connection was not successful. Following error was seen in the ballerina console
`Debugger failed to attach: handshake failed - received >GET /debug HTT< - expected >JDWP-Handshake<`

Composer: Please see attached image
![composer_bug_remotedebugger](https://cloud.githubusercontent.com/assets/15624590/23105241/e484002e-f701-11e6-87bb-2c9fed92b759.png)

**Comment by hevayo** [comment]
Not a bug, but we need to add how to debug in to command help.
