### ISSUE TITLE
Intermittent unusual issues in the editor when many structs and type mappers are added

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#988]
![structs111](https://cloud.githubusercontent.com/assets/1845370/23105540/061b35c2-f707-11e6-9579-c7c4344d914b.png)

![struct444](https://cloud.githubusercontent.com/assets/1845370/23105546/129860e0-f707-11e6-972d-4494c74a7303.png)

![struct555](https://cloud.githubusercontent.com/assets/1845370/23105570/5a2a54a4-f707-11e6-851a-3e27d825b97a.png)

![struct666](https://cloud.githubusercontent.com/assets/1845370/23105667/8c9cac1a-f708-11e6-8db7-d76dd237ce4e.png)

**Comment by sinthuja** [comment]
I tried to reproduce this issue, and I only reproduced the last effect shown above. As we have fixed several issues in the similar case, mostly I believe the other problems also could have solved. Therefore I would consider the last problem, where the resizing of the type mapper didn't happen as expected as a issue yet to be solved.

**Comment by nadeeshaan** [comment]
@sinthuja can you please confirm whether the aforementioned last issue is fixed in the latest master branch?

**Comment by keizer619** [comment]
There was an issue when loading drop down boxes on refresh. Now it has been [fixed](https://github.com/keizer619/composer/commit/611be054973d02431dbbb30a658859a368f81f41). The resizing of the type mapper is completely rewritten and resizing of the type mapper works and should work like following screenshot.

<img width="1223" alt="screen shot 2017-04-28 at 12 11 05 pm" src="https://cloud.githubusercontent.com/assets/2918812/25517143/a04931d8-2c0b-11e7-88e3-981a005de73c.png">

**Comment by hevayo** [comment]
The implementation of the type mapper have change thus the bug is no longer relevent. see 0.88
