### ISSUE TITLE
User defined functions cannot be added inside a type mapper

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#991]
Browser: Chrome and Firefox
1. Add a coordinates struct
2. Add a location struct
3. Create a getCountry function
4. Add a type mapper and try to add the getCountry() function to the type mapper

Issue
Cannot add the function. 
Note: Native functions can be added

**Comment by sinthuja** [comment]
This issue is fixed in dnwick/composer with revision number - 26f2a4eb3230a7173b1d03cff91b6f142dd4e7ab. The fix will be available in 0.8.1 composer.

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing
