### ISSUE TITLE
Provide a mechanism to provide command line arguments when running an application

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#999]
For most of users, the first try out may be a simple application that in takes command line arguments. Currently in composer there is no way to provide command line arguments. Please provide a mechanism to increase user experience.

**Comment by nadeeshaan** [comment]
You can configure the command line arguments as shown in the bellow screenshot. Hence closing

![selection_069](https://cloud.githubusercontent.com/assets/1329674/24182135/afe18368-0ee5-11e7-94d4-ae0f30fcbe5c.png)
